Kestrel Interface: kest_effect_view.c File Reference
kest_effect_view.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
kest_ui_page * create_effect_view_for (kest_effect *effect)
int init_effect_view (kest_ui_page *page)
void effect_view_enter_settings_cb (lv_event_t *e)
int configure_effect_view (kest_ui_page *page, void *data)
int create_effect_view_ui (kest_ui_page *page)
int enter_effect_view (kest_ui_page *page)
int clear_effect_view ()
int free_effect_view_ui (kest_ui_page *page)
int free_effect_view (kest_ui_page *page)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_effect_view.c.
Function Documentation
clear_effect_view()
int clear_effect_view ()
Definition at line 309 of file kest_effect_view.c.
configure_effect_view()
int configure_effect_view (kest_ui_page * page, void * data)
Definition at line 106 of file kest_effect_view.c.
Referenced by create_effect_view_for(), and init_effect_view().
create_effect_view_for()
kest_ui_page * create_effect_view_for (kest_effect * effect)
Definition at line 9 of file kest_effect_view.c.
create_effect_view_ui()
int create_effect_view_ui (kest_ui_page * page)
Definition at line 192 of file kest_effect_view.c.
Referenced by add_effect_from_menu_eff(), and init_effect_view().
effect_view_enter_settings_cb()
void effect_view_enter_settings_cb (lv_event_t * e)
Definition at line 91 of file kest_effect_view.c.
Referenced by configure_effect_view().
enter_effect_view()
int enter_effect_view (kest_ui_page * page)
Definition at line 301 of file kest_effect_view.c.
Referenced by init_effect_view().
free_effect_view()
int free_effect_view (kest_ui_page * page)
Definition at line 324 of file kest_effect_view.c.
Referenced by create_effect_view_for(), free_effect(), and gut_effect().
free_effect_view_ui()
int free_effect_view_ui (kest_ui_page * page)
Definition at line 314 of file kest_effect_view.c.
init_effect_view()
int init_effect_view (kest_ui_page * page)
Definition at line 43 of file kest_effect_view.c.
Referenced by create_effect_view_for().