Kestrel Interface: kest_button.h File Reference
kest_button.h File Reference
#include "kest_representation.h"
Data Structures
struct kest_button
struct kest_danger_button
struct kest_active_button
struct kest_active_button_array
Macros
#define STANDARD_DEL_BTN_REMAIN_MS 1000
#define STANDARD_BUTTON_HEIGHT ((int)(0.07 * DISPLAY_VRES))
#define STANDARD_BUTTON_SHORT_HEIGHT ((int)(0.06 * DISPLAY_VRES))
#define KEST_BUTTON_HEIGHT STANDARD_BUTTON_HEIGHT
#define KEST_BUTTON_WIDTH (STANDARD_CONTAINER_WIDTH - (3 * GLOBAL_PAD_WIDTH))
#define KEST_BUTTON_SCALE_EXPAND 1
#define KEST_BUTTON_SCALE_CONTRACT 0
#define KEST_BUTTON_LP_SCALE 1.05
#define KEST_BUTTON_SCALE_ANIM_MS 75
#define KEST_BUTTON_GLIDE_ANIM_MS 150
#define KEST_BUTTON_DEL_BTN_FADE_IN_MS 75
#define KEST_BUTTON_DEL_BTN_FADE_OUT_MS 300
#define KEST_BUTTON_DEL_BTN_REMAIN_MS STANDARD_DEL_BTN_REMAIN_MS
#define KEST_BUTTON_DEL_ANIM_MS 100
#define KEST_BUTTON_ARRAY_BASE_Y ((int)(0.021f * DISPLAY_VRES))
#define KEST_BUTTON_V_PAD ((int)(0.028f * DISPLAY_VRES))
#define KEST_BUTTON_DISTANCE (KEST_BUTTON_HEIGHT + KEST_BUTTON_V_PAD)
#define KEST_BUTTON_MAX_SUB_BUTTONS 2
#define KEST_BUTTON_DISABLED_OPACITY 128
#define KEST_BUTTON_FLAG_HIDDEN 0b0001
#define KEST_BUTTON_FLAG_DISABLED 0b0010
#define KEST_BUTTON_FLAG_UNCLICKABLE 0b0100
#define KEST_BUTTON_FLAG_NO_ALIGN 0b1000
#define DANGER_BUTTON_CONFIRM_TEXT "Yes"
#define DANGER_BUTTON_CANCEL_TEXT "Cancel"
#define DANGER_BUTTON_POPUP_HEIGHT ((int)(0.25 * DISPLAY_VRES))
#define DANGER_BUTTON_POPUP_WIDTH ((int)(0.6 * DISPLAY_HRES))
#define DANGER_BUTTON_POPUP_BUTTON_HEIGHT ((int)(0.045 * DISPLAY_VRES))
#define DANGER_BUTTON_POPUP_BUTTON_WIDTH ((int)(0.2 * DISPLAY_HRES))
#define KEST_ACTIVE_BUTTON_ARRAY_FLAG_DELETEABLE 0b0001
#define KEST_ACTIVE_BUTTON_ARRAY_FLAG_MOVEABLE 0b0010
Functions
int init_button (kest_button *button)
kest_button * new_button (const char *label)
int kest_button_create_label_ui (kest_button *button)
int create_button_ui (kest_button *button, lv_obj_t *parent)
int button_set_clicked_cb (kest_button *button, lv_event_cb_t cb, void *cb_arg)
int button_set_pressing_cb (kest_button *button, lv_event_cb_t cb, void *cb_arg)
int button_set_long_pressed_cb (kest_button *button, lv_event_cb_t cb, void *cb_arg)
int button_set_released_cb (kest_button *button, lv_event_cb_t cb, void *cb_arg)
int kest_button_set_label (kest_button *button, const char *label)
int kest_button_disable_alignment (kest_button *button)
int kest_button_set_alignment (kest_button *button, lv_align_t align, int offs_x, int offs_y)
int kest_button_set_size (kest_button *button, int width, int height)
int kest_button_add_sub_button (kest_button *button, kest_button *sub_button)
int kest_button_hide (kest_button *button)
int kest_button_unhide (kest_button *button)
int kest_button_set_clickable (kest_button *button)
int kest_button_set_unclickable (kest_button *button)
int kest_button_set_opacity (kest_button *button, int opacity)
int kest_button_enable (kest_button *button)
int kest_button_disable (kest_button *button)
int kest_button_delete_ui (kest_button *button)
int init_danger_button (kest_danger_button *button, void(*action_cb)(void *data), void *cb_arg, struct kest_ui_page *parent)
int kest_danger_button_create_ui (kest_danger_button *button, lv_obj_t *parent)
void kest_danger_button_activate_popup_cb (lv_event_t *e)
void kest_danger_button_value_changed_cb (lv_event_t *e)
DECLARE_LINKED_PTR_LIST (kest_active_button)
int kest_active_button_add_del_button (kest_active_button *button)
int kest_active_button_change_label (kest_active_button *button, char *text)
int kest_active_button_swap_del_button_for_persistent_unclickable (kest_active_button *button, const char *label)
int kest_active_button_reset_del_button (kest_active_button *button)
int kest_active_button_set_dimensions (kest_active_button *button, int w, int h)
int kest_active_button_create_ui (kest_active_button *button, lv_obj_t *parent)
void kest_active_button_free (kest_active_button *button)
void kest_active_button_set_representation (kest_active_button *button, void *representer, void *representee, void(*update)(void *, void *))
int kest_active_button_array_index_y_position (kest_active_button_array *array, int index)
kest_active_button_array * kest_active_button_array_new ()
int kest_active_button_array_append (kest_active_button *button, kest_active_button_array *array)
kest_active_button * kest_active_button_array_append_new (kest_active_button_array *array, void *data, char *label)
int kest_active_button_array_remove (kest_active_button_array *array, int index)
int kest_active_button_array_set_length (kest_active_button_array *array, int n)
int kest_active_button_array_set_dimensions (kest_active_button_array *array, int w, int h)
int kest_active_button_array_create_ui (kest_active_button_array *array, lv_obj_t *parent)
Macro Definition Documentation
DANGER_BUTTON_CANCEL_TEXT
#define DANGER_BUTTON_CANCEL_TEXT "Cancel"
Definition at line 116 of file kest_button.h.
Referenced by kest_danger_button_activate_popup_cb().
DANGER_BUTTON_CONFIRM_TEXT
#define DANGER_BUTTON_CONFIRM_TEXT "Yes"
Definition at line 115 of file kest_button.h.
Referenced by kest_danger_button_activate_popup_cb(), and kest_danger_button_value_changed_cb().
DANGER_BUTTON_POPUP_BUTTON_HEIGHT
#define DANGER_BUTTON_POPUP_BUTTON_HEIGHT ((int)(0.045 * DISPLAY_VRES))
Definition at line 121 of file kest_button.h.
Referenced by kest_danger_button_activate_popup_cb().
DANGER_BUTTON_POPUP_BUTTON_WIDTH
#define DANGER_BUTTON_POPUP_BUTTON_WIDTH ((int)(0.2 * DISPLAY_HRES))
Definition at line 122 of file kest_button.h.
Referenced by kest_danger_button_activate_popup_cb().
DANGER_BUTTON_POPUP_HEIGHT
#define DANGER_BUTTON_POPUP_HEIGHT ((int)(0.25 * DISPLAY_VRES))
Definition at line 118 of file kest_button.h.
Referenced by kest_danger_button_activate_popup_cb().
DANGER_BUTTON_POPUP_WIDTH
#define DANGER_BUTTON_POPUP_WIDTH ((int)(0.6 * DISPLAY_HRES))
Definition at line 119 of file kest_button.h.
Referenced by kest_danger_button_activate_popup_cb().
KEST_ACTIVE_BUTTON_ARRAY_FLAG_DELETEABLE
#define KEST_ACTIVE_BUTTON_ARRAY_FLAG_DELETEABLE 0b0001
Definition at line 189 of file kest_button.h.
Referenced by init_profile_view(), init_sequence_view(), init_test_page(), kest_active_button_array_append_new(), kest_active_button_long_pressed_cb(), and kest_active_button_release_cb().
KEST_ACTIVE_BUTTON_ARRAY_FLAG_MOVEABLE
#define KEST_ACTIVE_BUTTON_ARRAY_FLAG_MOVEABLE 0b0010
Definition at line 190 of file kest_button.h.
Referenced by init_profile_view(), init_sequence_view(), init_test_page(), kest_active_button_long_pressed_cb(), kest_active_button_pressing_cb(), and kest_active_button_release_cb().
KEST_BUTTON_ARRAY_BASE_Y
#define KEST_BUTTON_ARRAY_BASE_Y ((int)(0.021f * DISPLAY_VRES))
Definition at line 27 of file kest_button.h.
Referenced by kest_active_button_array_init().
KEST_BUTTON_DEL_ANIM_MS
#define KEST_BUTTON_DEL_ANIM_MS 100
Definition at line 25 of file kest_button.h.
Referenced by kest_active_button_trigger_delete_anim().
KEST_BUTTON_DEL_BTN_FADE_IN_MS
#define KEST_BUTTON_DEL_BTN_FADE_IN_MS 75
Definition at line 21 of file kest_button.h.
Referenced by kest_active_button_trigger_del_button_fade_in().
KEST_BUTTON_DEL_BTN_FADE_OUT_MS
#define KEST_BUTTON_DEL_BTN_FADE_OUT_MS 300
Definition at line 22 of file kest_button.h.
Referenced by kest_active_button_trigger_del_button_fade_out().
KEST_BUTTON_DEL_BTN_REMAIN_MS
#define KEST_BUTTON_DEL_BTN_REMAIN_MS STANDARD_DEL_BTN_REMAIN_MS
Definition at line 23 of file kest_button.h.
Referenced by kest_active_button_release_cb().
KEST_BUTTON_DISABLED_OPACITY
#define KEST_BUTTON_DISABLED_OPACITY 128
Definition at line 35 of file kest_button.h.
KEST_BUTTON_DISTANCE
#define KEST_BUTTON_DISTANCE (KEST_BUTTON_HEIGHT + KEST_BUTTON_V_PAD)
Definition at line 30 of file kest_button.h.
Referenced by kest_active_button_array_index_y_position().
KEST_BUTTON_FLAG_DISABLED
#define KEST_BUTTON_FLAG_DISABLED 0b0010
Definition at line 38 of file kest_button.h.
Referenced by create_button_ui(), kest_button_disable(), and kest_button_enable().
KEST_BUTTON_FLAG_HIDDEN
#define KEST_BUTTON_FLAG_HIDDEN 0b0001
Definition at line 37 of file kest_button.h.
Referenced by create_button_ui(), kest_button_hide(), kest_button_set_opacity(), and kest_button_unhide().
KEST_BUTTON_FLAG_NO_ALIGN
#define KEST_BUTTON_FLAG_NO_ALIGN 0b1000
Definition at line 40 of file kest_button.h.
Referenced by create_button_ui(), kest_button_disable_alignment(), and kest_button_set_alignment().
KEST_BUTTON_FLAG_UNCLICKABLE
#define KEST_BUTTON_FLAG_UNCLICKABLE 0b0100
Definition at line 39 of file kest_button.h.
Referenced by create_button_ui(), kest_button_set_clickable(), and kest_button_set_unclickable().
KEST_BUTTON_GLIDE_ANIM_MS
#define KEST_BUTTON_GLIDE_ANIM_MS 150
Definition at line 19 of file kest_button.h.
Referenced by kest_active_button_trigger_glide_anim().
KEST_BUTTON_HEIGHT
#define KEST_BUTTON_HEIGHT STANDARD_BUTTON_HEIGHT
Definition at line 11 of file kest_button.h.
Referenced by init_button(), and kest_active_button_array_init().
KEST_BUTTON_LP_SCALE
#define KEST_BUTTON_LP_SCALE 1.05
Definition at line 17 of file kest_button.h.
Referenced by kest_active_button_trigger_scale_anim().
KEST_BUTTON_MAX_SUB_BUTTONS
#define KEST_BUTTON_MAX_SUB_BUTTONS 2
Definition at line 33 of file kest_button.h.
Referenced by init_button(), and kest_button_add_sub_button().
KEST_BUTTON_SCALE_ANIM_MS
#define KEST_BUTTON_SCALE_ANIM_MS 75
Definition at line 18 of file kest_button.h.
Referenced by kest_active_button_trigger_scale_anim().
KEST_BUTTON_SCALE_CONTRACT
#define KEST_BUTTON_SCALE_CONTRACT 0
Definition at line 15 of file kest_button.h.
Referenced by kest_active_button_release_cb().
KEST_BUTTON_SCALE_EXPAND
#define KEST_BUTTON_SCALE_EXPAND 1
Definition at line 14 of file kest_button.h.
Referenced by kest_active_button_long_pressed_cb().
KEST_BUTTON_V_PAD
#define KEST_BUTTON_V_PAD ((int)(0.028f * DISPLAY_VRES))
Definition at line 29 of file kest_button.h.
KEST_BUTTON_WIDTH
#define KEST_BUTTON_WIDTH (STANDARD_CONTAINER_WIDTH - (3 * GLOBAL_PAD_WIDTH))
Definition at line 12 of file kest_button.h.
Referenced by init_button(), and kest_active_button_array_init().
STANDARD_BUTTON_HEIGHT
#define STANDARD_BUTTON_HEIGHT ((int)(0.07 * DISPLAY_VRES))
Definition at line 8 of file kest_button.h.
Referenced by create_menu_item_ui(), create_standard_button_click(), create_standard_button_long_press_release(), and ui_page_create_bottom_buttons().
STANDARD_BUTTON_SHORT_HEIGHT
#define STANDARD_BUTTON_SHORT_HEIGHT ((int)(0.06 * DISPLAY_VRES))
Definition at line 9 of file kest_button.h.
Referenced by create_standard_button_click_short(), and setting_widget_create_ui_no_callback().
STANDARD_DEL_BTN_REMAIN_MS
#define STANDARD_DEL_BTN_REMAIN_MS 1000
Definition at line 6 of file kest_button.h.
Referenced by menu_item_profile_listing_released_cb(), and menu_item_sequence_listing_released_cb().
Function Documentation
button_set_clicked_cb()
int button_set_clicked_cb (kest_button * button, lv_event_cb_t cb, void * cb_arg)
Definition at line 158 of file kest_button.c.
Referenced by configure_main_menu(), init_danger_button(), kest_active_button_add_del_button(), kest_active_button_init(), ui_page_add_back_button(), ui_page_add_bottom_button(), ui_page_add_left_panel_button(), ui_page_add_parent_button(), and ui_page_add_right_panel_button().
button_set_long_pressed_cb()
int button_set_long_pressed_cb (kest_button * button, lv_event_cb_t cb, void * cb_arg)
Definition at line 186 of file kest_button.c.
Referenced by kest_active_button_init().
button_set_pressing_cb()
int button_set_pressing_cb (kest_button * button, lv_event_cb_t cb, void * cb_arg)
Definition at line 172 of file kest_button.c.
Referenced by kest_active_button_init().
button_set_released_cb()
int button_set_released_cb (kest_button * button, lv_event_cb_t cb, void * cb_arg)
Definition at line 200 of file kest_button.c.
Referenced by kest_active_button_init().
create_button_ui()
int create_button_ui (kest_button * button, lv_obj_t * parent)
Definition at line 68 of file kest_button.c.
Referenced by create_button_ui(), create_main_menu_ui(), kest_active_button_create_ui(), kest_danger_button_create_ui(), ui_page_create_bottom_buttons(), and ui_page_create_panel_ui().
DECLARE_LINKED_PTR_LIST()
DECLARE_LINKED_PTR_LIST (kest_active_button)
init_button()
int init_button (kest_button * button)
Definition at line 11 of file kest_button.c.
Referenced by configure_main_menu(), init_danger_button(), kest_active_button_add_del_button(), kest_active_button_init(), and new_button().
init_danger_button()
int init_danger_button (kest_danger_button * button, void(* action_cb)(void *data), void * cb_arg, struct kest_ui_page * parent)
Definition at line 461 of file kest_button.c.
Referenced by configure_main_menu().
kest_active_button_add_del_button()
int kest_active_button_add_del_button (kest_active_button * button)
Definition at line 1025 of file kest_button.c.
Referenced by kest_active_button_array_append_new().
kest_active_button_array_append()
int kest_active_button_array_append (kest_active_button * button, kest_active_button_array * array)
Definition at line 1331 of file kest_button.c.
Referenced by kest_active_button_array_append_new().
kest_active_button_array_append_new()
kest_active_button * kest_active_button_array_append_new (kest_active_button_array * array, void * data, char * label)
Definition at line 1290 of file kest_button.c.
Referenced by configure_profile_view(), configure_sequence_view(), init_test_page(), profile_view_append_effect(), and seq_plus_cb().
kest_active_button_array_create_ui()
int kest_active_button_array_create_ui (kest_active_button_array * array, lv_obj_t * parent)
Definition at line 1382 of file kest_button.c.
Referenced by create_profile_view_ui(), create_sequence_view_ui(), and create_test_page_ui().
kest_active_button_array_index_y_position()
int kest_active_button_array_index_y_position (kest_active_button_array * array, int index)
Definition at line 1377 of file kest_button.c.
Referenced by kest_active_button_array_append(), kest_active_button_force_index(), and kest_active_button_set_index().
kest_active_button_array_new()
kest_active_button_array * kest_active_button_array_new ()
Definition at line 1278 of file kest_button.c.
Referenced by init_profile_view(), init_sequence_view(), and init_test_page().
kest_active_button_array_remove()
int kest_active_button_array_remove (kest_active_button_array * array, int index)
Definition at line 1356 of file kest_button.c.
Referenced by kest_active_button_delete_anim_ready_cb().
kest_active_button_array_set_dimensions()
int kest_active_button_array_set_dimensions (kest_active_button_array * array, int w, int h)
Definition at line 1398 of file kest_button.c.
kest_active_button_array_set_length()
int kest_active_button_array_set_length (kest_active_button_array * array, int n)
Definition at line 1258 of file kest_button.c.
Referenced by init_profile_view(), init_sequence_view(), and init_test_page().
kest_active_button_change_label()
int kest_active_button_change_label (kest_active_button * button, char * text)
Definition at line 1132 of file kest_button.c.
Referenced by sequence_view_profile_button_rep_update().
kest_active_button_create_ui()
int kest_active_button_create_ui (kest_active_button * button, lv_obj_t * parent)
Definition at line 1067 of file kest_button.c.
Referenced by kest_active_button_array_create_ui(), profile_view_append_effect(), and seq_plus_cb().
kest_active_button_free()
void kest_active_button_free (kest_active_button * button)
Definition at line 1108 of file kest_button.c.
Referenced by kest_active_button_delete_anim_ready_cb().
kest_active_button_reset_del_button()
int kest_active_button_reset_del_button (kest_active_button * button)
Definition at line 1184 of file kest_button.c.
Referenced by sequence_view_profile_button_rep_update().
kest_active_button_set_dimensions()
int kest_active_button_set_dimensions (kest_active_button * button, int w, int h)
Definition at line 1142 of file kest_button.c.
Referenced by kest_active_button_array_set_dimensions().
kest_active_button_set_representation()
void kest_active_button_set_representation (kest_active_button * button, void * representer, void * representee, void(* update)(void *, void *))
Definition at line 1057 of file kest_button.c.
Referenced by configure_sequence_view(), and seq_plus_cb().
kest_active_button_swap_del_button_for_persistent_unclickable()
int kest_active_button_swap_del_button_for_persistent_unclickable (kest_active_button * button, const char * label)
Definition at line 1155 of file kest_button.c.
Referenced by sequence_view_profile_button_rep_update().
kest_button_add_sub_button()
int kest_button_add_sub_button (kest_button * button, kest_button * sub_button)
Definition at line 274 of file kest_button.c.
Referenced by kest_active_button_add_del_button().
kest_button_create_label_ui()
int kest_button_create_label_ui (kest_button * button)
Definition at line 144 of file kest_button.c.
Referenced by kest_active_button_reset_del_button(), kest_active_button_swap_del_button_for_persistent_unclickable(), and kest_button_set_label().
kest_button_delete_ui()
int kest_button_delete_ui (kest_button * button)
Definition at line 434 of file kest_button.c.
Referenced by kest_active_button_free(), and kest_button_delete_ui().
kest_button_disable()
int kest_button_disable (kest_button * button)
Definition at line 401 of file kest_button.c.
Referenced by configure_profile_view(), create_profile_view_ui(), create_sequence_view_ui(), profile_view_rep_update(), and sequence_view_rep_update().
kest_button_disable_alignment()
int kest_button_disable_alignment (kest_button * button)
Definition at line 233 of file kest_button.c.
Referenced by configure_main_menu().
kest_button_enable()
int kest_button_enable (kest_button * button)
Definition at line 388 of file kest_button.c.
Referenced by profile_view_rep_update(), profile_view_save_name(), sequence_view_rep_update(), and sequence_view_set_name().
kest_button_hide()
int kest_button_hide (kest_button * button)
Definition at line 287 of file kest_button.c.
Referenced by kest_active_button_add_del_button(), kest_active_button_del_button_faded_out_cb(), and kest_active_button_reset_del_button().
kest_button_set_alignment()
int kest_button_set_alignment (kest_button * button, lv_align_t align, int offs_x, int offs_y)
Definition at line 243 of file kest_button.c.
Referenced by kest_active_button_add_del_button(), and kest_active_button_array_append().
kest_button_set_clickable()
int kest_button_set_clickable (kest_button * button)
Definition at line 332 of file kest_button.c.
Referenced by kest_active_button_reset_del_button().
kest_button_set_label()
int kest_button_set_label (kest_button * button, const char * label)
Definition at line 214 of file kest_button.c.
Referenced by configure_main_menu(), kest_active_button_add_del_button(), kest_active_button_change_label(), kest_active_button_reset_del_button(), and kest_active_button_swap_del_button_for_persistent_unclickable().
kest_button_set_opacity()
int kest_button_set_opacity (kest_button * button, int opacity)
Definition at line 360 of file kest_button.c.
Referenced by kest_active_button_del_button_fade_cb(), kest_active_button_delete_anim_cb(), and kest_active_button_swap_del_button_for_persistent_unclickable().
kest_button_set_size()
int kest_button_set_size (kest_button * button, int width, int height)
Definition at line 260 of file kest_button.c.
Referenced by kest_active_button_add_del_button(), kest_active_button_array_append(), and kest_active_button_set_dimensions().
kest_button_set_unclickable()
int kest_button_set_unclickable (kest_button * button)
Definition at line 347 of file kest_button.c.
Referenced by kest_active_button_swap_del_button_for_persistent_unclickable().
kest_button_unhide()
int kest_button_unhide (kest_button * button)
Definition at line 309 of file kest_button.c.
Referenced by kest_active_button_swap_del_button_for_persistent_unclickable(), kest_active_button_trigger_del_button_fade_in(), and kest_active_button_trigger_del_button_fade_out().
kest_danger_button_activate_popup_cb()
void kest_danger_button_activate_popup_cb (lv_event_t * e)
Definition at line 531 of file kest_button.c.
Referenced by init_danger_button().
kest_danger_button_create_ui()
int kest_danger_button_create_ui (kest_danger_button * button, lv_obj_t * parent)
Definition at line 479 of file kest_button.c.
Referenced by create_main_menu_ui().
kest_danger_button_value_changed_cb()
void kest_danger_button_value_changed_cb (lv_event_t * e)
Definition at line 507 of file kest_button.c.
new_button()
kest_button * new_button (const char * label)
Definition at line 54 of file kest_button.c.
Referenced by kest_active_button_add_del_button(), ui_page_add_back_button(), ui_page_add_bottom_button(), ui_page_add_left_panel_button(), ui_page_add_parent_button(), and ui_page_add_right_panel_button().