Kestrel Interface: kest_ui.h File Reference
kest_ui.h File Reference
#include "kest_linked_list.h"
#include "kest_button.h"
Data Structures
struct kest_ui_page_panel
struct kest_ui_page
struct kest_global_pages
Macros
#define DISPLAY_VRES 1024
#define DISPLAY_HRES 600
#define TOP_PANEL_HEIGHT ((int)(0.08 * DISPLAY_VRES))
#define TOP_PANEL_COLOUR 0x313131
#define GLOBAL_MAIN_TEXT_COLOUR 0xFFFFFF
#define GLOBAL_MAIN_FONT &lv_font_montserrat_28
#define GLOBAL_BACKGROUND_COLOUR 0x222222
#define UI_PAGE_TRANSITION_ANIM_MS 175
#define BACK_BUTTON_VSIZE ((int)(0.06 * DISPLAY_VRES))
#define BACK_BUTTON_HSIZE BACK_BUTTON_HSIZE
#define STANDARD_TOP_PANEL_BUTTON_WIDTH (TOP_PANEL_HEIGHT * 0.7)
#define STANDARD_TOP_PANEL_BUTTON_HEIGHT (TOP_PANEL_HEIGHT * 0.7)
#define GLOBAL_PAD_WIDTH ((int)(0.02 * DISPLAY_VRES))
#define H_PAD ((int)(0.067 * DISPLAY_HRES))
#define V_PAD ((int)(0.04 * DISPLAY_VRES))
#define STANDARD_YPOS (-(int)(0.02 * DISPLAY_VRES))
#define STANDARD_CONTAINER_WIDTH ((int)(0.83 * DISPLAY_HRES))
#define STANDARD_CONTAINER_HEIGHT ((int)(0.75 * DISPLAY_VRES))
#define STANDARD_CONTAINER_TALL_HEIGHT ((int)(0.85 * DISPLAY_VRES))
#define TOP_PANEL_FLAG_RW_TITLE 0b1
#define MAX_BOTTOM_BUTTONS 6
#define BOTTOM_BUTTON_PADDING GLOBAL_PAD_WIDTH
#define CONTAINER_TYPE_STD 0
#define CONTAINER_TYPE_STD_BTN_LIST 1
#define CONTAINER_TYPE_STD_MENU 2
#define KEST_UI_PAGE_GENERIC 0
#define KEST_UI_PAGE_MAIN_MENU 1
#define KEST_UI_PAGE_SEQ_LIST 2
#define KEST_UI_PAGE_MSV 3
#define KEST_UI_PAGE_SEQ_VIEW 4
#define KEST_UI_PAGE_PROF_VIEW 5
#define KEST_UI_PAGE_TRANS_VIEW 6
#define KEST_UI_PAGE_TRANS_SET 7
#define PAGE_HISTORY_LEN 64
Typedefs
typedef lv_obj_t_pll lv_obj_ll
Functions
DECLARE_LINKED_PTR_LIST (lv_obj_t)
kest_ui_page_panel * new_panel ()
void kest_create_ui (lv_disp_t *disp)
int init_ui_page (kest_ui_page *page)
int init_ui_page_dp (kest_ui_page **page)
int configure_ui_page (kest_ui_page *page, void *data)
int create_page_ui (kest_ui_page *page)
int enter_ui_page (kest_ui_page *page)
int enter_ui_page_forwards (kest_ui_page *page)
int enter_ui_page_backwards (kest_ui_page *page)
void enter_ui_page_cb (lv_event_t *e)
void enter_ui_page_forwards_cb (lv_event_t *e)
void enter_ui_page_backwards_forwards_cb (lv_event_t *e)
int enter_ui_page_indirect (kest_ui_page **_page)
int enter_ui_page_indirect_forwards (kest_ui_page **_page)
int enter_ui_page_indirect_backwards (kest_ui_page **_page)
void kest_ui_page_return_to_parent (kest_ui_page *page)
int kest_ui_page_set_background_default (kest_ui_page *page)
int kest_ui_page_add_child (kest_ui_page *page, kest_ui_page *child)
int ui_page_create_base_ui (kest_ui_page *page)
int ui_page_create_container (kest_ui_page *page)
int ui_page_create_bottom_buttons (kest_ui_page *page)
int ui_page_add_left_panel_button (kest_ui_page *page, const char *label, lv_event_cb_t cb)
int ui_page_add_right_panel_button (kest_ui_page *page, const char *label, lv_event_cb_t cb)
int ui_page_add_back_button (kest_ui_page *page)
int ui_page_add_parent_button (kest_ui_page *page)
int ui_page_set_title (kest_ui_page *page, const char *text)
int ui_page_update_title (kest_ui_page *page, const char *text)
int ui_page_set_title_rw (kest_ui_page *page, lv_event_cb_t ok_cb, lv_event_cb_t cancel_cb)
kest_button * ui_page_add_bottom_button (kest_ui_page *page, const char *label, lv_event_cb_t cb)
int create_standard_container (lv_obj_t **cont, lv_obj_t *parent)
int create_standard_container_tall (lv_obj_t **cont, lv_obj_t *parent)
int create_standard_menu_container (lv_obj_t **cont, lv_obj_t *parent)
int create_standard_menu_container_tall (lv_obj_t **cont, lv_obj_t *parent)
int create_standard_button_list (lv_obj_t **cont, lv_obj_t *parent)
int create_standard_button_list_tall (lv_obj_t **cont, lv_obj_t *parent)
int create_standard_button_click (lv_obj_t **obj, lv_obj_t **label, lv_obj_t *parent, char *text, lv_event_cb_t click_cb, void *click_cb_arg)
int create_standard_button_click_short (lv_obj_t **obj, lv_obj_t **label, lv_obj_t *parent, char *text, lv_event_cb_t click_cb, void *click_cb_arg)
int create_standard_button_long_press_release (lv_obj_t **obj, lv_obj_t **label, lv_obj_t *parent, char *text, lv_event_cb_t press_cb, void *press_cb_arg, lv_event_cb_t release_cb, void *release_cb_arg)
int create_panel (kest_ui_page *page)
int set_panel_text (kest_ui_page *page, const char *text)
int set_panel_text_rw (kest_ui_page *page, const char *text)
int create_panel_rw_title (kest_ui_page *page, const char *text)
int create_panel_left_button (kest_ui_page *page, const char *button_text, lv_event_cb_t cb, void *cb_arg)
int create_panel_right_button (kest_ui_page *page, const char *button_text, lv_event_cb_t cb, void *cb_arg)
int create_panel_rw_title_and_left_button (kest_ui_page *page, const char *text, const char *left_button_text, lv_event_cb_t left_cb, void *left_cb_arg)
int create_panel_with_back_button (kest_ui_page *page)
int create_panel_with_back_and_settings_buttons (kest_ui_page *page, kest_ui_page *settings_page)
int create_panel_with_back_button_and_right_button (kest_ui_page *page, const char *right_button_text, lv_event_cb_t right_cb, void *cb_arg)
int create_panel_with_left_button (kest_ui_page *page, const char *left_button_text, lv_event_cb_t left_cb, void *cb_arg)
int create_panel_with_right_button (kest_ui_page *page, const char *right_button_text, lv_event_cb_t right_cb, void *cb_arg)
int create_panel_with_back_button_and_page_button (kest_ui_page *page, const char *right_button_text, kest_ui_page *right_button_page)
int create_panel_with_left_and_right_buttons (kest_ui_page *page, const char *left_button_text, lv_event_cb_t left_cb, void *left_cb_arg, const char *right_button_text, lv_event_cb_t right_cb, void *right_cb_arg)
void spawn_keyboard (lv_obj_t *parent, lv_obj_t *text_area, void(*ok_cb)(lv_event_t *), void *ok_arg, void(*cancel_cb)(lv_event_t *), void *cancel_arg)
void spawn_numerical_keyboard (lv_obj_t *parent, lv_obj_t *text_area, void(*ok_cb)(lv_event_t *), void *ok_arg, void(*cancel_cb)(lv_event_t *), void *cancel_arg)
void hide_keyboard_cb (lv_event_t *e)
void hide_keyboard ()
int kest_init_global_pages (kest_global_pages *pages)
void enter_parent_page_cb (lv_event_t *e)
Variables
lv_obj_t * keyboard
Macro Definition Documentation
BACK_BUTTON_HSIZE
#define BACK_BUTTON_HSIZE BACK_BUTTON_HSIZE
Definition at line 26 of file kest_ui.h.
BACK_BUTTON_VSIZE
#define BACK_BUTTON_VSIZE ((int)(0.06 * DISPLAY_VRES))
Definition at line 25 of file kest_ui.h.
BOTTOM_BUTTON_PADDING
#define BOTTOM_BUTTON_PADDING GLOBAL_PAD_WIDTH
Definition at line 69 of file kest_ui.h.
Referenced by ui_page_create_bottom_buttons().
CONTAINER_TYPE_STD
#define CONTAINER_TYPE_STD 0
Definition at line 71 of file kest_ui.h.
Referenced by init_ui_page(), and ui_page_create_container().
CONTAINER_TYPE_STD_BTN_LIST
#define CONTAINER_TYPE_STD_BTN_LIST 1
Definition at line 72 of file kest_ui.h.
Referenced by configure_main_menu(), configure_menu_page(), configure_sequence_list(), and ui_page_create_container().
CONTAINER_TYPE_STD_MENU
#define CONTAINER_TYPE_STD_MENU 2
Definition at line 73 of file kest_ui.h.
Referenced by ui_page_create_container().
DISPLAY_HRES
#define DISPLAY_HRES 600
Definition at line 12 of file kest_ui.h.
Referenced by main_task().
DISPLAY_VRES
#define DISPLAY_VRES 1024
Definition at line 11 of file kest_ui.h.
Referenced by main_task().
GLOBAL_BACKGROUND_COLOUR
#define GLOBAL_BACKGROUND_COLOUR 0x222222
Definition at line 21 of file kest_ui.h.
Referenced by kest_ui_page_set_background_default().
GLOBAL_MAIN_FONT
#define GLOBAL_MAIN_FONT &lv_font_montserrat_28
Definition at line 19 of file kest_ui.h.
Referenced by set_panel_text(), and set_panel_text_rw().
GLOBAL_MAIN_TEXT_COLOUR
#define GLOBAL_MAIN_TEXT_COLOUR 0xFFFFFF
Definition at line 18 of file kest_ui.h.
Referenced by set_panel_text(), and set_panel_text_rw().
GLOBAL_PAD_WIDTH
#define GLOBAL_PAD_WIDTH ((int)(0.02 * DISPLAY_VRES))
Definition at line 31 of file kest_ui.h.
Referenced by create_panel(), kest_danger_button_activate_popup_cb(), and ui_page_create_panel_ui().
H_PAD
#define H_PAD ((int)(0.067 * DISPLAY_HRES))
Definition at line 33 of file kest_ui.h.
KEST_UI_PAGE_GENERIC
#define KEST_UI_PAGE_GENERIC 0
Definition at line 75 of file kest_ui.h.
Referenced by init_ui_page().
KEST_UI_PAGE_MAIN_MENU
#define KEST_UI_PAGE_MAIN_MENU 1
Definition at line 76 of file kest_ui.h.
Referenced by init_main_menu(), kest_page_id_find_page(), and kest_ui_page_create_identifier().
KEST_UI_PAGE_MSV
#define KEST_UI_PAGE_MSV 3
Definition at line 78 of file kest_ui.h.
Referenced by kest_init_global_pages(), kest_page_id_find_page(), and kest_ui_page_create_identifier().
KEST_UI_PAGE_PROF_VIEW
#define KEST_UI_PAGE_PROF_VIEW 5
Definition at line 80 of file kest_ui.h.
Referenced by init_profile_view(), kest_page_id_find_page(), and kest_ui_page_create_identifier().
KEST_UI_PAGE_SEQ_LIST
#define KEST_UI_PAGE_SEQ_LIST 2
Definition at line 77 of file kest_ui.h.
Referenced by kest_init_global_pages(), kest_page_id_find_page(), and kest_ui_page_create_identifier().
KEST_UI_PAGE_SEQ_VIEW
#define KEST_UI_PAGE_SEQ_VIEW 4
Definition at line 79 of file kest_ui.h.
Referenced by init_sequence_view(), kest_page_id_find_page(), and kest_ui_page_create_identifier().
KEST_UI_PAGE_TRANS_SET
#define KEST_UI_PAGE_TRANS_SET 7
Definition at line 82 of file kest_ui.h.
Referenced by init_effect_settings_page(), kest_page_id_find_page(), and kest_ui_page_create_identifier().
KEST_UI_PAGE_TRANS_VIEW
#define KEST_UI_PAGE_TRANS_VIEW 6
Definition at line 81 of file kest_ui.h.
Referenced by init_effect_view(), kest_page_id_find_page(), and kest_ui_page_create_identifier().
MAX_BOTTOM_BUTTONS
#define MAX_BOTTOM_BUTTONS 6
Definition at line 68 of file kest_ui.h.
Referenced by init_ui_page(), ui_page_add_bottom_button(), ui_page_create_bottom_buttons(), and ui_page_create_container().
PAGE_HISTORY_LEN
#define PAGE_HISTORY_LEN 64
Definition at line 191 of file kest_ui.h.
STANDARD_CONTAINER_HEIGHT
#define STANDARD_CONTAINER_HEIGHT ((int)(0.75 * DISPLAY_VRES))
Definition at line 39 of file kest_ui.h.
Referenced by create_standard_button_list(), create_standard_button_list_tall(), create_standard_container(), create_standard_container_tall(), create_standard_menu_container(), and create_standard_menu_container_tall().
STANDARD_CONTAINER_TALL_HEIGHT
#define STANDARD_CONTAINER_TALL_HEIGHT ((int)(0.85 * DISPLAY_VRES))
Definition at line 40 of file kest_ui.h.
Referenced by create_standard_button_list_tall(), create_standard_container_tall(), and create_standard_menu_container_tall().
STANDARD_CONTAINER_WIDTH
#define STANDARD_CONTAINER_WIDTH ((int)(0.83 * DISPLAY_HRES))
Definition at line 38 of file kest_ui.h.
Referenced by create_effect_view_ui(), create_standard_button_list(), create_standard_button_list_tall(), create_standard_container(), create_standard_container_tall(), create_standard_menu_container(), create_standard_menu_container_tall(), setting_widget_create_ui_no_callback(), and ui_page_create_bottom_buttons().
STANDARD_TOP_PANEL_BUTTON_HEIGHT
#define STANDARD_TOP_PANEL_BUTTON_HEIGHT (TOP_PANEL_HEIGHT * 0.7)
Definition at line 29 of file kest_ui.h.
Referenced by create_panel_left_button(), create_panel_right_button(), ui_page_add_back_button(), ui_page_add_left_panel_button(), ui_page_add_parent_button(), and ui_page_add_right_panel_button().
STANDARD_TOP_PANEL_BUTTON_WIDTH
#define STANDARD_TOP_PANEL_BUTTON_WIDTH (TOP_PANEL_HEIGHT * 0.7)
Definition at line 28 of file kest_ui.h.
Referenced by create_panel_left_button(), create_panel_right_button(), ui_page_add_back_button(), ui_page_add_left_panel_button(), ui_page_add_parent_button(), and ui_page_add_right_panel_button().
STANDARD_YPOS
#define STANDARD_YPOS (-(int)(0.02 * DISPLAY_VRES))
Definition at line 36 of file kest_ui.h.
Referenced by create_standard_button_list(), create_standard_button_list_tall(), create_standard_container(), create_standard_container_tall(), create_standard_menu_container(), and create_standard_menu_container_tall().
TOP_PANEL_COLOUR
#define TOP_PANEL_COLOUR 0x313131
Definition at line 16 of file kest_ui.h.
Referenced by create_panel(), set_panel_text_rw(), ui_page_create_panel_ui(), and ui_page_init_create_panel_label().
TOP_PANEL_FLAG_RW_TITLE
#define TOP_PANEL_FLAG_RW_TITLE 0b1
Definition at line 44 of file kest_ui.h.
Referenced by ui_page_init_create_panel_label(), ui_page_set_title(), and ui_page_set_title_rw().
TOP_PANEL_HEIGHT
#define TOP_PANEL_HEIGHT ((int)(0.08 * DISPLAY_VRES))
Definition at line 15 of file kest_ui.h.
Referenced by create_panel(), set_panel_text_rw(), and ui_page_create_panel_ui().
UI_PAGE_TRANSITION_ANIM_MS
#define UI_PAGE_TRANSITION_ANIM_MS 175
Definition at line 23 of file kest_ui.h.
Referenced by enter_ui_page_backwards(), and enter_ui_page_forwards().
V_PAD
#define V_PAD ((int)(0.04 * DISPLAY_VRES))
Definition at line 34 of file kest_ui.h.
Typedef Documentation
lv_obj_ll
typedef lv_obj_t_pll lv_obj_ll
Definition at line 208 of file kest_ui.h.
Function Documentation
configure_ui_page()
int configure_ui_page (kest_ui_page * page, void * data)
Definition at line 197 of file kest_ui.c.
Referenced by configure_menu_item(), and kest_create_ui().
create_page_ui()
int create_page_ui (kest_ui_page * page)
Definition at line 226 of file kest_ui.c.
create_panel()
int create_panel (kest_ui_page * page)
Definition at line 514 of file kest_ui.c.
Referenced by create_panel_rw_title(), create_panel_rw_title_and_left_button(), create_panel_with_left_and_right_buttons(), and create_panel_with_left_button().
create_panel_left_button()
int create_panel_left_button (kest_ui_page * page, const char * button_text, lv_event_cb_t cb, void * cb_arg)
Definition at line 612 of file kest_ui.c.
Referenced by create_panel_rw_title_and_left_button(), create_panel_with_left_and_right_buttons(), and create_panel_with_left_button().
create_panel_right_button()
int create_panel_right_button (kest_ui_page * page, const char * button_text, lv_event_cb_t cb, void * cb_arg)
Definition at line 634 of file kest_ui.c.
Referenced by create_panel_with_back_button_and_page_button(), create_panel_with_left_and_right_buttons(), and create_panel_with_right_button().
create_panel_rw_title()
int create_panel_rw_title (kest_ui_page * page, const char * text)
Definition at line 600 of file kest_ui.c.
create_panel_rw_title_and_left_button()
int create_panel_rw_title_and_left_button (kest_ui_page * page, const char * text, const char * left_button_text, lv_event_cb_t left_cb, void * left_cb_arg)
Definition at line 656 of file kest_ui.c.
create_panel_with_back_and_settings_buttons()
int create_panel_with_back_and_settings_buttons (kest_ui_page * page, kest_ui_page * settings_page)
Definition at line 675 of file kest_ui.c.
create_panel_with_back_button()
int create_panel_with_back_button (kest_ui_page * page)
Definition at line 670 of file kest_ui.c.
Referenced by create_effect_selector_ui_eff(), create_panel_with_back_button_and_page_button(), and create_panel_with_right_button().
create_panel_with_back_button_and_page_button()
int create_panel_with_back_button_and_page_button (kest_ui_page * page, const char * right_button_text, kest_ui_page * right_button_page)
Definition at line 709 of file kest_ui.c.
Referenced by create_panel_with_back_and_settings_buttons().
create_panel_with_back_button_and_right_button()
int create_panel_with_back_button_and_right_button (kest_ui_page * page, const char * right_button_text, lv_event_cb_t right_cb, void * cb_arg)
Definition at line 680 of file kest_ui.c.
create_panel_with_left_and_right_buttons()
int create_panel_with_left_and_right_buttons (kest_ui_page * page, const char * left_button_text, lv_event_cb_t left_cb, void * left_cb_arg, const char * right_button_text, lv_event_cb_t right_cb, void * right_cb_arg)
Definition at line 721 of file kest_ui.c.
Referenced by create_panel_with_back_button_and_right_button().
create_panel_with_left_button()
int create_panel_with_left_button (kest_ui_page * page, const char * left_button_text, lv_event_cb_t left_cb, void * cb_arg)
Definition at line 685 of file kest_ui.c.
Referenced by create_panel_with_back_button().
create_panel_with_right_button()
int create_panel_with_right_button (kest_ui_page * page, const char * right_button_text, lv_event_cb_t right_cb, void * cb_arg)
Definition at line 697 of file kest_ui.c.
create_standard_button_click()
int create_standard_button_click (lv_obj_t ** obj, lv_obj_t ** label, lv_obj_t * parent, char * text, lv_event_cb_t click_cb, void * click_cb_arg)
Definition at line 907 of file kest_ui.c.
Referenced by create_menu_item_ui().
create_standard_button_click_short()
int create_standard_button_click_short (lv_obj_t ** obj, lv_obj_t ** label, lv_obj_t * parent, char * text, lv_event_cb_t click_cb, void * click_cb_arg)
Definition at line 928 of file kest_ui.c.
Referenced by create_effect_selector_button_ui_eff().
create_standard_button_list()
int create_standard_button_list (lv_obj_t ** cont, lv_obj_t * parent)
Definition at line 866 of file kest_ui.c.
Referenced by ui_page_create_container().
create_standard_button_list_tall()
int create_standard_button_list_tall (lv_obj_t ** cont, lv_obj_t * parent)
Definition at line 886 of file kest_ui.c.
Referenced by create_effect_selector_ui_eff(), and ui_page_create_container().
create_standard_button_long_press_release()
int create_standard_button_long_press_release (lv_obj_t ** obj, lv_obj_t ** label, lv_obj_t * parent, char * text, lv_event_cb_t press_cb, void * press_cb_arg, lv_event_cb_t release_cb, void * release_cb_arg)
Definition at line 949 of file kest_ui.c.
Referenced by create_menu_item_ui().
create_standard_container()
int create_standard_container (lv_obj_t ** cont, lv_obj_t * parent)
Definition at line 785 of file kest_ui.c.
Referenced by ui_page_create_container().
create_standard_container_tall()
int create_standard_container_tall (lv_obj_t ** cont, lv_obj_t * parent)
Definition at line 802 of file kest_ui.c.
Referenced by ui_page_create_container().
create_standard_menu_container()
int create_standard_menu_container (lv_obj_t ** cont, lv_obj_t * parent)
Definition at line 820 of file kest_ui.c.
Referenced by ui_page_create_container().
create_standard_menu_container_tall()
int create_standard_menu_container_tall (lv_obj_t ** cont, lv_obj_t * parent)
Definition at line 841 of file kest_ui.c.
Referenced by ui_page_create_container().
DECLARE_LINKED_PTR_LIST()
DECLARE_LINKED_PTR_LIST (lv_obj_t)
enter_parent_page_cb()
void enter_parent_page_cb (lv_event_t * e)
Definition at line 468 of file kest_ui.c.
Referenced by create_panel_with_back_button(), create_panel_with_back_button_and_right_button(), ui_page_add_back_button(), and ui_page_add_parent_button().
enter_ui_page()
int enter_ui_page (kest_ui_page * page)
Definition at line 244 of file kest_ui.c.
Referenced by enter_main_menu_cb(), enter_ui_page_cb(), enter_ui_page_indirect(), kest_create_ui(), and kest_cxt_enter_previous_current_page().
enter_ui_page_backwards()
int enter_ui_page_backwards (kest_ui_page * page)
Definition at line 354 of file kest_ui.c.
Referenced by add_effect_from_menu_eff(), enter_parent_page_cb(), enter_ui_page_backwardindirect_s(), enter_ui_page_backwards_cb(), kest_ui_page_return_to_parent(), and profile_view_enter_main_menu_cb().
enter_ui_page_backwards_forwards_cb()
void enter_ui_page_backwards_forwards_cb (lv_event_t * e)
enter_ui_page_cb()
void enter_ui_page_cb (lv_event_t * e)
Definition at line 441 of file kest_ui.c.
enter_ui_page_forwards()
int enter_ui_page_forwards (kest_ui_page * page)
Definition at line 299 of file kest_ui.c.
Referenced by effect_view_enter_settings_cb(), enter_effect_selector_cb(), enter_ui_page_forwards_cb(), enter_ui_page_indirect_forwards(), menu_item_profile_listing_released_cb(), menu_item_sequence_listing_released_cb(), menu_page_link_clicked_cb(), profile_view_effect_click_cb(), profile_view_enter_settings_page_cb(), seq_view_clicked_cb(), and sequence_list_add_cb().
enter_ui_page_forwards_cb()
void enter_ui_page_forwards_cb (lv_event_t * e)
Definition at line 450 of file kest_ui.c.
Referenced by configure_main_menu(), and create_panel_with_back_button_and_page_button().
enter_ui_page_indirect()
int enter_ui_page_indirect (kest_ui_page ** _page)
Definition at line 411 of file kest_ui.c.
enter_ui_page_indirect_backwards()
int enter_ui_page_indirect_backwards (kest_ui_page ** _page)
enter_ui_page_indirect_forwards()
int enter_ui_page_indirect_forwards (kest_ui_page ** _page)
Definition at line 421 of file kest_ui.c.
Referenced by menu_page_link_clicked_cb().
hide_keyboard()
void hide_keyboard ()
Definition at line 769 of file kest_ui.c.
Referenced by profile_view_revert_name(), profile_view_save_name(), sequence_view_revert_name(), sequence_view_set_name(), sw_field_cancel_cb(), and sw_field_save_cb().
hide_keyboard_cb()
void hide_keyboard_cb (lv_event_t * e)
Definition at line 777 of file kest_ui.c.
init_ui_page()
int init_ui_page (kest_ui_page * page)
Definition at line 152 of file kest_ui.c.
Referenced by create_effect_view_for(), create_profile_view_for(), create_ui_page(), init_effect_selector_eff(), init_effect_settings_page(), init_effect_view(), init_main_menu(), init_menu_page(), init_profile_settings_page(), init_profile_view(), init_sequence_view(), and init_test_page().
init_ui_page_dp()
int init_ui_page_dp (kest_ui_page ** page)
kest_create_ui()
void kest_create_ui (lv_disp_t * disp)
Definition at line 121 of file kest_ui.c.
Referenced by app_main(), and main_task().
kest_init_global_pages()
int kest_init_global_pages (kest_global_pages * pages)
Definition at line 78 of file kest_ui.c.
Referenced by app_main(), and main_task().
kest_ui_page_add_child()
int kest_ui_page_add_child (kest_ui_page * page, kest_ui_page * child)
kest_ui_page_return_to_parent()
void kest_ui_page_return_to_parent (kest_ui_page * page)
Definition at line 485 of file kest_ui.c.
kest_ui_page_set_background_default()
int kest_ui_page_set_background_default (kest_ui_page * page)
Definition at line 64 of file kest_ui.c.
new_panel()
kest_ui_page_panel * new_panel ()
Definition at line 991 of file kest_ui.c.
Referenced by configure_main_menu(), configure_menu_page(), configure_sequence_list(), configure_sequence_view(), init_effect_settings_page(), init_effect_view(), init_profile_settings_page(), init_profile_view(), and init_test_page().
set_panel_text()
int set_panel_text (kest_ui_page * page, const char * text)
Definition at line 541 of file kest_ui.c.
Referenced by create_effect_selector_ui_eff().
set_panel_text_rw()
int set_panel_text_rw (kest_ui_page * page, const char * text)
Definition at line 573 of file kest_ui.c.
Referenced by create_panel_rw_title(), and create_panel_rw_title_and_left_button().
spawn_keyboard()
void spawn_keyboard (lv_obj_t * parent, lv_obj_t * text_area, void(* ok_cb)(lv_event_t *), void * ok_arg, void(* cancel_cb)(lv_event_t *), void * cancel_arg)
Definition at line 737 of file kest_ui.c.
Referenced by spawn_numerical_keyboard().
spawn_numerical_keyboard()
void spawn_numerical_keyboard (lv_obj_t * parent, lv_obj_t * text_area, void(* ok_cb)(lv_event_t *), void * ok_arg, void(* cancel_cb)(lv_event_t *), void * cancel_arg)
Definition at line 759 of file kest_ui.c.
Referenced by edit_sw_field_cb().
ui_page_add_back_button()
int ui_page_add_back_button (kest_ui_page * page)
Definition at line 1129 of file kest_ui.c.
Referenced by configure_effect_settings_page(), configure_menu_page(), configure_profile_settings_page(), configure_sequence_list(), and configure_sequence_view().
ui_page_add_bottom_button()
kest_button * ui_page_add_bottom_button (kest_ui_page * page, const char * label, lv_event_cb_t cb)
Definition at line 1308 of file kest_ui.c.
Referenced by configure_profile_view(), configure_sequence_list(), configure_sequence_view(), and init_test_page().
ui_page_add_left_panel_button()
int ui_page_add_left_panel_button (kest_ui_page * page, const char * label, lv_event_cb_t cb)
Definition at line 1171 of file kest_ui.c.
Referenced by configure_profile_view().
ui_page_add_parent_button()
int ui_page_add_parent_button (kest_ui_page * page)
Definition at line 1150 of file kest_ui.c.
Referenced by configure_effect_view().
ui_page_add_right_panel_button()
int ui_page_add_right_panel_button (kest_ui_page * page, const char * label, lv_event_cb_t cb)
Definition at line 1189 of file kest_ui.c.
Referenced by configure_effect_view(), and configure_profile_view().
ui_page_create_base_ui()
int ui_page_create_base_ui (kest_ui_page * page)
Definition at line 1207 of file kest_ui.c.
Referenced by create_effect_settings_page_ui(), create_effect_view_ui(), create_main_menu_ui(), create_menu_page_ui(), create_profile_settings_page_ui(), create_profile_view_ui(), create_sequence_view_ui(), and create_test_page_ui().
ui_page_create_bottom_buttons()
int ui_page_create_bottom_buttons (kest_ui_page * page)
Definition at line 1271 of file kest_ui.c.
Referenced by ui_page_create_base_ui().
ui_page_create_container()
int ui_page_create_container (kest_ui_page * page)
Definition at line 1230 of file kest_ui.c.
Referenced by ui_page_create_base_ui().
ui_page_set_title()
int ui_page_set_title (kest_ui_page * page, const char * text)
Definition at line 1066 of file kest_ui.c.
Referenced by profile_view_rep_update(), sequence_view_rep_update(), and ui_page_update_title().
ui_page_set_title_rw()
int ui_page_set_title_rw (kest_ui_page * page, lv_event_cb_t ok_cb, lv_event_cb_t cancel_cb)
Definition at line 1335 of file kest_ui.c.
Referenced by configure_profile_view(), and configure_sequence_view().
ui_page_update_title()
int ui_page_update_title (kest_ui_page * page, const char * text)
Definition at line 1014 of file kest_ui.c.
Variable Documentation
keyboard
lv_obj_t* keyboard extern
Definition at line 20 of file kest_ui.c.
Referenced by hide_keyboard(), hide_keyboard_cb(), spawn_keyboard(), and spawn_numerical_keyboard().