Kestrel Interface: kest_eff_section.c File Reference
kest_eff_section.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 1
Functions
int token_is_valid_section_name (char *str)
int get_section_start_score (char *str, int current_score)
int kest_parameters_section_extract (kest_eff_parsing_state *ps, kest_parameter_pll **list, kest_ast_node *sect)
int kest_settings_section_extract (kest_eff_parsing_state *ps, kest_setting_pll **list, kest_ast_node *sect)
int kest_resources_section_extract (kest_eff_parsing_state *ps, kest_dsp_resource_pll **list, kest_ast_node *sect)
int kest_defs_section_extract (kest_eff_parsing_state *ps, kest_expr_scope *scope, struct kest_ast_node *sect)
int kest_dictionary_section_lookup_str (kest_ast_node *section, const char *name, const char **result)
int kest_dictionary_section_lookup_float (kest_ast_node *section, const char *name, float *result)
int kest_dictionary_section_lookup_int (kest_ast_node *section, const char *name, int *result)
int kest_dictionary_section_lookup_expr (kest_ast_node *section, const char *name, kest_expression **result)
int kest_dictionary_section_lookup_dict (kest_ast_node *section, const char *name, kest_dictionary **result)
int kest_parse_dictionary_section (kest_eff_parsing_state *ps, kest_ast_node *section)
int kest_parse_code_section (kest_eff_parsing_state *ps, kest_ast_node *section)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 1
Definition at line 4 of file kest_eff_section.c.
Function Documentation
get_section_start_score()
int get_section_start_score (char * str, int current_score)
Definition at line 24 of file kest_eff_section.c.
Referenced by kest_parse_tokens().
kest_defs_section_extract()
int kest_defs_section_extract (kest_eff_parsing_state * ps, kest_expr_scope * scope, struct kest_ast_node * sect)
Definition at line 137 of file kest_eff_section.c.
Referenced by kest_parse_tokens().
kest_dictionary_section_lookup_dict()
int kest_dictionary_section_lookup_dict (kest_ast_node * section, const char * name, kest_dictionary ** result)
Definition at line 237 of file kest_eff_section.c.
kest_dictionary_section_lookup_expr()
int kest_dictionary_section_lookup_expr (kest_ast_node * section, const char * name, kest_expression ** result)
Definition at line 225 of file kest_eff_section.c.
kest_dictionary_section_lookup_float()
int kest_dictionary_section_lookup_float (kest_ast_node * section, const char * name, float * result)
Definition at line 201 of file kest_eff_section.c.
kest_dictionary_section_lookup_int()
int kest_dictionary_section_lookup_int (kest_ast_node * section, const char * name, int * result)
Definition at line 213 of file kest_eff_section.c.
kest_dictionary_section_lookup_str()
int kest_dictionary_section_lookup_str (kest_ast_node * section, const char * name, const char ** result)
Definition at line 189 of file kest_eff_section.c.
Referenced by kest_parse_tokens().
kest_parameters_section_extract()
int kest_parameters_section_extract (kest_eff_parsing_state * ps, kest_parameter_pll ** list, kest_ast_node * sect)
Definition at line 41 of file kest_eff_section.c.
Referenced by kest_parse_tokens().
kest_parse_code_section()
int kest_parse_code_section (kest_eff_parsing_state * ps, kest_ast_node * section)
Definition at line 276 of file kest_eff_section.c.
Referenced by kest_parse_tokens().
kest_parse_dictionary_section()
int kest_parse_dictionary_section (kest_eff_parsing_state * ps, kest_ast_node * section)
Definition at line 249 of file kest_eff_section.c.
Referenced by kest_parse_tokens().
kest_resources_section_extract()
int kest_resources_section_extract (kest_eff_parsing_state * ps, kest_dsp_resource_pll ** list, kest_ast_node * sect)
Definition at line 102 of file kest_eff_section.c.
Referenced by kest_parse_tokens().
kest_settings_section_extract()
int kest_settings_section_extract (kest_eff_parsing_state * ps, kest_setting_pll ** list, kest_ast_node * sect)
Definition at line 70 of file kest_eff_section.c.
Referenced by kest_parse_tokens().
token_is_valid_section_name()
int token_is_valid_section_name (char * str)
Definition at line 9 of file kest_eff_section.c.
Referenced by get_section_start_score().