Kestrel Interface: kest_transformer.h File Reference
kest_transformer.h File Reference
Data Structures
struct kest_effect
Macros
#define TRANSFORMER_MODE_FULL_SPECTRUM 0
#define TRANSFORMER_MODE_UPPER_SPECTRUM 1
#define TRANSFORMER_MODE_LOWER_SPECTRUM 2
#define TRANSFORMER_MODE_BAND 3
#define TRANSFORMER_WET_MIX_PID 0xFFFF
#define TRANSFORMER_BAND_LP_CUTOFF_PID 0xFFFE
#define TRANSFORMER_BAND_HP_CUTOFF_PID 0xFFFD
#define TRANSFORMER_BAND_MODE_SID 0xFFFF
Functions
const char * kest_effect_name (kest_effect *effect)
DECLARE_LINKED_PTR_LIST (kest_effect)
int init_effect (kest_effect *effect)
int effect_set_id (kest_effect *effect, uint16_t profile_id, uint16_t effect_id)
int effect_rectify_param_ids (kest_effect *effect)
kest_parameter * effect_add_parameter (kest_effect *effect)
kest_setting * effect_add_setting (kest_effect *effect)
int init_default_effect_by_type (kest_effect *effect, uint16_t type, uint16_t profile_id, uint16_t effect_id)
int init_effect_from_effect_desc (kest_effect *effect, kest_effect_desc *eff)
int request_append_effect (uint16_t type, kest_effect *local)
int clone_effect (kest_effect *dest, kest_effect *src)
void free_effect (kest_effect *effect)
kest_parameter * effect_get_parameter (kest_effect *effect, int n)
kest_setting * effect_get_setting (kest_effect *effect, int n)
int kest_fpga_transfer_batch_append_effect (kest_effect *effect, const kest_eff_resource_report *cxt, kest_eff_resource_report *report, kest_fpga_transfer_batch *batch)
int kest_effect_update_fpga_registers (kest_effect *effect)
kest_expr_scope * kest_effect_create_scope (kest_effect *effect)
int kest_effect_set_parameter (kest_effect *effect, const char *name, float value)
int kest_effect_set_setting (kest_effect *effect, const char *name, int value)
int kest_effect_update_reps (kest_effect *effect)
void kest_effect_profile_rep_update (void *representer, void *representee)
int kest_effect_init_view_page (kest_effect *effect, struct kest_ui_page *parent)
Macro Definition Documentation
TRANSFORMER_BAND_HP_CUTOFF_PID
#define TRANSFORMER_BAND_HP_CUTOFF_PID 0xFFFD
Definition at line 12 of file kest_transformer.h.
TRANSFORMER_BAND_LP_CUTOFF_PID
#define TRANSFORMER_BAND_LP_CUTOFF_PID 0xFFFE
Definition at line 11 of file kest_transformer.h.
TRANSFORMER_BAND_MODE_SID
#define TRANSFORMER_BAND_MODE_SID 0xFFFF
Definition at line 13 of file kest_transformer.h.
TRANSFORMER_MODE_BAND
#define TRANSFORMER_MODE_BAND 3
Definition at line 7 of file kest_transformer.h.
TRANSFORMER_MODE_FULL_SPECTRUM
#define TRANSFORMER_MODE_FULL_SPECTRUM 0
Definition at line 4 of file kest_transformer.h.
TRANSFORMER_MODE_LOWER_SPECTRUM
#define TRANSFORMER_MODE_LOWER_SPECTRUM 2
Definition at line 6 of file kest_transformer.h.
TRANSFORMER_MODE_UPPER_SPECTRUM
#define TRANSFORMER_MODE_UPPER_SPECTRUM 1
Definition at line 5 of file kest_transformer.h.
TRANSFORMER_WET_MIX_PID
#define TRANSFORMER_WET_MIX_PID 0xFFFF
Definition at line 9 of file kest_transformer.h.
Function Documentation
clone_effect()
int clone_effect (kest_effect * dest, kest_effect * src)
Definition at line 345 of file kest_effect.c.
Referenced by clone_pipeline().
DECLARE_LINKED_PTR_LIST()
DECLARE_LINKED_PTR_LIST (kest_effect)
effect_add_parameter()
kest_parameter * effect_add_parameter (kest_effect * effect)
Definition at line 237 of file kest_effect.c.
Referenced by clone_effect(), init_3_band_eq(), init_amplifier(), init_band_pass_filter(), init_compressor(), init_delay(), init_dirty_octave(), init_distortion(), init_envelope(), init_flanger(), init_high_pass_filter(), init_low_end_compressor(), init_low_pass_filter(), init_noise_suppressor(), init_percussifier(), and init_warbler().
effect_add_setting()
kest_setting * effect_add_setting (kest_effect * effect)
Definition at line 264 of file kest_effect.c.
Referenced by clone_effect(), init_amplifier(), init_delay(), init_distortion(), and init_flanger().
effect_get_parameter()
kest_parameter * effect_get_parameter (kest_effect * effect, int n)
Definition at line 448 of file kest_effect.c.
Referenced by cxt_get_parameter_and_effect_by_id(), and cxt_get_parameter_by_id().
effect_get_setting()
kest_setting * effect_get_setting (kest_effect * effect, int n)
Definition at line 466 of file kest_effect.c.
Referenced by cxt_get_setting_by_id().
effect_rectify_param_ids()
int effect_rectify_param_ids (kest_effect * effect)
Definition at line 130 of file kest_effect.c.
Referenced by effect_set_id(), and kest_profile_append_effect_eff().
effect_set_id()
int effect_set_id (kest_effect * effect, uint16_t profile_id, uint16_t effect_id)
Definition at line 178 of file kest_effect.c.
free_effect()
void free_effect (kest_effect * effect)
Definition at line 433 of file kest_effect.c.
Referenced by gut_pipeline(), and kest_pipeline_remove_effect().
init_default_effect_by_type()
int init_default_effect_by_type (kest_effect * effect, uint16_t type, uint16_t profile_id, uint16_t effect_id)
init_effect()
int init_effect (kest_effect * effect)
Definition at line 29 of file kest_effect.c.
Referenced by clone_effect(), init_effect_from_effect_desc(), and init_effect_of_type().
init_effect_from_effect_desc()
int init_effect_from_effect_desc (kest_effect * effect, kest_effect_desc * eff)
Definition at line 103 of file kest_effect.c.
Referenced by kest_pipeline_append_effect_eff().
kest_effect_create_scope()
kest_expr_scope * kest_effect_create_scope (kest_effect * effect)
Definition at line 509 of file kest_effect.c.
Referenced by init_effect_from_effect_desc().
kest_effect_init_view_page()
int kest_effect_init_view_page (kest_effect * effect, struct kest_ui_page * parent)
kest_effect_name()
const char * kest_effect_name (kest_effect * effect)
Definition at line 17 of file kest_effect.c.
Referenced by configure_effect_settings_page(), configure_effect_view(), configure_profile_view(), context_print_profiles(), create_effect_view_ui(), and profile_view_append_effect().
kest_effect_profile_rep_update()
void kest_effect_profile_rep_update (void * representer, void * representee)
Definition at line 598 of file kest_effect.c.
Referenced by init_effect().
kest_effect_set_parameter()
int kest_effect_set_parameter (kest_effect * effect, const char * name, float value)
Definition at line 551 of file kest_effect.c.
kest_effect_set_setting()
int kest_effect_set_setting (kest_effect * effect, const char * name, int value)
Definition at line 574 of file kest_effect.c.
kest_effect_update_fpga_registers()
int kest_effect_update_fpga_registers (kest_effect * effect)
Definition at line 483 of file kest_effect.c.
kest_effect_update_reps()
int kest_effect_update_reps (kest_effect * effect)
Definition at line 613 of file kest_effect.c.
Referenced by kest_parameter_effect_rep_update(), and kest_setting_effect_rep_update().
kest_fpga_transfer_batch_append_effect()
int kest_fpga_transfer_batch_append_effect (kest_effect * effect, const kest_eff_resource_report * cxt, kest_eff_resource_report * report, kest_fpga_transfer_batch * batch)
request_append_effect()
int request_append_effect (uint16_t type, kest_effect * local)
Definition at line 190 of file kest_effect.c.