Kestrel Interface: kest_bump_arena.h File Reference
kest_bump_arena.h File Reference
Data Structures
struct kest_bump_arena
Macros
#define KEST_BUMP_ARENA_ALLOC_ALIGN 4
#define KEST_BUMP_ARENA_INIT_ALIGN 64
Functions
int kest_bump_arena_init_empty (kest_bump_arena *arena)
int kest_bump_arena_init (kest_bump_arena *arena, size_t capacity)
void * kest_bump_arena_alloc (kest_bump_arena *arena, size_t size)
void * kest_bump_arena_realloc (kest_bump_arena *arena, void *p, size_t size)
void kest_bump_arena_free (kest_bump_arena *arena)
int kest_bump_arena_reset (kest_bump_arena *arena)
int kest_bump_arena_destroy (kest_bump_arena *arena)
Macro Definition Documentation
KEST_BUMP_ARENA_ALLOC_ALIGN
#define KEST_BUMP_ARENA_ALLOC_ALIGN 4
Definition at line 4 of file kest_bump_arena.h.
Referenced by kest_bump_arena_alloc().
KEST_BUMP_ARENA_INIT_ALIGN
#define KEST_BUMP_ARENA_INIT_ALIGN 64
Definition at line 5 of file kest_bump_arena.h.
Referenced by kest_bump_arena_init().
Function Documentation
kest_bump_arena_alloc()
void * kest_bump_arena_alloc (kest_bump_arena * arena, size_t size)
Definition at line 69 of file kest_bump_arena.c.
Referenced by kest_bump_arena_realloc(), and kest_parser_alloc().
kest_bump_arena_destroy()
int kest_bump_arena_destroy (kest_bump_arena * arena)
Definition at line 130 of file kest_bump_arena.c.
Referenced by kest_eff_parser_deinit_mempool().
kest_bump_arena_free()
void kest_bump_arena_free (kest_bump_arena * arena)
kest_bump_arena_init()
int kest_bump_arena_init (kest_bump_arena * arena, size_t capacity)
Definition at line 38 of file kest_bump_arena.c.
Referenced by kest_eff_parser_init_mempool().
kest_bump_arena_init_empty()
int kest_bump_arena_init_empty (kest_bump_arena * arena)
Definition at line 9 of file kest_bump_arena.c.
kest_bump_arena_realloc()
void * kest_bump_arena_realloc (kest_bump_arena * arena, void * p, size_t size)
Definition at line 100 of file kest_bump_arena.c.
kest_bump_arena_reset()
int kest_bump_arena_reset (kest_bump_arena * arena)
Definition at line 120 of file kest_bump_arena.c.
Referenced by kest_eff_parser_reset_mempool().