Kestrel Interface: kest_menu.c File Reference
kest_menu.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (kest_menu_item)
int init_menu_item (kest_menu_item *item)
void menu_page_link_clicked_cb (lv_event_t *e)
int configure_menu_item (kest_menu_item *item)
int delete_menu_item_ui (kest_menu_item *item)
int free_menu_item (kest_menu_item *item)
int refresh_menu_item (kest_menu_item *item)
void parameter_widget_change_cb_settings_wrapper (lv_event_t *e)
void danger_button_value_changed_cb (lv_event_t *e)
void danger_button_activate_popup_cb (lv_event_t *e)
kest_menu_item * create_profile_listing_menu_item (char *text, kest_profile *profile, kest_ui_page *parent)
int profile_listing_menu_item_refresh_active (kest_menu_item *item)
int profile_listing_menu_item_change_name (kest_menu_item *item, char *name)
void profile_listing_delete_button_cb (lv_event_t *e)
void disappear_profile_listing_delete_button (lv_timer_t *timer)
void menu_item_profile_listing_released_cb (lv_event_t *e)
void menu_item_profile_listing_long_pressed_cb (lv_event_t *e)
int create_menu_item_ui (kest_menu_item *item, lv_obj_t *parent)
kest_menu_item * create_pad_menu_item (int pad_height)
kest_menu_item * create_page_link_menu_item (char *text, kest_ui_page *linked_page, kest_ui_page *parent)
kest_menu_item * create_page_linindirect_k_menu_item (char *text, kest_ui_page **linked_page, kest_ui_page *parent)
kest_menu_item * create_parameter_widget_menu_item (kest_parameter *param, kest_ui_page *parent)
kest_menu_item * create_danger_button_menu_item (void(*action_cb)(void *arg), void *arg, const char *text, kest_ui_page *parent)
int init_menu_page_str (kest_menu_page_str *str)
int init_menu_page (kest_ui_page *page)
int configure_menu_page (kest_ui_page *page, void *data)
int create_menu_page_ui (kest_ui_page *page)
int enter_menu_page (kest_ui_page *page)
int refresh_menu_page (kest_ui_page *page)
int free_menu_page_ui (kest_ui_page *page)
int menu_page_add_item (kest_menu_page_str *str, kest_menu_item *item)
void enter_main_menu_cb (lv_event_t *e)
int init_main_menu (kest_ui_page *page)
void kest_msc_button_cb (lv_event_t *e)
int configure_main_menu (kest_ui_page *page, void *data)
int create_main_menu_ui (kest_ui_page *page)
int enter_main_menu (kest_ui_page *page)
int menu_page_remove_item (kest_ui_page *page, kest_menu_item *item)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_menu.c.
Function Documentation
configure_main_menu()
int configure_main_menu (kest_ui_page * page, void * data)
Definition at line 779 of file kest_menu.c.
Referenced by init_main_menu().
configure_menu_item()
int configure_menu_item (kest_menu_item * item)
Definition at line 58 of file kest_menu.c.
Referenced by configure_menu_page().
configure_menu_page()
int configure_menu_page (kest_ui_page * page, void * data)
Definition at line 581 of file kest_menu.c.
Referenced by configure_menu_page(), and init_menu_page().
create_danger_button_menu_item()
kest_menu_item * create_danger_button_menu_item (void(* action_cb)(void *arg), void * arg, const char * text, kest_ui_page * parent)
Definition at line 523 of file kest_menu.c.
create_main_menu_ui()
int create_main_menu_ui (kest_ui_page * page)
Definition at line 858 of file kest_menu.c.
Referenced by init_main_menu().
create_menu_item_ui()
int create_menu_item_ui (kest_menu_item * item, lv_obj_t * parent)
Definition at line 357 of file kest_menu.c.
Referenced by create_menu_page_ui(), and sequence_list_add_cb().
create_menu_page_ui()
int create_menu_page_ui (kest_ui_page * page)
Definition at line 620 of file kest_menu.c.
Referenced by create_menu_page_ui(), and init_menu_page().
create_pad_menu_item()
kest_menu_item * create_pad_menu_item (int pad_height)
Definition at line 440 of file kest_menu.c.
create_page_linindirect_k_menu_item()
kest_menu_item * create_page_linindirect_k_menu_item (char * text, kest_ui_page ** linked_page, kest_ui_page * parent)
Definition at line 475 of file kest_menu.c.
create_page_link_menu_item()
kest_menu_item * create_page_link_menu_item (char * text, kest_ui_page * linked_page, kest_ui_page * parent)
Definition at line 455 of file kest_menu.c.
create_parameter_widget_menu_item()
kest_menu_item * create_parameter_widget_menu_item (kest_parameter * param, kest_ui_page * parent)
Definition at line 492 of file kest_menu.c.
create_profile_listing_menu_item()
kest_menu_item * create_profile_listing_menu_item (char * text, kest_profile * profile, kest_ui_page * parent)
Definition at line 208 of file kest_menu.c.
danger_button_activate_popup_cb()
void danger_button_activate_popup_cb (lv_event_t * e)
Definition at line 184 of file kest_menu.c.
Referenced by create_menu_item_ui().
danger_button_value_changed_cb()
void danger_button_value_changed_cb (lv_event_t * e)
Definition at line 159 of file kest_menu.c.
delete_menu_item_ui()
int delete_menu_item_ui (kest_menu_item * item)
Definition at line 97 of file kest_menu.c.
Referenced by menu_page_remove_item().
disappear_profile_listing_delete_button()
void disappear_profile_listing_delete_button (lv_timer_t * timer)
Definition at line 297 of file kest_menu.c.
Referenced by menu_item_profile_listing_released_cb().
enter_main_menu()
int enter_main_menu (kest_ui_page * page)
Definition at line 918 of file kest_menu.c.
Referenced by init_main_menu().
enter_main_menu_cb()
void enter_main_menu_cb (lv_event_t * e)
Definition at line 743 of file kest_menu.c.
enter_menu_page()
int enter_menu_page (kest_ui_page * page)
Definition at line 661 of file kest_menu.c.
Referenced by init_menu_page().
free_menu_item()
int free_menu_item (kest_menu_item * item)
Definition at line 114 of file kest_menu.c.
Referenced by create_parameter_widget_menu_item(), and menu_page_remove_item().
free_menu_page_ui()
int free_menu_page_ui (kest_ui_page * page)
Definition at line 716 of file kest_menu.c.
Referenced by init_menu_page().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (kest_menu_item)
init_main_menu()
int init_main_menu (kest_ui_page * page)
Definition at line 748 of file kest_menu.c.
Referenced by kest_init_global_pages().
init_menu_item()
int init_menu_item (kest_menu_item * item)
Definition at line 11 of file kest_menu.c.
Referenced by create_danger_button_menu_item(), create_pad_menu_item(), create_page_linindirect_k_menu_item(), create_page_link_menu_item(), create_parameter_widget_menu_item(), create_profile_listing_menu_item(), and create_sequence_listing_menu_item().
init_menu_page()
int init_menu_page (kest_ui_page * page)
Definition at line 559 of file kest_menu.c.
Referenced by init_sequence_list().
init_menu_page_str()
int init_menu_page_str (kest_menu_page_str * str)
Definition at line 545 of file kest_menu.c.
Referenced by init_menu_page().
kest_msc_button_cb()
void kest_msc_button_cb (lv_event_t * e)
Definition at line 763 of file kest_menu.c.
Referenced by configure_main_menu().
menu_item_profile_listing_long_pressed_cb()
void menu_item_profile_listing_long_pressed_cb (lv_event_t * e)
Definition at line 336 of file kest_menu.c.
Referenced by create_menu_item_ui().
menu_item_profile_listing_released_cb()
void menu_item_profile_listing_released_cb (lv_event_t * e)
Definition at line 306 of file kest_menu.c.
Referenced by create_menu_item_ui().
menu_page_add_item()
int menu_page_add_item (kest_menu_page_str * str, kest_menu_item * item)
Definition at line 726 of file kest_menu.c.
Referenced by configure_sequence_list(), and sequence_list_add_cb().
menu_page_link_clicked_cb()
void menu_page_link_clicked_cb (lv_event_t * e)
Definition at line 42 of file kest_menu.c.
Referenced by create_menu_item_ui().
menu_page_remove_item()
int menu_page_remove_item (kest_ui_page * page, kest_menu_item * item)
Definition at line 926 of file kest_menu.c.
Referenced by profile_listing_delete_button_cb(), and sequence_listing_delete_button_cb().
parameter_widget_change_cb_settings_wrapper()
void parameter_widget_change_cb_settings_wrapper (lv_event_t * e)
Definition at line 144 of file kest_menu.c.
Referenced by create_menu_item_ui().
profile_listing_delete_button_cb()
void profile_listing_delete_button_cb (lv_event_t * e)
Definition at line 277 of file kest_menu.c.
Referenced by create_menu_item_ui().
profile_listing_menu_item_change_name()
int profile_listing_menu_item_change_name (kest_menu_item * item, char * name)
Definition at line 262 of file kest_menu.c.
profile_listing_menu_item_refresh_active()
int profile_listing_menu_item_refresh_active (kest_menu_item * item)
Definition at line 231 of file kest_menu.c.
refresh_menu_item()
int refresh_menu_item (kest_menu_item * item)
Definition at line 126 of file kest_menu.c.
Referenced by refresh_menu_page().
refresh_menu_page()
int refresh_menu_page (kest_ui_page * page)
Definition at line 695 of file kest_menu.c.
Referenced by enter_menu_page().