Kestrel Interface: kest_alloc.c File Reference
kest_alloc.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
void * kest_alloc (size_t size)
void kest_free (void *ptr)
void * kest_realloc (void *ptr, size_t size)
char * kest_strndup (const char *str, size_t n)
void kest_mem_monitor_task (void *param)
void kest_mem_init ()
void lv_mem_init (void)
void lv_mem_deinit (void)
void * lv_malloc_core (size_t size)
void * lv_realloc_core (void *p, size_t new_size)
void lv_free_core (void *p)
void * kest_lv_malloc (size_t size)
void kest_lv_free (void *ptr)
void print_memory_report ()
void * kest_allocator_alloc (kest_allocator *a, size_t n)
void * kest_allocator_realloc (kest_allocator *a, void *p, size_t n)
void * kest_allocator_strndup (kest_allocator *a, const char *str, int n)
void kest_allocator_free (kest_allocator *a, void *p)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_alloc.c.
Function Documentation
kest_alloc()
void * kest_alloc (size_t size)
Definition at line 11 of file kest_alloc.c.
Referenced by clone_pipeline(), clone_setting(), configure_effect_view(), configure_main_menu(), create_danger_button_menu_item(), create_effect_view_for(), create_menu_item_ui(), create_pad_menu_item(), create_page_linindirect_k_menu_item(), create_page_link_menu_item(), create_panel(), create_parameter_widget_menu_item(), create_profile_listing_menu_item(), create_profile_view_for(), create_sequence_listing_menu_item(), create_sequence_view_for(), create_ui_page(), effect_add_parameter(), effect_add_setting(), erase_folder(), init_amplifier(), init_delay(), init_distortion(), init_effect(), init_effect_selector_eff(), init_effect_settings_page(), init_effect_view(), init_flanger(), init_menu_page(), init_profile_view(), init_sequence_view(), init_test_page(), kest_active_button_array_append_new(), kest_active_button_array_new(), kest_active_button_array_set_length(), kest_allocator_alloc(), kest_bump_arena_init(), kest_context_add_profile(), kest_context_add_profile_rp(), kest_context_add_sequence_rp(), kest_defs_section_extract(), kest_extract_parameter_from_dict(), kest_extract_resource_from_dict(), kest_extract_setting_from_dict(), kest_fpga_batch_concat(), kest_new_expr_scope(), kest_new_expr_scope_entry_expr(), kest_new_expr_scope_entry_param(), kest_new_expr_scope_entry_setting(), kest_new_fpga_transfer_batch(), kest_parameter_make_clone(), kest_parameter_make_clone_for_effect(), kest_parse_asm_line(), kest_pipeline_append_effect_eff(), kest_process_asm_line(), kest_profile_set_default_name_from_id(), kest_read_eff_desc_from_file(), kest_realloc(), kest_setting_make_clone(), kest_setting_make_clone_for_effect(), kest_string_to_native(), kest_strndup(), kest_token_ll_safe_append(), list_files_in_directory(), load_saved_profiles(), load_saved_sequences(), load_state_from_file(), lv_malloc_core(), new_button(), new_m_expression_binary(), new_m_expression_const(), new_m_expression_reference(), new_m_expression_unary(), new_m_parameter_wni(), new_panel(), sequence_append_profile(), and sequence_append_profile_rp().
kest_allocator_alloc()
void * kest_allocator_alloc (kest_allocator * a, size_t n)
Definition at line 177 of file kest_alloc.c.
Referenced by kest_allocator_strndup(), kest_dict_entry_to_string(), kest_filter_create(), and kest_string_to_native_with_allocator().
kest_allocator_free()
void kest_allocator_free (kest_allocator * a, void * p)
Definition at line 208 of file kest_alloc.c.
kest_allocator_realloc()
void * kest_allocator_realloc (kest_allocator * a, void * p, size_t n)
Definition at line 185 of file kest_alloc.c.
kest_allocator_strndup()
void * kest_allocator_strndup (kest_allocator * a, const char * str, int n)
Definition at line 193 of file kest_alloc.c.
kest_free()
void kest_free (void * ptr)
Definition at line 32 of file kest_alloc.c.
Referenced by cxt_remove_profile(), cxt_remove_sequence(), effect_add_parameter(), effect_add_setting(), erase_folder(), free_effect(), free_effect_view(), free_menu_item(), free_parameter_widget(), free_profile(), free_setting_widget(), gut_profile(), gut_setting(), init_profile_view(), kest_active_button_array_append_new(), kest_active_button_free(), kest_allocator_free(), kest_bump_arena_destroy(), kest_expression_compute_format(), kest_extract_filter_coefs_from_dict(), kest_extract_parameter_from_dict(), kest_extract_resource_from_dict(), kest_extract_setting_from_dict(), kest_free_fpga_transfer_batch(), kest_parameter_free(), kest_parse_dict_list(), kest_parse_dict_val(), kest_pipeline_remove_effect(), kest_profile_set_default_name_from_id(), kest_realloc(), kest_representation_pll_remove(), kest_sequence_remove_profile(), kest_setting_free(), lv_free_core(), menu_page_remove_item(), new_m_expression_binary(), new_m_expression_reference(), new_m_expression_unary(), print_dict(), profile_view_save_name(), save_sequence(), sequence_view_set_name(), sw_field_cancel_cb(), and sw_field_save_cb().
kest_lv_free()
void kest_lv_free (void * ptr)
Definition at line 165 of file kest_alloc.c.
kest_lv_malloc()
void * kest_lv_malloc (size_t size)
Definition at line 160 of file kest_alloc.c.
kest_mem_init()
void kest_mem_init ()
Definition at line 116 of file kest_alloc.c.
Referenced by app_main().
kest_mem_monitor_task()
void kest_mem_monitor_task (void * param)
Definition at line 104 of file kest_alloc.c.
Referenced by kest_mem_init().
kest_realloc()
void * kest_realloc (void * ptr, size_t size)
Definition at line 45 of file kest_alloc.c.
Referenced by kest_allocator_realloc(), kest_fpga_batch_append(), kest_fpga_batch_concat(), and lv_realloc_core().
kest_strndup()
char * kest_strndup (const char * str, size_t n)
Definition at line 73 of file kest_alloc.c.
Referenced by clone_profile(), configure_effect_settings_page(), configure_profile_settings_page(), create_danger_button_menu_item(), create_page_linindirect_k_menu_item(), create_page_link_menu_item(), create_profile_listing_menu_item(), create_sequence_listing_menu_item(), edit_sw_field_cb(), kest_defs_section_extract(), kest_extract_parameter_from_dict(), kest_extract_resource_from_dict(), kest_extract_setting_from_dict(), kest_read_eff_desc_from_file(), new_m_expression_reference(), profile_view_save_name(), sequence_listing_menu_item_change_name(), sequence_view_set_name(), and sw_field_save_cb().
lv_free_core()
void lv_free_core (void * p)
Definition at line 155 of file kest_alloc.c.
lv_malloc_core()
void * lv_malloc_core (size_t size)
Definition at line 146 of file kest_alloc.c.
lv_mem_deinit()
void lv_mem_deinit (void)
Definition at line 141 of file kest_alloc.c.
lv_mem_init()
void lv_mem_init (void)
Definition at line 136 of file kest_alloc.c.
lv_realloc_core()
void * lv_realloc_core (void * p, size_t new_size)
Definition at line 150 of file kest_alloc.c.
print_memory_report()
void print_memory_report ()
Definition at line 172 of file kest_alloc.c.
Referenced by app_main(), and kest_mem_monitor_task().