Kestrel Interface: kest_asm_parser.c File Reference
kest_asm_parser.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
#define CH_DELIMITER 'c'
#define KEST_EXPR_DELIMITER "["
#define RS_DELIMITER "$"
#define DQ_CODELIMITER "]"
Functions
IMPLEMENT_LINKED_PTR_LIST (kest_asm_line)
const kest_arg_format * kest_instr_arg_format (const char *instr)
int kest_instr_opcode (const char *instr)
int kest_parse_asm_arg (kest_eff_parsing_state *ps, kest_asm_operand *arg)
int kest_parse_asm_arg_2 (kest_eff_parsing_state *ps, kest_asm_arg *arg)
int is_valid_instr (const char *instr)
int kest_parse_asm_line (kest_eff_parsing_state *ps)
int kest_parse_asm (kest_eff_parsing_state *ps)
kest_dsp_resource * kest_resource_get_by_name (kest_dsp_resource_pll *resources, const char *name)
int kest_process_asm_line (kest_eff_parsing_state *ps, kest_asm_line *line)
int kest_process_asm_lines (kest_eff_parsing_state *ps)
Macro Definition Documentation
CH_DELIMITER
#define CH_DELIMITER 'c'
Definition at line 13 of file kest_asm_parser.c.
Referenced by kest_parse_asm_arg(), and kest_parse_asm_arg_2().
DQ_CODELIMITER
#define DQ_CODELIMITER "]"
Definition at line 16 of file kest_asm_parser.c.
Referenced by kest_parse_asm_arg(), and kest_parse_asm_arg_2().
KEST_EXPR_DELIMITER
#define KEST_EXPR_DELIMITER "["
Definition at line 14 of file kest_asm_parser.c.
Referenced by kest_parse_asm_arg(), and kest_parse_asm_arg_2().
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 8 of file kest_asm_parser.c.
RS_DELIMITER
#define RS_DELIMITER "$"
Definition at line 15 of file kest_asm_parser.c.
Referenced by kest_parse_asm_arg(), and kest_parse_asm_arg_2().
Function Documentation
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (kest_asm_line)
is_valid_instr()
int is_valid_instr (const char * instr)
Definition at line 546 of file kest_asm_parser.c.
Referenced by kest_parse_asm_line().
kest_instr_arg_format()
const kest_arg_format * kest_instr_arg_format (const char * instr)
Definition at line 174 of file kest_asm_parser.c.
Referenced by kest_process_asm_line().
kest_instr_opcode()
int kest_instr_opcode (const char * instr)
Definition at line 208 of file kest_asm_parser.c.
Referenced by kest_process_asm_line().
kest_parse_asm()
int kest_parse_asm (kest_eff_parsing_state * ps)
Definition at line 1248 of file kest_asm_parser.c.
Referenced by kest_parse_code_section().
kest_parse_asm_arg()
int kest_parse_asm_arg (kest_eff_parsing_state * ps, kest_asm_operand * arg)
Definition at line 242 of file kest_asm_parser.c.
Referenced by kest_parse_asm_line().
kest_parse_asm_arg_2()
int kest_parse_asm_arg_2 (kest_eff_parsing_state * ps, kest_asm_arg * arg)
Definition at line 402 of file kest_asm_parser.c.
Referenced by kest_parse_asm_line().
kest_parse_asm_line()
int kest_parse_asm_line (kest_eff_parsing_state * ps)
Definition at line 557 of file kest_asm_parser.c.
Referenced by kest_parse_asm().
kest_process_asm_line()
int kest_process_asm_line (kest_eff_parsing_state * ps, kest_asm_line * line)
Definition at line 1297 of file kest_asm_parser.c.
Referenced by kest_process_asm_lines().
kest_process_asm_lines()
int kest_process_asm_lines (kest_eff_parsing_state * ps)
Definition at line 1491 of file kest_asm_parser.c.
Referenced by kest_read_eff_desc_from_file().
kest_resource_get_by_name()
kest_dsp_resource * kest_resource_get_by_name (kest_dsp_resource_pll * resources, const char * name)
Definition at line 1279 of file kest_asm_parser.c.
Referenced by kest_process_asm_line().