Kestrel Interface: kest_fpga_encoding.c File Reference
kest_fpga_encoding.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 1
Functions
int kest_fpga_block_opcode_format (int opcode)
int kest_block_instr_format (kest_block *block)
uint32_t kest_encode_dsp_block_instr_type_a (kest_block *block)
uint32_t kest_encode_dsp_block_instr_type_b (kest_block *block, int res_handle)
uint32_t kest_block_instr_encode_resource_aware (kest_block *block, const kest_eff_resource_report *res)
int kest_fpga_batch_append_block_number (kest_fpga_transfer_batch *batch, int block)
int kest_fpga_batch_append_block_instr (kest_fpga_transfer_batch *batch, kest_block *block, const kest_eff_resource_report *res, int pos)
int kest_fpga_batch_append_block_regs (kest_fpga_transfer_batch *batch, kest_block *block, kest_expr_scope *scope, int pos)
int kest_fpga_batch_append_block_register_updates (kest_fpga_transfer_batch *batch, kest_block *block, kest_expr_scope *scope, int pos)
int kest_fpga_transfer_batch_append_effect_register_updates (kest_fpga_transfer_batch *batch, kest_effect_desc *eff, kest_expr_scope *scope, int pos)
int kest_fpga_batch_append_block (kest_fpga_transfer_batch *batch, kest_block *block, const kest_eff_resource_report *res, kest_expr_scope *scope, int pos)
int kest_fpga_batch_append_blocks (kest_fpga_transfer_batch *batch, kest_block_pll *blocks, const kest_eff_resource_report *res, kest_expr_scope *scope, int pos)
int kest_fpga_batch_append_resource (kest_fpga_transfer_batch *batch, kest_dsp_resource *res, const kest_eff_resource_report *rpt, kest_expr_scope *scope)
int kest_fpga_batch_append_resources (kest_fpga_transfer_batch *batch, kest_dsp_resource_pll *list, const kest_eff_resource_report *rpt, kest_expr_scope *scope)
int kest_fpga_batch_append_eff_desc (kest_fpga_transfer_batch *batch, kest_effect_desc *eff, const kest_eff_resource_report *res, kest_expr_scope *scope, int pos)
int kest_fpga_batch_append_effect (kest_fpga_transfer_batch *batch, kest_effect *effect, kest_eff_resource_report *res, int *pos)
int kest_fpga_batch_append_effects (kest_fpga_transfer_batch *batch, kest_effect_pll *list, kest_eff_resource_report *res, int *pos)
char * kest_block_opcode_to_string (uint32_t opcode)
char * kest_block_opcode_to_name (uint32_t opcode)
void print_instruction_format_a (uint32_t instr)
void print_instruction_format_b (uint32_t instr)
void print_instruction (uint32_t instr)
int kest_fpga_batch_print (kest_fpga_transfer_batch seq)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 1
Definition at line 10 of file kest_fpga_encoding.c.
Function Documentation
kest_block_instr_encode_resource_aware()
uint32_t kest_block_instr_encode_resource_aware (kest_block * block, const kest_eff_resource_report * res)
Definition at line 60 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_block_instr().
kest_block_instr_format()
int kest_block_instr_format (kest_block * block)
Definition at line 32 of file kest_fpga_encoding.c.
Referenced by kest_block_instr_encode_resource_aware().
kest_block_opcode_to_name()
char * kest_block_opcode_to_name (uint32_t opcode)
Definition at line 407 of file kest_fpga_encoding.c.
Referenced by print_instruction_format_a(), and print_instruction_format_b().
kest_block_opcode_to_string()
char * kest_block_opcode_to_string (uint32_t opcode)
Definition at line 378 of file kest_fpga_encoding.c.
kest_encode_dsp_block_instr_type_a()
uint32_t kest_encode_dsp_block_instr_type_a (kest_block * block)
Definition at line 39 of file kest_fpga_encoding.c.
Referenced by kest_block_instr_encode_resource_aware().
kest_encode_dsp_block_instr_type_b()
uint32_t kest_encode_dsp_block_instr_type_b (kest_block * block, int res_handle)
Definition at line 51 of file kest_fpga_encoding.c.
Referenced by kest_block_instr_encode_resource_aware().
kest_fpga_batch_append_block()
int kest_fpga_batch_append_block (kest_fpga_transfer_batch * batch, kest_block * block, const kest_eff_resource_report * res, kest_expr_scope * scope, int pos)
Definition at line 215 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_blocks().
kest_fpga_batch_append_block_instr()
int kest_fpga_batch_append_block_instr (kest_fpga_transfer_batch * batch, kest_block * block, const kest_eff_resource_report * res, int pos)
Definition at line 111 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_block().
kest_fpga_batch_append_block_number()
int kest_fpga_batch_append_block_number (kest_fpga_transfer_batch * batch, int block)
Definition at line 100 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_block_instr(), kest_fpga_batch_append_block_register_updates(), and kest_fpga_batch_append_block_regs().
kest_fpga_batch_append_block_register_updates()
int kest_fpga_batch_append_block_register_updates (kest_fpga_transfer_batch * batch, kest_block * block, kest_expr_scope * scope, int pos)
Definition at line 157 of file kest_fpga_encoding.c.
Referenced by kest_fpga_transfer_batch_append_effect_register_updates().
kest_fpga_batch_append_block_regs()
int kest_fpga_batch_append_block_regs (kest_fpga_transfer_batch * batch, kest_block * block, kest_expr_scope * scope, int pos)
Definition at line 125 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_block().
kest_fpga_batch_append_blocks()
int kest_fpga_batch_append_blocks (kest_fpga_transfer_batch * batch, kest_block_pll * blocks, const kest_eff_resource_report * res, kest_expr_scope * scope, int pos)
Definition at line 226 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_eff_desc().
kest_fpga_batch_append_eff_desc()
int kest_fpga_batch_append_eff_desc (kest_fpga_transfer_batch * batch, kest_effect_desc * eff, const kest_eff_resource_report * res, kest_expr_scope * scope, int pos)
Definition at line 327 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_effect().
kest_fpga_batch_append_effect()
int kest_fpga_batch_append_effect (kest_fpga_transfer_batch * batch, kest_effect * effect, kest_eff_resource_report * res, int * pos)
Definition at line 338 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_effects().
kest_fpga_batch_append_effects()
int kest_fpga_batch_append_effects (kest_fpga_transfer_batch * batch, kest_effect_pll * list, kest_eff_resource_report * res, int * pos)
Definition at line 360 of file kest_fpga_encoding.c.
Referenced by kest_pipeline_create_fpga_transfer_batch().
kest_fpga_batch_append_resource()
int kest_fpga_batch_append_resource (kest_fpga_transfer_batch * batch, kest_dsp_resource * res, const kest_eff_resource_report * rpt, kest_expr_scope * scope)
Definition at line 248 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_resources().
kest_fpga_batch_append_resources()
int kest_fpga_batch_append_resources (kest_fpga_transfer_batch * batch, kest_dsp_resource_pll * list, const kest_eff_resource_report * rpt, kest_expr_scope * scope)
Definition at line 311 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_eff_desc().
kest_fpga_batch_print()
int kest_fpga_batch_print (kest_fpga_transfer_batch seq)
Definition at line 496 of file kest_fpga_encoding.c.
Referenced by kest_fpga_comms_task().
kest_fpga_block_opcode_format()
int kest_fpga_block_opcode_format (int opcode)
Definition at line 21 of file kest_fpga_encoding.c.
Referenced by kest_block_instr_format(), and kest_fpga_batch_print().
kest_fpga_transfer_batch_append_effect_register_updates()
int kest_fpga_transfer_batch_append_effect_register_updates (kest_fpga_transfer_batch * batch, kest_effect_desc * eff, kest_expr_scope * scope, int pos)
Definition at line 196 of file kest_fpga_encoding.c.
Referenced by kest_effect_update_fpga_registers().
print_instruction()
void print_instruction (uint32_t instr)
Definition at line 486 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_print().
print_instruction_format_a()
void print_instruction_format_a (uint32_t instr)
Definition at line 434 of file kest_fpga_encoding.c.
Referenced by print_instruction().
print_instruction_format_b()
void print_instruction_format_b (uint32_t instr)
Definition at line 460 of file kest_fpga_encoding.c.
Referenced by print_instruction().