Kestrel Interface: kest_pipeline.h File Reference
kest_pipeline.h File Reference
Data Structures
struct kest_pipeline
Functions
int init_m_pipeline (kest_pipeline *pipeline)
kest_effect * kest_pipeline_append_effect_eff (kest_pipeline *pipeline, kest_effect_desc *eff)
int kest_pipeline_move_effect (kest_pipeline *pipeline, int new_pos, int old_pos)
int kest_pipeline_remove_effect (kest_pipeline *pipeline, uint16_t id)
int kest_pipeline_get_n_effects (kest_pipeline *pipeline)
kest_effect * kest_pipeline_get_effect_by_id (kest_pipeline *pipeline, int id)
int clone_pipeline (kest_pipeline *dest, kest_pipeline *src)
void gut_pipeline (kest_pipeline *pipeline)
int kest_pipeline_create_fpga_transfer_batch (kest_pipeline *pipeline, kest_fpga_transfer_batch *batch)
Function Documentation
clone_pipeline()
int clone_pipeline (kest_pipeline * dest, kest_pipeline * src)
Definition at line 177 of file kest_pipeline.c.
Referenced by clone_profile().
gut_pipeline()
void gut_pipeline (kest_pipeline * pipeline)
Definition at line 214 of file kest_pipeline.c.
Referenced by gut_profile().
init_m_pipeline()
int init_m_pipeline (kest_pipeline * pipeline)
Definition at line 9 of file kest_pipeline.c.
kest_pipeline_append_effect_eff()
kest_effect * kest_pipeline_append_effect_eff (kest_pipeline * pipeline, kest_effect_desc * eff)
Definition at line 19 of file kest_pipeline.c.
Referenced by kest_profile_append_effect_eff().
kest_pipeline_create_fpga_transfer_batch()
int kest_pipeline_create_fpga_transfer_batch (kest_pipeline * pipeline, kest_fpga_transfer_batch * batch)
Definition at line 223 of file kest_pipeline.c.
Referenced by kest_profile_create_fpga_transfer_batch(), and kest_profile_program_fpga().
kest_pipeline_get_effect_by_id()
kest_effect * kest_pipeline_get_effect_by_id (kest_pipeline * pipeline, int id)
Definition at line 271 of file kest_pipeline.c.
Referenced by kest_profile_get_effect_by_id().
kest_pipeline_get_n_effects()
int kest_pipeline_get_n_effects (kest_pipeline * pipeline)
Definition at line 158 of file kest_pipeline.c.
kest_pipeline_move_effect()
int kest_pipeline_move_effect (kest_pipeline * pipeline, int new_pos, int old_pos)
Definition at line 106 of file kest_pipeline.c.
Referenced by kest_profile_move_effect().
kest_pipeline_remove_effect()
int kest_pipeline_remove_effect (kest_pipeline * pipeline, uint16_t id)
Definition at line 70 of file kest_pipeline.c.
Referenced by kest_profile_remove_effect().