Kestrel Interface: kest_expr_scope.h File Reference
kest_expr_scope.h File Reference
Data Structures
struct kest_expr_scope_entry
struct kest_expr_scope
Macros
#define KEST_SCOPE_ENTRY_TYPE_EXPR 0
#define KEST_SCOPE_ENTRY_TYPE_PARAM 1
#define KEST_SCOPE_ENTRY_TYPE_SETTING 2
Functions
kest_expr_scope_entry * kest_new_expr_scope_entry_expr (const char *name, struct kest_expression *expr)
kest_expr_scope_entry * kest_new_expr_scope_entry_param (struct kest_parameter *param)
kest_expr_scope_entry * kest_new_expr_scope_entry_setting (struct kest_setting *setting)
DECLARE_LINKED_PTR_LIST (kest_expr_scope_entry)
kest_expr_scope * kest_new_expr_scope ()
int kest_expr_scope_init (kest_expr_scope *scope)
int kest_expr_scope_add_expr (kest_expr_scope *scope, const char *name, struct kest_expression *expr)
int kest_expr_scope_add_param (kest_expr_scope *scope, struct kest_parameter *param)
int kest_expr_scope_add_setting (kest_expr_scope *scope, struct kest_setting *setting)
int kest_expr_scope_add_params (kest_expr_scope *scope, struct kest_parameter_pll *params)
int kest_expr_scope_add_settings (kest_expr_scope *scope, struct kest_setting_pll *settings)
kest_expr_scope_entry * kest_expr_scope_fetch (kest_expr_scope *scope, const char *name)
kest_expr_scope * kest_expr_scope_copy (kest_expr_scope *scope)
Macro Definition Documentation
KEST_SCOPE_ENTRY_TYPE_EXPR
#define KEST_SCOPE_ENTRY_TYPE_EXPR 0
Definition at line 4 of file kest_expr_scope.h.
Referenced by kest_expression_compute_range_rec(), and kest_new_expr_scope_entry_expr().
KEST_SCOPE_ENTRY_TYPE_PARAM
#define KEST_SCOPE_ENTRY_TYPE_PARAM 1
Definition at line 5 of file kest_expr_scope.h.
Referenced by kest_expression_compute_range_rec(), and kest_new_expr_scope_entry_param().
KEST_SCOPE_ENTRY_TYPE_SETTING
#define KEST_SCOPE_ENTRY_TYPE_SETTING 2
Definition at line 6 of file kest_expr_scope.h.
Referenced by kest_new_expr_scope_entry_setting().
Function Documentation
DECLARE_LINKED_PTR_LIST()
DECLARE_LINKED_PTR_LIST (kest_expr_scope_entry)
kest_expr_scope_add_expr()
int kest_expr_scope_add_expr (kest_expr_scope * scope, const char * name, struct kest_expression * expr)
Definition at line 88 of file kest_expr_scope.c.
Referenced by kest_defs_section_extract(), and kest_effect_create_scope().
kest_expr_scope_add_param()
int kest_expr_scope_add_param (kest_expr_scope * scope, struct kest_parameter * param)
Definition at line 106 of file kest_expr_scope.c.
Referenced by kest_eff_desc_create_scope(), kest_effect_create_scope(), and kest_expr_scope_add_params().
kest_expr_scope_add_params()
int kest_expr_scope_add_params (kest_expr_scope * scope, struct kest_parameter_pll * params)
Definition at line 142 of file kest_expr_scope.c.
Referenced by kest_parse_tokens().
kest_expr_scope_add_setting()
int kest_expr_scope_add_setting (kest_expr_scope * scope, struct kest_setting * setting)
Definition at line 124 of file kest_expr_scope.c.
Referenced by kest_effect_create_scope(), and kest_expr_scope_add_settings().
kest_expr_scope_add_settings()
int kest_expr_scope_add_settings (kest_expr_scope * scope, struct kest_setting_pll * settings)
Definition at line 161 of file kest_expr_scope.c.
Referenced by kest_parse_tokens().
kest_expr_scope_copy()
kest_expr_scope * kest_expr_scope_copy (kest_expr_scope * scope)
kest_expr_scope_fetch()
kest_expr_scope_entry * kest_expr_scope_fetch (kest_expr_scope * scope, const char * name)
Definition at line 189 of file kest_expr_scope.c.
Referenced by kest_expression_compute_range_rec().
kest_expr_scope_init()
int kest_expr_scope_init (kest_expr_scope * scope)
Definition at line 66 of file kest_expr_scope.c.
Referenced by kest_parse_tokens().
kest_new_expr_scope()
kest_expr_scope * kest_new_expr_scope ()
Definition at line 76 of file kest_expr_scope.c.
Referenced by kest_eff_desc_create_scope(), and kest_effect_create_scope().
kest_new_expr_scope_entry_expr()
kest_expr_scope_entry * kest_new_expr_scope_entry_expr (const char * name, struct kest_expression * expr)
Definition at line 11 of file kest_expr_scope.c.
Referenced by kest_expr_scope_add_expr().
kest_new_expr_scope_entry_param()
kest_expr_scope_entry * kest_new_expr_scope_entry_param (struct kest_parameter * param)
Definition at line 28 of file kest_expr_scope.c.
Referenced by kest_expr_scope_add_param().
kest_new_expr_scope_entry_setting()
kest_expr_scope_entry * kest_new_expr_scope_entry_setting (struct kest_setting * setting)
Definition at line 45 of file kest_expr_scope.c.
Referenced by kest_expr_scope_add_setting().