Kestrel Interface: kest_sequence_view.c File Reference
kest_sequence_view.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int create_sequence_view_for (kest_sequence *sequence)
int seq_view_clicked_cb (kest_active_button *button)
int seq_view_moved_cb (kest_active_button *button)
int init_sequence_view (kest_ui_page *page)
void seq_play_cb (lv_event_t *e)
void seq_plus_cb (lv_event_t *e)
void seq_save_cb (lv_event_t *e)
int seq_view_free_cb (kest_active_button *button)
int seq_view_delete_cb (kest_active_button *button)
void sequence_view_set_name (lv_event_t *e)
void sequence_view_revert_name (lv_event_t *e)
int configure_sequence_view (kest_ui_page *page, void *data)
int create_sequence_view_ui (kest_ui_page *page)
int refresh_sequence_view (kest_ui_page *page)
int free_sequence_view_ui (kest_ui_page *page)
int sequence_view_free_all (kest_ui_page *page)
void sequence_view_rep_update (void *representer, void *representee)
void sequence_view_profile_button_rep_update (void *representer, void *representee)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_sequence_view.c.
Function Documentation
configure_sequence_view()
int configure_sequence_view (kest_ui_page * page, void * data)
Definition at line 279 of file kest_sequence_view.c.
Referenced by create_sequence_view_for(), and init_sequence_view().
create_sequence_view_for()
int create_sequence_view_for (kest_sequence * sequence)
Definition at line 9 of file kest_sequence_view.c.
Referenced by load_saved_sequences(), menu_item_sequence_listing_released_cb(), and sequence_list_add_cb().
create_sequence_view_ui()
int create_sequence_view_ui (kest_ui_page * page)
Definition at line 353 of file kest_sequence_view.c.
Referenced by init_sequence_view().
free_sequence_view_ui()
int free_sequence_view_ui (kest_ui_page * page)
Definition at line 390 of file kest_sequence_view.c.
init_sequence_view()
int init_sequence_view (kest_ui_page * page)
Definition at line 65 of file kest_sequence_view.c.
Referenced by create_sequence_view_for(), and kest_init_global_pages().
refresh_sequence_view()
int refresh_sequence_view (kest_ui_page * page)
Definition at line 380 of file kest_sequence_view.c.
seq_play_cb()
void seq_play_cb (lv_event_t * e)
Definition at line 107 of file kest_sequence_view.c.
Referenced by configure_sequence_view().
seq_plus_cb()
void seq_plus_cb (lv_event_t * e)
Definition at line 131 of file kest_sequence_view.c.
Referenced by configure_sequence_view().
seq_save_cb()
void seq_save_cb (lv_event_t * e)
Definition at line 179 of file kest_sequence_view.c.
Referenced by configure_sequence_view().
seq_view_clicked_cb()
int seq_view_clicked_cb (kest_active_button * button)
Definition at line 25 of file kest_sequence_view.c.
Referenced by configure_sequence_view(), and init_sequence_view().
seq_view_delete_cb()
int seq_view_delete_cb (kest_active_button * button)
Definition at line 215 of file kest_sequence_view.c.
Referenced by configure_sequence_view().
seq_view_free_cb()
int seq_view_free_cb (kest_active_button * button)
Definition at line 205 of file kest_sequence_view.c.
seq_view_moved_cb()
int seq_view_moved_cb (kest_active_button * button)
Definition at line 46 of file kest_sequence_view.c.
Referenced by configure_sequence_view(), and init_sequence_view().
sequence_view_free_all()
int sequence_view_free_all (kest_ui_page * page)
Definition at line 400 of file kest_sequence_view.c.
sequence_view_profile_button_rep_update()
void sequence_view_profile_button_rep_update (void * representer, void * representee)
Definition at line 450 of file kest_sequence_view.c.
Referenced by configure_sequence_view(), and seq_plus_cb().
sequence_view_rep_update()
void sequence_view_rep_update (void * representer, void * representee)
Definition at line 411 of file kest_sequence_view.c.
Referenced by init_sequence_view().
sequence_view_revert_name()
void sequence_view_revert_name (lv_event_t * e)
Definition at line 264 of file kest_sequence_view.c.
Referenced by configure_sequence_view().
sequence_view_set_name()
void sequence_view_set_name (lv_event_t * e)
Definition at line 239 of file kest_sequence_view.c.
Referenced by configure_sequence_view().