Kestrel Interface: kest_string.c File Reference
kest_string.c File Reference
#include "kest_int.h"
Functions
IMPLEMENT_LIST (char)
int char_cmp (const char *a, const char *b)
int kest_string_init (kest_string *string)
int kest_string_init_from_str (kest_string *string, char *str)
int kest_string_init_with_allocator (kest_string *string, const kest_allocator *alloc)
int kest_string_init_reserved (kest_string *string, size_t n)
int kest_string_init_reserved_with_allocator (kest_string *string, size_t n, const kest_allocator *alloc)
int kest_string_reserve (kest_string *string, size_t n)
int kest_string_append (kest_string *string, char x)
int kest_string_append_int (kest_string *string, int x)
int kest_string_append_str (kest_string *string, const char *str)
int kest_string_concat (kest_string *a, kest_string *b)
int kest_string_destroy (kest_string *string)
int kest_string_contains (kest_string *string, char c)
int kest_string_index_of (kest_string *string, char x)
char * kest_string_head (kest_string *string)
char * kest_string_tail (kest_string *string)
int kest_string_pop_tail (kest_string *string)
int kest_string_drain (kest_string *string)
int kest_string_len (kest_string *string)
int kest_string_write_out (kest_string *string, char *buf, size_t buf_len)
char * kest_string_to_native (kest_string *string)
char * kest_string_to_native_with_allocator (kest_string *string, kest_allocator *alloc)
int kest_string_appendf (kest_string *string, const char *fmt,...)
Function Documentation
char_cmp()
int char_cmp (const char * a, const char * b)
Definition at line 5 of file kest_string.c.
Referenced by kest_string_contains(), and kest_string_index_of().
IMPLEMENT_LIST()
IMPLEMENT_LIST (char)
kest_string_append()
int kest_string_append (kest_string * string, char x)
Definition at line 56 of file kest_string.c.
Referenced by kest_dict_entry_to_string(), kest_parse_dict_list(), and print_dict().
kest_string_append_int()
int kest_string_append_int (kest_string * string, int x)
Definition at line 61 of file kest_string.c.
kest_string_append_str()
int kest_string_append_str (kest_string * string, const char * str)
Definition at line 73 of file kest_string.c.
Referenced by kest_parse_dict_list(), kest_string_append_int(), and kest_string_appendf().
kest_string_appendf()
int kest_string_appendf (kest_string * string, const char * fmt, ...)
Definition at line 211 of file kest_string.c.
Referenced by kest_dict_entry_to_string(), kest_expression_compute_format(), kest_parse_dict_list(), and print_dict().
kest_string_concat()
int kest_string_concat (kest_string * a, kest_string * b)
Definition at line 92 of file kest_string.c.
Referenced by kest_dict_entry_to_string(), and print_dict().
kest_string_contains()
int kest_string_contains (kest_string * string, char c)
Definition at line 102 of file kest_string.c.
kest_string_destroy()
int kest_string_destroy (kest_string * string)
Definition at line 97 of file kest_string.c.
Referenced by kest_compute_register_formats(), kest_dict_entry_to_string(), kest_expression_compute_format(), kest_extract_filter_coefs_from_dict(), kest_parse_dict_list(), kest_parse_dict_val(), and print_dict().
kest_string_drain()
int kest_string_drain (kest_string * string)
Definition at line 127 of file kest_string.c.
kest_string_head()
char * kest_string_head (kest_string * string)
Definition at line 112 of file kest_string.c.
kest_string_index_of()
int kest_string_index_of (kest_string * string, char x)
Definition at line 107 of file kest_string.c.
kest_string_init()
int kest_string_init (kest_string * string)
Definition at line 12 of file kest_string.c.
Referenced by kest_compute_register_formats(), kest_dict_entry_to_string(), kest_expression_compute_format(), kest_string_init_from_str(), and print_dict().
kest_string_init_from_str()
int kest_string_init_from_str (kest_string * string, char * str)
Definition at line 17 of file kest_string.c.
kest_string_init_reserved()
int kest_string_init_reserved (kest_string * string, size_t n)
Definition at line 41 of file kest_string.c.
Referenced by kest_string_init_from_str().
kest_string_init_reserved_with_allocator()
int kest_string_init_reserved_with_allocator (kest_string * string, size_t n, const kest_allocator * alloc)
Definition at line 46 of file kest_string.c.
kest_string_init_with_allocator()
int kest_string_init_with_allocator (kest_string * string, const kest_allocator * alloc)
Definition at line 36 of file kest_string.c.
Referenced by kest_parse_dict_list().
kest_string_len()
int kest_string_len (kest_string * string)
Definition at line 132 of file kest_string.c.
Referenced by kest_parse_dict_list().
kest_string_pop_tail()
int kest_string_pop_tail (kest_string * string)
Definition at line 122 of file kest_string.c.
Referenced by kest_parse_dict_list().
kest_string_reserve()
int kest_string_reserve (kest_string * string, size_t n)
Definition at line 51 of file kest_string.c.
kest_string_tail()
char * kest_string_tail (kest_string * string)
Definition at line 117 of file kest_string.c.
kest_string_to_native()
char * kest_string_to_native (kest_string * string)
Definition at line 167 of file kest_string.c.
Referenced by kest_expression_compute_format(), kest_extract_filter_coefs_from_dict(), kest_parse_dict_list(), kest_parse_dict_val(), and print_dict().
kest_string_to_native_with_allocator()
char * kest_string_to_native_with_allocator (kest_string * string, kest_allocator * alloc)
Definition at line 189 of file kest_string.c.
Referenced by kest_parse_dict_list().
kest_string_write_out()
int kest_string_write_out (kest_string * string, char * buf, size_t buf_len)
Definition at line 137 of file kest_string.c.