Kestrel Interface: kest_transformer.c File Reference
kest_transformer.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
#define INITIAL_PARAMETER_ARRAY_LENGTH 8
#define PARAMETER_ARRAY_CHUNK_SIZE 8
#define INITIAL_OPTION_ARRAY_LENGTH 8
#define OPTION_ARRAY_CHUNK_SIZE 8
Functions
IMPLEMENT_LINKED_PTR_LIST (kest_effect)
const char * kest_effect_name (kest_effect *effect)
int init_effect (kest_effect *effect)
int init_effect_from_effect_desc (kest_effect *effect, kest_effect_desc *eff)
int effect_rectify_param_ids (kest_effect *effect)
int effect_set_id (kest_effect *effect, uint16_t profile_id, uint16_t effect_id)
int request_append_effect (uint16_t type, kest_effect *local)
kest_parameter * effect_add_parameter (kest_effect *effect)
kest_setting * effect_add_setting (kest_effect *effect)
int clone_effect (kest_effect *dest, kest_effect *src)
void gut_effect (kest_effect *effect)
void free_effect (kest_effect *effect)
kest_parameter * effect_get_parameter (kest_effect *effect, int n)
kest_setting * effect_get_setting (kest_effect *effect, int n)
int kest_effect_update_fpga_registers (kest_effect *effect)
kest_expr_scope * kest_effect_create_scope (kest_effect *effect)
int kest_effect_set_parameter (kest_effect *effect, const char *name, float value)
int kest_effect_set_setting (kest_effect *effect, const char *name, int value)
void kest_effect_profile_rep_update (void *representer, void *representee)
int kest_effect_update_reps (kest_effect *effect)
Macro Definition Documentation
INITIAL_OPTION_ARRAY_LENGTH
#define INITIAL_OPTION_ARRAY_LENGTH 8
Definition at line 10 of file kest_transformer.c.
INITIAL_PARAMETER_ARRAY_LENGTH
#define INITIAL_PARAMETER_ARRAY_LENGTH 8
Definition at line 7 of file kest_transformer.c.
OPTION_ARRAY_CHUNK_SIZE
#define OPTION_ARRAY_CHUNK_SIZE 8
Definition at line 11 of file kest_transformer.c.
PARAMETER_ARRAY_CHUNK_SIZE
#define PARAMETER_ARRAY_CHUNK_SIZE 8
Definition at line 8 of file kest_transformer.c.
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_transformer.c.
Function Documentation
clone_effect()
int clone_effect (kest_effect * dest, kest_effect * src)
Definition at line 345 of file kest_transformer.c.
effect_add_parameter()
kest_parameter * effect_add_parameter (kest_effect * effect)
Definition at line 237 of file kest_transformer.c.
Referenced by clone_effect().
effect_add_setting()
kest_setting * effect_add_setting (kest_effect * effect)
Definition at line 264 of file kest_transformer.c.
Referenced by clone_effect().
effect_get_parameter()
kest_parameter * effect_get_parameter (kest_effect * effect, int n)
Definition at line 448 of file kest_transformer.c.
effect_get_setting()
kest_setting * effect_get_setting (kest_effect * effect, int n)
Definition at line 466 of file kest_transformer.c.
effect_rectify_param_ids()
int effect_rectify_param_ids (kest_effect * effect)
Definition at line 130 of file kest_transformer.c.
Referenced by effect_set_id().
effect_set_id()
int effect_set_id (kest_effect * effect, uint16_t profile_id, uint16_t effect_id)
Definition at line 178 of file kest_transformer.c.
free_effect()
void free_effect (kest_effect * effect)
Definition at line 433 of file kest_transformer.c.
gut_effect()
void gut_effect (kest_effect * effect)
Definition at line 410 of file kest_transformer.c.
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (kest_effect)
init_effect()
int init_effect (kest_effect * effect)
Definition at line 29 of file kest_transformer.c.
Referenced by clone_effect(), and init_effect_from_effect_desc().
init_effect_from_effect_desc()
int init_effect_from_effect_desc (kest_effect * effect, kest_effect_desc * eff)
Definition at line 103 of file kest_transformer.c.
kest_effect_create_scope()
kest_expr_scope * kest_effect_create_scope (kest_effect * effect)
Definition at line 509 of file kest_transformer.c.
Referenced by init_effect_from_effect_desc().
kest_effect_name()
const char * kest_effect_name (kest_effect * effect)
Definition at line 17 of file kest_transformer.c.
kest_effect_profile_rep_update()
void kest_effect_profile_rep_update (void * representer, void * representee)
Definition at line 598 of file kest_transformer.c.
kest_effect_set_parameter()
int kest_effect_set_parameter (kest_effect * effect, const char * name, float value)
Definition at line 551 of file kest_transformer.c.
kest_effect_set_setting()
int kest_effect_set_setting (kest_effect * effect, const char * name, int value)
Definition at line 574 of file kest_transformer.c.
kest_effect_update_fpga_registers()
int kest_effect_update_fpga_registers (kest_effect * effect)
Definition at line 483 of file kest_transformer.c.
kest_effect_update_reps()
int kest_effect_update_reps (kest_effect * effect)
Definition at line 613 of file kest_transformer.c.
request_append_effect()
int request_append_effect (uint16_t type, kest_effect * local)
Definition at line 190 of file kest_transformer.c.