Kestrel Interface: kest_profile_view.c File Reference
kest_profile_view.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
kest_ui_page * create_profile_view_for (kest_profile *profile)
int profile_view_effect_click_cb (kest_active_button *button)
int profile_view_effect_moved_cb (kest_active_button *button)
int profile_view_effect_delete_cb (kest_active_button *button)
int init_profile_view (kest_ui_page *page)
int profile_view_save_name (kest_ui_page *page)
void profile_view_save_name_cb (lv_event_t *e)
void profile_view_revert_name (lv_event_t *e)
void profile_view_enter_settings_page_cb (lv_event_t *e)
void profile_view_enter_main_menu_cb (lv_event_t *e)
void profile_view_play_button_cb (lv_event_t *e)
int configure_profile_view (kest_ui_page *page, void *data)
int create_profile_view_ui (kest_ui_page *page)
int enter_profile_view (kest_ui_page *page)
int profile_view_append_effect (kest_ui_page *page, kest_effect *effect)
int profile_view_recalculate_indices (kest_ui_page *page)
int free_profile_view (kest_ui_page *page)
int profile_view_refresh_play_button (kest_ui_page *page)
int profile_view_refresh_save_button (kest_ui_page *page)
int profile_view_change_name (kest_ui_page *page, char *name)
int profile_view_set_left_button_mode (kest_ui_page *page, int mode)
void profile_view_rep_update (void *representer, void *representee)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_profile_view.c.
Function Documentation
configure_profile_view()
int configure_profile_view (kest_ui_page * page, void * data)
Definition at line 335 of file kest_profile_view.c.
Referenced by create_profile_view_for(), and init_profile_view().
create_profile_view_for()
kest_ui_page * create_profile_view_for (kest_profile * profile)
Definition at line 9 of file kest_profile_view.c.
Referenced by create_new_profile_with_teensy(), load_saved_profiles(), and seq_view_clicked_cb().
create_profile_view_ui()
int create_profile_view_ui (kest_ui_page * page)
Definition at line 416 of file kest_profile_view.c.
Referenced by init_profile_view().
enter_profile_view()
int enter_profile_view (kest_ui_page * page)
Definition at line 472 of file kest_profile_view.c.
Referenced by init_profile_view().
free_profile_view()
int free_profile_view (kest_ui_page * page)
Definition at line 521 of file kest_profile_view.c.
Referenced by create_profile_view_for(), and init_profile_view().
init_profile_view()
int init_profile_view (kest_ui_page * page)
Definition at line 116 of file kest_profile_view.c.
Referenced by create_profile_view_for().
profile_view_append_effect()
int profile_view_append_effect (kest_ui_page * page, kest_effect * effect)
Definition at line 488 of file kest_profile_view.c.
Referenced by add_effect_from_menu_eff().
profile_view_change_name()
int profile_view_change_name (kest_ui_page * page, char * name)
Definition at line 552 of file kest_profile_view.c.
profile_view_effect_click_cb()
int profile_view_effect_click_cb (kest_active_button * button)
Definition at line 47 of file kest_profile_view.c.
Referenced by init_profile_view().
profile_view_effect_delete_cb()
int profile_view_effect_delete_cb (kest_active_button * button)
Definition at line 93 of file kest_profile_view.c.
Referenced by init_profile_view().
profile_view_effect_moved_cb()
int profile_view_effect_moved_cb (kest_active_button * button)
Definition at line 69 of file kest_profile_view.c.
Referenced by init_profile_view().
profile_view_enter_main_menu_cb()
void profile_view_enter_main_menu_cb (lv_event_t * e)
Definition at line 300 of file kest_profile_view.c.
profile_view_enter_settings_page_cb()
void profile_view_enter_settings_page_cb (lv_event_t * e)
Definition at line 285 of file kest_profile_view.c.
Referenced by configure_profile_view().
profile_view_play_button_cb()
void profile_view_play_button_cb (lv_event_t * e)
Definition at line 305 of file kest_profile_view.c.
Referenced by configure_profile_view().
profile_view_recalculate_indices()
int profile_view_recalculate_indices (kest_ui_page * page)
Definition at line 510 of file kest_profile_view.c.
profile_view_refresh_play_button()
int profile_view_refresh_play_button (kest_ui_page * page)
Definition at line 533 of file kest_profile_view.c.
profile_view_refresh_save_button()
int profile_view_refresh_save_button (kest_ui_page * page)
Definition at line 544 of file kest_profile_view.c.
profile_view_rep_update()
void profile_view_rep_update (void * representer, void * representee)
Definition at line 577 of file kest_profile_view.c.
Referenced by init_profile_view().
profile_view_revert_name()
void profile_view_revert_name (lv_event_t * e)
Definition at line 272 of file kest_profile_view.c.
Referenced by configure_profile_view().
profile_view_save_name()
int profile_view_save_name (kest_ui_page * page)
Definition at line 235 of file kest_profile_view.c.
Referenced by profile_view_save_name_cb().
profile_view_save_name_cb()
void profile_view_save_name_cb (lv_event_t * e)
Definition at line 266 of file kest_profile_view.c.
Referenced by configure_profile_view().
profile_view_set_left_button_mode()
int profile_view_set_left_button_mode (kest_ui_page * page, int mode)
Definition at line 565 of file kest_profile_view.c.