Kestrel Interface: kest_tokenizer.c File Reference
kest_tokenizer.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (char)
int char_is_letter (char c)
int char_is_number (char c)
int char_is_alphanumeric (char c)
int char_is_bracket (char c)
int char_is_in_string (char c, const char *str)
int token_is_char (char *str, char c)
int token_is_newline (char *str)
int token_is_int (char *token)
int token_is_number (char *token)
int token_is_dict_entry_seperator (char *token)
float digit_to_float (char c)
float token_to_float (char *token)
int token_is_name (char *token)
int kest_token_ll_advance (kest_token_ll **list)
int kest_token_ll_skip_ws (kest_token_ll **list)
int kest_token_ll_safe_append (kest_token_ll **list_ptr, char *x, int line, int index)
int kest_token_ll_safe_aappend (kest_token_ll **list_ptr, char *x, int line, int index)
int tokenizer_policy (char c, int *state_ptr)
int kest_tokenize_content (kest_eff_parsing_state *ps)
kest_token_ll * kest_token_span_to_ll (kest_token_ll *start, kest_token_ll *end)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 8 of file kest_tokenizer.c.
Function Documentation
char_is_alphanumeric()
int char_is_alphanumeric (char c)
Definition at line 25 of file kest_tokenizer.c.
Referenced by tokenizer_policy().
char_is_bracket()
int char_is_bracket (char c)
Definition at line 30 of file kest_tokenizer.c.
Referenced by tokenizer_policy().
char_is_in_string()
int char_is_in_string (char c, const char * str)
Definition at line 36 of file kest_tokenizer.c.
Referenced by token_is_number(), and tokenizer_policy().
char_is_letter()
int char_is_letter (char c)
Definition at line 15 of file kest_tokenizer.c.
Referenced by char_is_alphanumeric(), fnames_agree(), token_is_name(), and tokenizer_policy().
char_is_number()
int char_is_number (char c)
Definition at line 20 of file kest_tokenizer.c.
Referenced by char_is_alphanumeric(), token_is_name(), and tokenizer_policy().
digit_to_float()
float digit_to_float (char c)
Definition at line 151 of file kest_tokenizer.c.
Referenced by token_to_float().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (char)
kest_token_ll_advance()
int kest_token_ll_advance (kest_token_ll ** list)
Definition at line 239 of file kest_tokenizer.c.
Referenced by kest_parse_dict_list(), kest_parse_dict_val(), and kest_parse_dictionary().
kest_token_ll_safe_aappend()
int kest_token_ll_safe_aappend (kest_token_ll ** list_ptr, char * x, int line, int index)
Definition at line 333 of file kest_tokenizer.c.
Referenced by kest_token_span_to_ll(), and kest_tokenize_content().
kest_token_ll_safe_append()
int kest_token_ll_safe_append (kest_token_ll ** list_ptr, char * x, int line, int index)
Definition at line 301 of file kest_tokenizer.c.
kest_token_ll_skip_ws()
int kest_token_ll_skip_ws (kest_token_ll ** list)
Definition at line 272 of file kest_tokenizer.c.
Referenced by kest_parse_asm(), kest_parse_dict_list(), and kest_parse_dictionary().
kest_token_span_to_ll()
kest_token_ll * kest_token_span_to_ll (kest_token_ll * start, kest_token_ll * end)
Definition at line 625 of file kest_tokenizer.c.
Referenced by kest_parse_tokens().
kest_tokenize_content()
int kest_tokenize_content (kest_eff_parsing_state * ps)
Definition at line 504 of file kest_tokenizer.c.
Referenced by kest_read_eff_desc_from_file().
token_is_char()
int token_is_char (char * str, char c)
Definition at line 53 of file kest_tokenizer.c.
Referenced by get_section_start_score(), and token_is_newline().
token_is_dict_entry_seperator()
int token_is_dict_entry_seperator (char * token)
Definition at line 134 of file kest_tokenizer.c.
Referenced by kest_parse_dict_val().
token_is_int()
int token_is_int (char * token)
Definition at line 63 of file kest_tokenizer.c.
Referenced by kest_parse_asm_arg(), and kest_parse_asm_arg_2().
token_is_name()
int token_is_name (char * token)
Definition at line 215 of file kest_tokenizer.c.
Referenced by kest_parse_dictionary(), and kest_parse_expression_rec_pratt().
token_is_newline()
int token_is_newline (char * str)
Definition at line 58 of file kest_tokenizer.c.
Referenced by kest_parse_tokens().
token_is_number()
int token_is_number (char * token)
Definition at line 80 of file kest_tokenizer.c.
Referenced by kest_parse_expression_rec_pratt().
token_to_float()
float token_to_float (char * token)
Definition at line 163 of file kest_tokenizer.c.
Referenced by kest_parse_asm_arg_2(), and kest_parse_expression_rec_pratt().
tokenizer_policy()
int tokenizer_policy (char c, int * state_ptr)
Definition at line 365 of file kest_tokenizer.c.
Referenced by kest_tokenize_content().