Kestrel Interface: kest_profile_settings.c File Reference
kest_profile_settings.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int init_profile_settings_page (kest_ui_page *page)
int configure_profile_settings_page (kest_ui_page *page, void *data)
void profile_settings_save_button_cb (lv_event_t *e)
void default_profile_button_cb (lv_event_t *e)
int create_profile_settings_page_ui (kest_ui_page *page)
int free_profile_settings_page_ui (kest_ui_page *page)
int profile_settings_page_free_all (kest_ui_page *page)
int enter_profile_settings_page (kest_ui_page *page)
int enter_profile_settings_page_forward (kest_ui_page *page)
int enter_profile_settings_page_back (kest_ui_page *page)
int refresh_profile_settings_page (kest_ui_page *page)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_profile_settings.c.
Function Documentation
configure_profile_settings_page()
int configure_profile_settings_page (kest_ui_page * page, void * data)
Definition at line 45 of file kest_profile_settings.c.
Referenced by configure_profile_view(), and init_profile_settings_page().
create_profile_settings_page_ui()
int create_profile_settings_page_ui (kest_ui_page * page)
Definition at line 122 of file kest_profile_settings.c.
Referenced by init_profile_settings_page().
default_profile_button_cb()
void default_profile_button_cb (lv_event_t * e)
Definition at line 105 of file kest_profile_settings.c.
enter_profile_settings_page()
int enter_profile_settings_page (kest_ui_page * page)
Definition at line 214 of file kest_profile_settings.c.
enter_profile_settings_page_back()
int enter_profile_settings_page_back (kest_ui_page * page)
Definition at line 230 of file kest_profile_settings.c.
enter_profile_settings_page_forward()
int enter_profile_settings_page_forward (kest_ui_page * page)
Definition at line 222 of file kest_profile_settings.c.
free_profile_settings_page_ui()
int free_profile_settings_page_ui (kest_ui_page * page)
Definition at line 198 of file kest_profile_settings.c.
Referenced by init_profile_settings_page().
init_profile_settings_page()
int init_profile_settings_page (kest_ui_page * page)
Definition at line 9 of file kest_profile_settings.c.
Referenced by init_profile_view().
profile_settings_page_free_all()
int profile_settings_page_free_all (kest_ui_page * page)
Definition at line 206 of file kest_profile_settings.c.
Referenced by init_profile_settings_page().
profile_settings_save_button_cb()
void profile_settings_save_button_cb (lv_event_t * e)
Definition at line 88 of file kest_profile_settings.c.
refresh_profile_settings_page()
int refresh_profile_settings_page (kest_ui_page * page)
Definition at line 238 of file kest_profile_settings.c.
Referenced by init_profile_settings_page().