Kestrel Interface: kest_representation.c File Reference
kest_representation.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (kest_representation)
void kest_representation_pll_update_all (kest_representation_pll *reps)
int queue_representation_list_update (kest_representation_pll *reps)
kest_representation_pll * kest_representation_pll_remove (kest_representation_pll *reps, kest_representation *rep)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_representation.c.
Function Documentation
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (kest_representation)
kest_representation_pll_remove()
kest_representation_pll * kest_representation_pll_remove (kest_representation_pll * reps, kest_representation * rep)
Definition at line 74 of file kest_representation.c.
Referenced by kest_profile_remove_representation().
kest_representation_pll_update_all()
void kest_representation_pll_update_all (kest_representation_pll * reps)
Definition at line 16 of file kest_representation.c.
queue_representation_list_update()
int queue_representation_list_update (kest_representation_pll * reps)
Definition at line 57 of file kest_representation.c.
Referenced by kest_cxt_queue_save_state(), kest_effect_update_reps(), kest_profile_update_representations(), and kest_sequence_update_representations().