Kestrel Interface: kest_error_codes.c File Reference
kest_error_codes.c File Reference
#include "kest_error_codes.h"
Functions
const char * kest_error_code_to_string (int error_code)
Function Documentation
kest_error_code_to_string()
const char * kest_error_code_to_string (int error_code)
Definition at line 13 of file kest_error_codes.c.
Referenced by app_main(), kest_defs_section_extract(), kest_parse_asm(), kest_pipeline_create_fpga_transfer_batch(), kest_profile_create_fpga_transfer_batch(), kest_profile_program_fpga(), kest_profile_remove_effect(), kest_read_eff_desc_from_file(), load_effects(), main_task(), menu_item_sequence_listing_released_cb(), save_profile(), save_sequence(), and setting_widget_change_cb_inner().