Kestrel Interface: kest_fpga_encoding.h File Reference
kest_fpga_encoding.h File Reference
Macros
#define ZERO_REGISTER_ADDR 2
#define POS_ONE_REGISTER_ADDR 3
#define NEG_ONE_REGISTER_ADDR 4
#define INSTR_FORMAT_A 0
#define INSTR_FORMAT_B 1
#define NO_SHIFT 255
#define DELAY_FORMAT 8
Functions
int kest_fpga_batch_append_block_number (kest_fpga_transfer_batch *batch, int block)
uint32_t kest_block_instr_encode_resource_aware (kest_block *block, const kest_eff_resource_report *res)
int kest_fpga_batch_append_effect (kest_fpga_transfer_batch *batch, kest_effect *effect, kest_eff_resource_report *res, int *pos)
int kest_fpga_transfer_batch_append_effect_register_updates (kest_fpga_transfer_batch *batch, kest_effect_desc *eff, kest_expr_scope *scope, int pos)
int kest_fpga_batch_append_effects (kest_fpga_transfer_batch *batch, kest_effect_pll *list, kest_eff_resource_report *res, int *pos)
int kest_fpga_batch_print (kest_fpga_transfer_batch seq)
Macro Definition Documentation
DELAY_FORMAT
#define DELAY_FORMAT 8
Definition at line 13 of file kest_fpga_encoding.h.
Referenced by kest_fpga_batch_append_resource().
INSTR_FORMAT_A
#define INSTR_FORMAT_A 0
Definition at line 8 of file kest_fpga_encoding.h.
Referenced by kest_fpga_block_opcode_format().
INSTR_FORMAT_B
#define INSTR_FORMAT_B 1
Definition at line 9 of file kest_fpga_encoding.h.
Referenced by kest_fpga_block_opcode_format().
NEG_ONE_REGISTER_ADDR
#define NEG_ONE_REGISTER_ADDR 4
Definition at line 6 of file kest_fpga_encoding.h.
NO_SHIFT
#define NO_SHIFT 255
Definition at line 11 of file kest_fpga_encoding.h.
POS_ONE_REGISTER_ADDR
#define POS_ONE_REGISTER_ADDR 3
Definition at line 5 of file kest_fpga_encoding.h.
ZERO_REGISTER_ADDR
#define ZERO_REGISTER_ADDR 2
Definition at line 4 of file kest_fpga_encoding.h.
Function Documentation
kest_block_instr_encode_resource_aware()
uint32_t kest_block_instr_encode_resource_aware (kest_block * block, const kest_eff_resource_report * res)
Definition at line 60 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_block_instr().
kest_fpga_batch_append_block_number()
int kest_fpga_batch_append_block_number (kest_fpga_transfer_batch * batch, int block)
Definition at line 100 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_block_instr(), kest_fpga_batch_append_block_register_updates(), and kest_fpga_batch_append_block_regs().
kest_fpga_batch_append_effect()
int kest_fpga_batch_append_effect (kest_fpga_transfer_batch * batch, kest_effect * effect, kest_eff_resource_report * res, int * pos)
Definition at line 338 of file kest_fpga_encoding.c.
Referenced by kest_fpga_batch_append_effects().
kest_fpga_batch_append_effects()
int kest_fpga_batch_append_effects (kest_fpga_transfer_batch * batch, kest_effect_pll * list, kest_eff_resource_report * res, int * pos)
Definition at line 360 of file kest_fpga_encoding.c.
Referenced by kest_pipeline_create_fpga_transfer_batch().
kest_fpga_batch_print()
int kest_fpga_batch_print (kest_fpga_transfer_batch seq)
Definition at line 496 of file kest_fpga_encoding.c.
Referenced by kest_fpga_comms_task().
kest_fpga_transfer_batch_append_effect_register_updates()
int kest_fpga_transfer_batch_append_effect_register_updates (kest_fpga_transfer_batch * batch, kest_effect_desc * eff, kest_expr_scope * scope, int pos)
Definition at line 196 of file kest_fpga_encoding.c.
Referenced by kest_effect_update_fpga_registers().