Kestrel Interface: kest_fpga_comms.h File Reference
kest_fpga_comms.h File Reference
Macros
#define PRINT_TRANSFER_BATCHES
Functions
void kest_fpga_comms_task (void *param)
int kest_fpga_queue_transfer_batch (kest_fpga_transfer_batch batch)
int kest_fpga_queue_program_batch (kest_fpga_transfer_batch batch)
int kest_fpga_queue_input_gain_set (float gain_db)
int kest_fpga_queue_output_gain_set (float gain_db)
int kest_fpga_queue_register_commit ()
Macro Definition Documentation
PRINT_TRANSFER_BATCHES
#define PRINT_TRANSFER_BATCHES
Definition at line 4 of file kest_fpga_comms.h.
Function Documentation
kest_fpga_comms_task()
void kest_fpga_comms_task (void * param)
Definition at line 32 of file kest_fpga_comms.c.
Referenced by app_main(), and main_task().
kest_fpga_queue_input_gain_set()
int kest_fpga_queue_input_gain_set (float gain_db)
Definition at line 152 of file kest_fpga_comms.c.
kest_fpga_queue_output_gain_set()
int kest_fpga_queue_output_gain_set (float gain_db)
Definition at line 162 of file kest_fpga_comms.c.
kest_fpga_queue_program_batch()
int kest_fpga_queue_program_batch (kest_fpga_transfer_batch batch)
Definition at line 139 of file kest_fpga_comms.c.
Referenced by kest_profile_program_fpga().
kest_fpga_queue_register_commit()
int kest_fpga_queue_register_commit ()
Definition at line 172 of file kest_fpga_comms.c.
kest_fpga_queue_transfer_batch()
int kest_fpga_queue_transfer_batch (kest_fpga_transfer_batch batch)
Definition at line 127 of file kest_fpga_comms.c.
Referenced by kest_effect_update_fpga_registers().