Kestrel Interface: kest_button.c File Reference
kest_button.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (kest_active_button)
int init_button (kest_button *button)
kest_button * new_button (const char *label)
int create_button_ui (kest_button *button, lv_obj_t *parent)
int kest_button_create_label_ui (kest_button *button)
int button_set_clicked_cb (kest_button *button, lv_event_cb_t cb, void *cb_arg)
int button_set_pressing_cb (kest_button *button, lv_event_cb_t cb, void *cb_arg)
int button_set_long_pressed_cb (kest_button *button, lv_event_cb_t cb, void *cb_arg)
int button_set_released_cb (kest_button *button, lv_event_cb_t cb, void *cb_arg)
int kest_button_set_label (kest_button *button, const char *label)
int kest_button_disable_alignment (kest_button *button)
int kest_button_set_alignment (kest_button *button, lv_align_t align, int offs_x, int offs_y)
int kest_button_set_size (kest_button *button, int width, int height)
int kest_button_add_sub_button (kest_button *button, kest_button *sub_button)
int kest_button_hide (kest_button *button)
int kest_button_unhide (kest_button *button)
int kest_button_set_clickable (kest_button *button)
int kest_button_set_unclickable (kest_button *button)
int kest_button_set_opacity (kest_button *button, int opacity)
int kest_button_enable (kest_button *button)
int kest_button_disable (kest_button *button)
int kest_button_reset_state (kest_button *button)
int kest_button_delete_ui (kest_button *button)
int init_danger_button (kest_danger_button *button, void(*action_cb)(void *data), void *cb_arg, kest_ui_page *parent)
int kest_danger_button_create_ui (kest_danger_button *button, lv_obj_t *parent)
void kest_danger_button_confirm_cb (lv_event_t *e)
void kest_danger_button_cancel_cb (lv_event_t *e)
void kest_danger_button_value_changed_cb (lv_event_t *e)
void kest_danger_button_activate_popup_cb (lv_event_t *e)
void kest_active_button_scale_cb (void *data, int32_t value)
void kest_active_button_glide_cb (void *data, int32_t value)
void kest_active_button_del_button_fade_cb (void *data, int32_t value)
void kest_active_button_del_button_faded_out_cb (lv_anim_t *anim)
void kest_active_button_delete_anim_cb (void *data, int32_t value)
void kest_active_button_trigger_scale_anim (kest_active_button *button, int direction)
void kest_active_button_trigger_glide_anim (kest_active_button *button, int32_t new_pos_y)
void kest_active_button_trigger_del_button_fade_in (kest_active_button *button)
void kest_active_button_trigger_del_button_fade_out (kest_active_button *button)
void kest_active_button_delete_anim_ready_cb (lv_anim_t *anim)
void kest_active_button_trigger_delete_anim (kest_active_button *button)
int kest_active_button_force_index (kest_active_button *button, int i)
int kest_active_button_set_index (kest_active_button *button, int i)
void kest_active_button_del_button_remain_timer_cb (lv_timer_t *timer)
void kest_active_button_clicked_cb (lv_event_t *e)
void kest_active_button_long_pressed_cb (lv_event_t *e)
void kest_active_button_pressing_cb (lv_event_t *e)
void kest_active_button_release_cb (lv_event_t *e)
void kest_active_button_del_cb (lv_event_t *e)
int kest_active_button_init (kest_active_button *button)
int kest_active_button_add_del_button (kest_active_button *button)
void kest_active_button_set_representation (kest_active_button *button, void *representer, void *representee, void(*update)(void *, void *))
int kest_active_button_create_ui (kest_active_button *button, lv_obj_t *parent)
void kest_active_button_free (kest_active_button *button)
int kest_active_button_change_label (kest_active_button *button, char *text)
int kest_active_button_set_dimensions (kest_active_button *button, int w, int h)
int kest_active_button_swap_del_button_for_persistent_unclickable (kest_active_button *button, const char *label)
int kest_active_button_reset_del_button (kest_active_button *button)
int kest_active_button_array_init (kest_active_button_array *array)
int kest_active_button_array_set_length (kest_active_button_array *array, int n)
kest_active_button_array * kest_active_button_array_new ()
kest_active_button * kest_active_button_array_append_new (kest_active_button_array *array, void *data, char *label)
int kest_active_button_array_append (kest_active_button *button, kest_active_button_array *array)
int kest_active_button_array_remove (kest_active_button_array *array, int index)
int kest_active_button_array_index_y_position (kest_active_button_array *array, int index)
int kest_active_button_array_create_ui (kest_active_button_array *array, lv_obj_t *parent)
int kest_active_button_array_set_dimensions (kest_active_button_array *array, int w, int h)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_button.c.
Function Documentation
button_set_clicked_cb()
int button_set_clicked_cb (kest_button * button, lv_event_cb_t cb, void * cb_arg)
Definition at line 158 of file kest_button.c.
Referenced by configure_main_menu(), init_danger_button(), kest_active_button_add_del_button(), kest_active_button_init(), ui_page_add_back_button(), ui_page_add_bottom_button(), ui_page_add_left_panel_button(), ui_page_add_parent_button(), and ui_page_add_right_panel_button().
button_set_long_pressed_cb()
int button_set_long_pressed_cb (kest_button * button, lv_event_cb_t cb, void * cb_arg)
Definition at line 186 of file kest_button.c.
Referenced by kest_active_button_init().
button_set_pressing_cb()
int button_set_pressing_cb (kest_button * button, lv_event_cb_t cb, void * cb_arg)
Definition at line 172 of file kest_button.c.
Referenced by kest_active_button_init().
button_set_released_cb()
int button_set_released_cb (kest_button * button, lv_event_cb_t cb, void * cb_arg)
Definition at line 200 of file kest_button.c.
Referenced by kest_active_button_init().
create_button_ui()
int create_button_ui (kest_button * button, lv_obj_t * parent)
Definition at line 68 of file kest_button.c.
Referenced by create_button_ui(), create_main_menu_ui(), kest_active_button_create_ui(), kest_danger_button_create_ui(), ui_page_create_bottom_buttons(), and ui_page_create_panel_ui().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (kest_active_button)
init_button()
int init_button (kest_button * button)
Definition at line 11 of file kest_button.c.
Referenced by configure_main_menu(), init_danger_button(), kest_active_button_add_del_button(), kest_active_button_init(), and new_button().
init_danger_button()
int init_danger_button (kest_danger_button * button, void(* action_cb)(void *data), void * cb_arg, kest_ui_page * parent)
Definition at line 461 of file kest_button.c.
Referenced by configure_main_menu().
kest_active_button_add_del_button()
int kest_active_button_add_del_button (kest_active_button * button)
Definition at line 1025 of file kest_button.c.
Referenced by kest_active_button_array_append_new().
kest_active_button_array_append()
int kest_active_button_array_append (kest_active_button * button, kest_active_button_array * array)
Definition at line 1331 of file kest_button.c.
Referenced by kest_active_button_array_append_new().
kest_active_button_array_append_new()
kest_active_button * kest_active_button_array_append_new (kest_active_button_array * array, void * data, char * label)
Definition at line 1290 of file kest_button.c.
Referenced by configure_profile_view(), configure_sequence_view(), init_test_page(), profile_view_append_effect(), and seq_plus_cb().
kest_active_button_array_create_ui()
int kest_active_button_array_create_ui (kest_active_button_array * array, lv_obj_t * parent)
Definition at line 1382 of file kest_button.c.
Referenced by create_profile_view_ui(), create_sequence_view_ui(), and create_test_page_ui().
kest_active_button_array_index_y_position()
int kest_active_button_array_index_y_position (kest_active_button_array * array, int index)
Definition at line 1377 of file kest_button.c.
Referenced by kest_active_button_array_append(), kest_active_button_force_index(), and kest_active_button_set_index().
kest_active_button_array_init()
int kest_active_button_array_init (kest_active_button_array * array)
Definition at line 1229 of file kest_button.c.
Referenced by kest_active_button_array_new().
kest_active_button_array_new()
kest_active_button_array * kest_active_button_array_new ()
Definition at line 1278 of file kest_button.c.
Referenced by init_profile_view(), init_sequence_view(), and init_test_page().
kest_active_button_array_remove()
int kest_active_button_array_remove (kest_active_button_array * array, int index)
Definition at line 1356 of file kest_button.c.
Referenced by kest_active_button_delete_anim_ready_cb().
kest_active_button_array_set_dimensions()
int kest_active_button_array_set_dimensions (kest_active_button_array * array, int w, int h)
Definition at line 1398 of file kest_button.c.
kest_active_button_array_set_length()
int kest_active_button_array_set_length (kest_active_button_array * array, int n)
Definition at line 1258 of file kest_button.c.
Referenced by init_profile_view(), init_sequence_view(), and init_test_page().
kest_active_button_change_label()
int kest_active_button_change_label (kest_active_button * button, char * text)
Definition at line 1132 of file kest_button.c.
Referenced by sequence_view_profile_button_rep_update().
kest_active_button_clicked_cb()
void kest_active_button_clicked_cb (lv_event_t * e)
Definition at line 779 of file kest_button.c.
Referenced by kest_active_button_init().
kest_active_button_create_ui()
int kest_active_button_create_ui (kest_active_button * button, lv_obj_t * parent)
Definition at line 1067 of file kest_button.c.
Referenced by kest_active_button_array_create_ui(), profile_view_append_effect(), and seq_plus_cb().
kest_active_button_del_button_fade_cb()
void kest_active_button_del_button_fade_cb (void * data, int32_t value)
Definition at line 599 of file kest_button.c.
Referenced by kest_active_button_reset_del_button(), kest_active_button_swap_del_button_for_persistent_unclickable(), kest_active_button_trigger_del_button_fade_in(), and kest_active_button_trigger_del_button_fade_out().
kest_active_button_del_button_faded_out_cb()
void kest_active_button_del_button_faded_out_cb (lv_anim_t * anim)
Definition at line 616 of file kest_button.c.
Referenced by kest_active_button_trigger_del_button_fade_out().
kest_active_button_del_button_remain_timer_cb()
void kest_active_button_del_button_remain_timer_cb (lv_timer_t * timer)
Definition at line 771 of file kest_button.c.
Referenced by kest_active_button_release_cb().
kest_active_button_del_cb()
void kest_active_button_del_cb (lv_event_t * e)
Definition at line 984 of file kest_button.c.
Referenced by kest_active_button_add_del_button().
kest_active_button_delete_anim_cb()
void kest_active_button_delete_anim_cb (void * data, int32_t value)
Definition at line 629 of file kest_button.c.
Referenced by kest_active_button_trigger_delete_anim().
kest_active_button_delete_anim_ready_cb()
void kest_active_button_delete_anim_ready_cb (lv_anim_t * anim)
Definition at line 712 of file kest_button.c.
Referenced by kest_active_button_trigger_delete_anim().
kest_active_button_force_index()
int kest_active_button_force_index (kest_active_button * button, int i)
Definition at line 734 of file kest_button.c.
Referenced by kest_active_button_release_cb().
kest_active_button_free()
void kest_active_button_free (kest_active_button * button)
Definition at line 1108 of file kest_button.c.
Referenced by kest_active_button_delete_anim_ready_cb().
kest_active_button_glide_cb()
void kest_active_button_glide_cb (void * data, int32_t value)
Definition at line 588 of file kest_button.c.
Referenced by kest_active_button_trigger_glide_anim().
kest_active_button_init()
int kest_active_button_init (kest_active_button * button)
Definition at line 999 of file kest_button.c.
Referenced by kest_active_button_array_append_new().
kest_active_button_long_pressed_cb()
void kest_active_button_long_pressed_cb (lv_event_t * e)
Definition at line 802 of file kest_button.c.
Referenced by kest_active_button_init().
kest_active_button_pressing_cb()
void kest_active_button_pressing_cb (lv_event_t * e)
Definition at line 861 of file kest_button.c.
Referenced by kest_active_button_init().
kest_active_button_release_cb()
void kest_active_button_release_cb (lv_event_t * e)
Definition at line 938 of file kest_button.c.
Referenced by kest_active_button_init().
kest_active_button_reset_del_button()
int kest_active_button_reset_del_button (kest_active_button * button)
Definition at line 1184 of file kest_button.c.
Referenced by sequence_view_profile_button_rep_update().
kest_active_button_scale_cb()
void kest_active_button_scale_cb (void * data, int32_t value)
Definition at line 567 of file kest_button.c.
Referenced by kest_active_button_trigger_scale_anim().
kest_active_button_set_dimensions()
int kest_active_button_set_dimensions (kest_active_button * button, int w, int h)
Definition at line 1142 of file kest_button.c.
Referenced by kest_active_button_array_set_dimensions().
kest_active_button_set_index()
int kest_active_button_set_index (kest_active_button * button, int i)
Definition at line 751 of file kest_button.c.
Referenced by kest_active_button_array_remove(), and kest_active_button_pressing_cb().
kest_active_button_set_representation()
void kest_active_button_set_representation (kest_active_button * button, void * representer, void * representee, void(* update)(void *, void *))
Definition at line 1057 of file kest_button.c.
Referenced by configure_sequence_view(), and seq_plus_cb().
kest_active_button_swap_del_button_for_persistent_unclickable()
int kest_active_button_swap_del_button_for_persistent_unclickable (kest_active_button * button, const char * label)
Definition at line 1155 of file kest_button.c.
Referenced by sequence_view_profile_button_rep_update().
kest_active_button_trigger_del_button_fade_in()
void kest_active_button_trigger_del_button_fade_in (kest_active_button * button)
Definition at line 674 of file kest_button.c.
Referenced by kest_active_button_long_pressed_cb().
kest_active_button_trigger_del_button_fade_out()
void kest_active_button_trigger_del_button_fade_out (kest_active_button * button)
Definition at line 697 of file kest_button.c.
Referenced by kest_active_button_del_button_remain_timer_cb().
kest_active_button_trigger_delete_anim()
void kest_active_button_trigger_delete_anim (kest_active_button * button)
Definition at line 720 of file kest_button.c.
Referenced by kest_active_button_del_cb().
kest_active_button_trigger_glide_anim()
void kest_active_button_trigger_glide_anim (kest_active_button * button, int32_t new_pos_y)
Definition at line 659 of file kest_button.c.
Referenced by kest_active_button_force_index(), and kest_active_button_set_index().
kest_active_button_trigger_scale_anim()
void kest_active_button_trigger_scale_anim (kest_active_button * button, int direction)
Definition at line 639 of file kest_button.c.
Referenced by kest_active_button_long_pressed_cb(), and kest_active_button_release_cb().
kest_button_add_sub_button()
int kest_button_add_sub_button (kest_button * button, kest_button * sub_button)
Definition at line 274 of file kest_button.c.
Referenced by kest_active_button_add_del_button().
kest_button_create_label_ui()
int kest_button_create_label_ui (kest_button * button)
Definition at line 144 of file kest_button.c.
Referenced by kest_active_button_reset_del_button(), kest_active_button_swap_del_button_for_persistent_unclickable(), and kest_button_set_label().
kest_button_delete_ui()
int kest_button_delete_ui (kest_button * button)
Definition at line 434 of file kest_button.c.
Referenced by kest_active_button_free(), and kest_button_delete_ui().
kest_button_disable()
int kest_button_disable (kest_button * button)
Definition at line 401 of file kest_button.c.
Referenced by configure_profile_view(), create_profile_view_ui(), create_sequence_view_ui(), profile_view_rep_update(), and sequence_view_rep_update().
kest_button_disable_alignment()
int kest_button_disable_alignment (kest_button * button)
Definition at line 233 of file kest_button.c.
Referenced by configure_main_menu().
kest_button_enable()
int kest_button_enable (kest_button * button)
Definition at line 388 of file kest_button.c.
Referenced by profile_view_rep_update(), profile_view_save_name(), sequence_view_rep_update(), and sequence_view_set_name().
kest_button_hide()
int kest_button_hide (kest_button * button)
Definition at line 287 of file kest_button.c.
Referenced by kest_active_button_add_del_button(), kest_active_button_del_button_faded_out_cb(), and kest_active_button_reset_del_button().
kest_button_reset_state()
int kest_button_reset_state (kest_button * button)
Definition at line 419 of file kest_button.c.
Referenced by kest_active_button_reset_del_button(), and kest_active_button_swap_del_button_for_persistent_unclickable().
kest_button_set_alignment()
int kest_button_set_alignment (kest_button * button, lv_align_t align, int offs_x, int offs_y)
Definition at line 243 of file kest_button.c.
Referenced by kest_active_button_add_del_button(), and kest_active_button_array_append().
kest_button_set_clickable()
int kest_button_set_clickable (kest_button * button)
Definition at line 332 of file kest_button.c.
Referenced by kest_active_button_reset_del_button().
kest_button_set_label()
int kest_button_set_label (kest_button * button, const char * label)
Definition at line 214 of file kest_button.c.
Referenced by configure_main_menu(), kest_active_button_add_del_button(), kest_active_button_change_label(), kest_active_button_reset_del_button(), and kest_active_button_swap_del_button_for_persistent_unclickable().
kest_button_set_opacity()
int kest_button_set_opacity (kest_button * button, int opacity)
Definition at line 360 of file kest_button.c.
Referenced by kest_active_button_del_button_fade_cb(), kest_active_button_delete_anim_cb(), and kest_active_button_swap_del_button_for_persistent_unclickable().
kest_button_set_size()
int kest_button_set_size (kest_button * button, int width, int height)
Definition at line 260 of file kest_button.c.
Referenced by kest_active_button_add_del_button(), kest_active_button_array_append(), and kest_active_button_set_dimensions().
kest_button_set_unclickable()
int kest_button_set_unclickable (kest_button * button)
Definition at line 347 of file kest_button.c.
Referenced by kest_active_button_swap_del_button_for_persistent_unclickable().
kest_button_unhide()
int kest_button_unhide (kest_button * button)
Definition at line 309 of file kest_button.c.
Referenced by kest_active_button_swap_del_button_for_persistent_unclickable(), kest_active_button_trigger_del_button_fade_in(), and kest_active_button_trigger_del_button_fade_out().
kest_danger_button_activate_popup_cb()
void kest_danger_button_activate_popup_cb (lv_event_t * e)
Definition at line 531 of file kest_button.c.
Referenced by init_danger_button().
kest_danger_button_cancel_cb()
void kest_danger_button_cancel_cb (lv_event_t * e)
Definition at line 497 of file kest_button.c.
Referenced by kest_danger_button_activate_popup_cb().
kest_danger_button_confirm_cb()
void kest_danger_button_confirm_cb (lv_event_t * e)
Definition at line 489 of file kest_button.c.
Referenced by kest_danger_button_activate_popup_cb().
kest_danger_button_create_ui()
int kest_danger_button_create_ui (kest_danger_button * button, lv_obj_t * parent)
Definition at line 479 of file kest_button.c.
Referenced by create_main_menu_ui().
kest_danger_button_value_changed_cb()
void kest_danger_button_value_changed_cb (lv_event_t * e)
Definition at line 507 of file kest_button.c.
new_button()
kest_button * new_button (const char * label)
Definition at line 54 of file kest_button.c.
Referenced by kest_active_button_add_del_button(), ui_page_add_back_button(), ui_page_add_bottom_button(), ui_page_add_left_panel_button(), ui_page_add_parent_button(), and ui_page_add_right_panel_button().