Kestrel Interface: kest_effect_settings.c File Reference
kest_effect_settings.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int init_effect_settings_page (kest_ui_page *page)
int configure_effect_settings_page (kest_ui_page *page, void *data)
void band_control_value_changed_cb (lv_event_t *e)
int create_effect_settings_page_ui (kest_ui_page *page)
int refresh_effect_settings_page (kest_ui_page *page)
int free_effect_settings_page_ui (kest_ui_page *page)
int effect_settings_page_free_all (kest_ui_page *page)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_effect_settings.c.
Function Documentation
band_control_value_changed_cb()
void band_control_value_changed_cb (lv_event_t * e)
Definition at line 85 of file kest_effect_settings.c.
Referenced by create_effect_settings_page_ui().
configure_effect_settings_page()
int configure_effect_settings_page (kest_ui_page * page, void * data)
Definition at line 48 of file kest_effect_settings.c.
Referenced by configure_effect_view(), and init_effect_settings_page().
create_effect_settings_page_ui()
int create_effect_settings_page_ui (kest_ui_page * page)
Definition at line 137 of file kest_effect_settings.c.
Referenced by create_effect_view_ui(), and init_effect_settings_page().
effect_settings_page_free_all()
int effect_settings_page_free_all (kest_ui_page * page)
Definition at line 276 of file kest_effect_settings.c.
free_effect_settings_page_ui()
int free_effect_settings_page_ui (kest_ui_page * page)
Definition at line 265 of file kest_effect_settings.c.
init_effect_settings_page()
int init_effect_settings_page (kest_ui_page * page)
Definition at line 9 of file kest_effect_settings.c.
Referenced by init_effect_view().
refresh_effect_settings_page()
int refresh_effect_settings_page (kest_ui_page * page)
Definition at line 182 of file kest_effect_settings.c.
Referenced by band_control_value_changed_cb(), and create_effect_settings_page_ui().