Kestrel Interface: kest_state.c File Reference
kest_state.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int kest_cxt_clone_state (kest_context *cxt, kest_state *state)
void kest_state_representation_update (void *representer, void *representee)
int kest_cxt_restore_state (kest_context *cxt, kest_state *state)
int kest_cxt_enter_previous_current_page (kest_context *cxt, kest_state *state)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_state.c.
Function Documentation
kest_cxt_clone_state()
int kest_cxt_clone_state (kest_context * cxt, kest_state * state)
Definition at line 13 of file kest_state.c.
Referenced by kest_state_representation_update().
kest_cxt_enter_previous_current_page()
int kest_cxt_enter_previous_current_page (kest_context * cxt, kest_state * state)
Definition at line 120 of file kest_state.c.
Referenced by app_main().
kest_cxt_restore_state()
int kest_cxt_restore_state (kest_context * cxt, kest_state * state)
Definition at line 94 of file kest_state.c.
Referenced by app_main(), and main_task().
kest_state_representation_update()
void kest_state_representation_update (void * representer, void * representee)
Definition at line 65 of file kest_state.c.
Referenced by kest_init_context().