Kestrel Interface: kest_context.h File Reference
kest_context.h File Reference
Data Structures
struct kest_context
Macros
#define MAX_N_PROFILES 256
#define CONTEXT_PROFILE_ID 0xFFFF
#define INPUT_GAIN_PID 0x0000
#define OUTPUT_GAIN_PID 0x0001
Typedefs
typedef kest_profile_pll profile_ll
Functions
int kest_init_context (kest_context *cxt)
int kest_context_init_effect_list (kest_context *cxt)
int kest_context_init_main_sequence (kest_context *cxt)
int kest_context_init_ui (kest_context *cxt)
int kest_context_enlarge_profile_array (kest_context *cxt)
int kest_context_set_n_profiles (kest_context *cxt, int n)
int kest_context_add_profile (kest_context *cxt)
kest_profile * kest_context_add_profile_rp (kest_context *cxt)
kest_sequence * kest_context_add_sequence_rp (kest_context *cxt)
kest_profile * cxt_get_profile_by_id (kest_context *cxt, uint16_t profile_id)
kest_effect * cxt_get_effect_by_id (kest_context *cxt, uint16_t profile_id, uint16_t effect_id)
kest_parameter * cxt_get_parameter_by_id (kest_context *cxt, uint16_t profile_id, uint16_t effect_id, uint16_t parameter_id)
int cxt_get_parameter_and_effect_by_id (kest_context *cxt, kest_parameter_id id, kest_parameter **pp, kest_effect **tp)
kest_setting * cxt_get_setting_by_id (kest_context *cxt, uint16_t profile_id, uint16_t effect_id, uint16_t parameter_id)
kest_profile * cxt_get_profile_by_fname (kest_context *cxt, const char *fname)
kest_sequence * cxt_get_sequence_by_fname (kest_context *cxt, const char *fname)
int cxt_effect_id_to_position (kest_context *cxt, uint16_t profile_id, uint16_t effect_id)
int cxt_effect_position_to_id (kest_context *cxt, uint16_t profile_id, uint16_t effect_pos)
int cxt_remove_effect (kest_context *cxt, uint16_t pid, uint16_t tid)
int cxt_remove_profile (kest_context *cxt, kest_profile *profile)
int cxt_remove_sequence (kest_context *cxt, kest_sequence *sequence)
int set_active_profile (kest_profile *profile)
int set_active_profile_from_sequence (kest_profile *profile)
int set_working_profile (kest_profile *profile)
int context_no_default_profile (kest_context *cxt)
int resolve_default_profile (kest_context *cxt)
int set_profile_as_default (kest_context *cxt, kest_profile *profile)
int cxt_save_all_profiles (kest_context *cxt)
void context_print_profiles (kest_context *cxt)
int cxt_set_all_profiles_left_button_to_main_menu (kest_context *cxt)
int cxt_handle_hw_switch (kest_context *cxt, int sw)
kest_profile * cxt_find_profile (kest_context *cxt, const char *fname)
int kest_cxt_obtain_mutex (kest_context *cxt)
int kest_cxt_release_mutex (kest_context *cxt)
int kest_cxt_queue_save_state (kest_context *cxt)
int kest_cxt_set_input_gain (kest_context *cxt, float gain)
int kest_cxt_set_output_gain (kest_context *cxt, float gain)
kest_effect_desc * kest_cxt_get_effect_desc_from_cname (kest_context *cxt, const char *cname)
Macro Definition Documentation
CONTEXT_PROFILE_ID
#define CONTEXT_PROFILE_ID 0xFFFF
Definition at line 6 of file kest_context.h.
Referenced by cxt_get_parameter_and_effect_by_id(), kest_init_context(), and parameter_widget_change_cb_inner().
INPUT_GAIN_PID
#define INPUT_GAIN_PID 0x0000
Definition at line 7 of file kest_context.h.
Referenced by cxt_get_parameter_and_effect_by_id(), and kest_init_context().
MAX_N_PROFILES
#define MAX_N_PROFILES 256
Definition at line 4 of file kest_context.h.
OUTPUT_GAIN_PID
#define OUTPUT_GAIN_PID 0x0001
Definition at line 8 of file kest_context.h.
Referenced by cxt_get_parameter_and_effect_by_id(), and kest_init_context().
Typedef Documentation
profile_ll
typedef kest_profile_pll profile_ll
Definition at line 10 of file kest_context.h.
Function Documentation
context_no_default_profile()
int context_no_default_profile (kest_context * cxt)
context_print_profiles()
void context_print_profiles (kest_context * cxt)
Definition at line 537 of file kest_context.c.
Referenced by app_main().
cxt_effect_id_to_position()
int cxt_effect_id_to_position (kest_context * cxt, uint16_t profile_id, uint16_t effect_id)
Definition at line 323 of file kest_context.c.
cxt_effect_position_to_id()
int cxt_effect_position_to_id (kest_context * cxt, uint16_t profile_id, uint16_t effect_pos)
Definition at line 348 of file kest_context.c.
cxt_find_profile()
kest_profile * cxt_find_profile (kest_context * cxt, const char * fname)
Definition at line 620 of file kest_context.c.
cxt_get_effect_by_id()
kest_effect * cxt_get_effect_by_id (kest_context * cxt, uint16_t profile_id, uint16_t effect_id)
Definition at line 220 of file kest_context.c.
Referenced by cxt_get_parameter_and_effect_by_id(), cxt_get_parameter_by_id(), and cxt_get_setting_by_id().
cxt_get_parameter_and_effect_by_id()
int cxt_get_parameter_and_effect_by_id (kest_context * cxt, kest_parameter_id id, kest_parameter ** pp, kest_effect ** tp)
Definition at line 259 of file kest_context.c.
cxt_get_parameter_by_id()
kest_parameter * cxt_get_parameter_by_id (kest_context * cxt, uint16_t profile_id, uint16_t effect_id, uint16_t parameter_id)
Definition at line 246 of file kest_context.c.
cxt_get_profile_by_fname()
kest_profile * cxt_get_profile_by_fname (kest_context * cxt, const char * fname)
Definition at line 721 of file kest_context.c.
Referenced by kest_cxt_restore_state(), kest_page_id_find_page(), and read_sequence_from_file().
cxt_get_profile_by_id()
kest_profile * cxt_get_profile_by_id (kest_context * cxt, uint16_t profile_id)
Definition at line 200 of file kest_context.c.
Referenced by cxt_effect_id_to_position(), cxt_effect_position_to_id(), cxt_get_effect_by_id(), cxt_remove_effect(), and sw_field_save_cb().
cxt_get_sequence_by_fname()
kest_sequence * cxt_get_sequence_by_fname (kest_context * cxt, const char * fname)
Definition at line 756 of file kest_context.c.
Referenced by kest_page_id_find_page().
cxt_get_setting_by_id()
kest_setting * cxt_get_setting_by_id (kest_context * cxt, uint16_t profile_id, uint16_t effect_id, uint16_t parameter_id)
Definition at line 310 of file kest_context.c.
cxt_handle_hw_switch()
int cxt_handle_hw_switch (kest_context * cxt, int sw)
Definition at line 602 of file kest_context.c.
Referenced by footswitch_task().
cxt_remove_effect()
int cxt_remove_effect (kest_context * cxt, uint16_t pid, uint16_t tid)
Definition at line 456 of file kest_context.c.
cxt_remove_profile()
int cxt_remove_profile (kest_context * cxt, kest_profile * profile)
Definition at line 378 of file kest_context.c.
Referenced by profile_listing_delete_button_cb().
cxt_remove_sequence()
int cxt_remove_sequence (kest_context * cxt, kest_sequence * sequence)
Definition at line 419 of file kest_context.c.
Referenced by sequence_listing_delete_button_cb().
cxt_save_all_profiles()
int cxt_save_all_profiles (kest_context * cxt)
Definition at line 647 of file kest_context.c.
Referenced by seq_save_cb().
cxt_set_all_profiles_left_button_to_main_menu()
int cxt_set_all_profiles_left_button_to_main_menu (kest_context * cxt)
Definition at line 582 of file kest_context.c.
kest_context_add_profile()
int kest_context_add_profile (kest_context * cxt)
Definition at line 114 of file kest_context.c.
kest_context_add_profile_rp()
kest_profile * kest_context_add_profile_rp (kest_context * cxt)
Definition at line 141 of file kest_context.c.
Referenced by create_new_profile_with_teensy().
kest_context_add_sequence_rp()
kest_sequence * kest_context_add_sequence_rp (kest_context * cxt)
Definition at line 175 of file kest_context.c.
Referenced by sequence_list_add_cb().
kest_context_enlarge_profile_array()
int kest_context_enlarge_profile_array (kest_context * cxt)
kest_context_init_effect_list()
int kest_context_init_effect_list (kest_context * cxt)
Definition at line 94 of file kest_context.c.
Referenced by app_main(), and main_task().
kest_context_init_main_sequence()
int kest_context_init_main_sequence (kest_context * cxt)
Definition at line 67 of file kest_context.c.
Referenced by kest_init_context().
kest_context_init_ui()
int kest_context_init_ui (kest_context * cxt)
Definition at line 103 of file kest_context.c.
kest_context_set_n_profiles()
int kest_context_set_n_profiles (kest_context * cxt, int n)
kest_cxt_get_effect_desc_from_cname()
kest_effect_desc * kest_cxt_get_effect_desc_from_cname (kest_context * cxt, const char * cname)
Definition at line 797 of file kest_context.c.
Referenced by read_profile_from_file().
kest_cxt_obtain_mutex()
int kest_cxt_obtain_mutex (kest_context * cxt)
Definition at line 667 of file kest_context.c.
Referenced by kest_cxt_clone_state().
kest_cxt_queue_save_state()
int kest_cxt_queue_save_state (kest_context * cxt)
Definition at line 711 of file kest_context.c.
Referenced by enter_ui_page(), enter_ui_page_backwards(), and enter_ui_page_forwards().
kest_cxt_release_mutex()
int kest_cxt_release_mutex (kest_context * cxt)
Definition at line 697 of file kest_context.c.
Referenced by kest_cxt_clone_state().
kest_cxt_set_input_gain()
int kest_cxt_set_input_gain (kest_context * cxt, float gain)
Definition at line 774 of file kest_context.c.
Referenced by kest_cxt_restore_state().
kest_cxt_set_output_gain()
int kest_cxt_set_output_gain (kest_context * cxt, float gain)
Definition at line 786 of file kest_context.c.
Referenced by kest_cxt_restore_state().
kest_init_context()
int kest_init_context (kest_context * cxt)
Definition at line 12 of file kest_context.c.
Referenced by app_main(), and main_task().
resolve_default_profile()
int resolve_default_profile (kest_context * cxt)
set_active_profile()
int set_active_profile (kest_profile * profile)
Definition at line 473 of file kest_context.c.
Referenced by profile_view_play_button_cb().
set_active_profile_from_sequence()
int set_active_profile_from_sequence (kest_profile * profile)
Definition at line 502 of file kest_context.c.
Referenced by kest_cxt_restore_state(), kest_sequence_advance(), kest_sequence_begin(), kest_sequence_begin_at(), kest_sequence_regress(), and kest_sequence_stop().
set_profile_as_default()
int set_profile_as_default (kest_context * cxt, kest_profile * profile)
set_working_profile()
int set_working_profile (kest_profile * profile)
Definition at line 524 of file kest_context.c.