Kestrel Interface: kest_effect_init.c File Reference
kest_effect_init.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int init_3_band_eq (kest_effect *effect)
int init_amplifier (kest_effect *effect)
int init_band_pass_filter (kest_effect *effect)
int init_compressor (kest_effect *effect)
int init_delay (kest_effect *effect)
int init_dirty_octave (kest_effect *effect)
int init_distortion (kest_effect *effect)
int init_envelope (kest_effect *effect)
int init_flanger (kest_effect *effect)
int init_high_pass_filter (kest_effect *effect)
int init_low_end_compressor (kest_effect *effect)
int init_low_pass_filter (kest_effect *effect)
int init_noise_suppressor (kest_effect *effect)
int init_percussifier (kest_effect *effect)
int init_warbler (kest_effect *effect)
int init_effect_of_type (kest_effect *effect, uint16_t type)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_effect_init.c.
Function Documentation
init_3_band_eq()
int init_3_band_eq (kest_effect * effect)
Definition at line 14 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_amplifier()
int init_amplifier (kest_effect * effect)
Definition at line 76 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_band_pass_filter()
int init_band_pass_filter (kest_effect * effect)
Definition at line 134 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_compressor()
int init_compressor (kest_effect * effect)
Definition at line 180 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_delay()
int init_delay (kest_effect * effect)
Definition at line 258 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_dirty_octave()
int init_dirty_octave (kest_effect * effect)
Definition at line 342 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_distortion()
int init_distortion (kest_effect * effect)
Definition at line 372 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_effect_of_type()
int init_effect_of_type (kest_effect * effect, uint16_t type)
Definition at line 1209 of file kest_effect_init.c.
init_envelope()
int init_envelope (kest_effect * effect)
Definition at line 484 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_flanger()
int init_flanger (kest_effect * effect)
Definition at line 594 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_high_pass_filter()
int init_high_pass_filter (kest_effect * effect)
Definition at line 709 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_low_end_compressor()
int init_low_end_compressor (kest_effect * effect)
Definition at line 739 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_low_pass_filter()
int init_low_pass_filter (kest_effect * effect)
Definition at line 881 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_noise_suppressor()
int init_noise_suppressor (kest_effect * effect)
Definition at line 911 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_percussifier()
int init_percussifier (kest_effect * effect)
Definition at line 973 of file kest_effect_init.c.
Referenced by init_effect_of_type().
init_warbler()
int init_warbler (kest_effect * effect)
Definition at line 1099 of file kest_effect_init.c.
Referenced by init_effect_of_type().