Kestrel Interface: kest_resource.c File Reference
kest_resource.c File Reference
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 1
Functions
IMPLEMENT_LINKED_PTR_LIST (kest_dsp_resource)
int kest_init_dsp_resource (kest_dsp_resource *res)
int kest_dsp_resource_create_filter (kest_dsp_resource *res)
int string_to_resource_type (const char *type_str)
int kest_resources_assign_handles (kest_dsp_resource_pll *list)
kest_eff_resource_report empty_m_eff_resource_report ()
int kest_filter_init (kest_filter *filter)
kest_filter * kest_filter_create (kest_allocator *alloc)
int kest_resource_report_integrate (kest_eff_resource_report *a, const kest_eff_resource_report *b)
Variables
kest_dsp_resource sin_lut
kest_dsp_resource tanh_lut
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 1
Definition at line 9 of file kest_resource.c.
Function Documentation
empty_m_eff_resource_report()
kest_eff_resource_report empty_m_eff_resource_report ()
Definition at line 127 of file kest_resource.c.
Referenced by kest_pipeline_create_fpga_transfer_batch().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (kest_dsp_resource)
kest_dsp_resource_create_filter()
int kest_dsp_resource_create_filter (kest_dsp_resource * res)
Definition at line 50 of file kest_resource.c.
kest_filter_create()
kest_filter * kest_filter_create (kest_allocator * alloc)
Definition at line 150 of file kest_resource.c.
Referenced by kest_dsp_resource_create_filter(), kest_extract_biquad_from_dict(), and kest_extract_filter_from_dict().
kest_filter_init()
int kest_filter_init (kest_filter * filter)
Definition at line 136 of file kest_resource.c.
kest_init_dsp_resource()
int kest_init_dsp_resource (kest_dsp_resource * res)
Definition at line 34 of file kest_resource.c.
Referenced by kest_extract_resource_from_dict().
kest_resource_report_integrate()
int kest_resource_report_integrate (kest_eff_resource_report * a, const kest_eff_resource_report * b)
Definition at line 166 of file kest_resource.c.
Referenced by kest_fpga_batch_append_effect().
kest_resources_assign_handles()
int kest_resources_assign_handles (kest_dsp_resource_pll * list)
Definition at line 88 of file kest_resource.c.
Referenced by kest_parse_tokens().
string_to_resource_type()
int string_to_resource_type (const char * type_str)
Definition at line 70 of file kest_resource.c.
Referenced by kest_extract_resource_from_dict().
Variable Documentation
sin_lut
kest_dsp_resource sin_lut
Initial value:
= {
    .type   = KEST_DSP_RESOURCE_LUT,
    .name   = NULL,
    .handle = 0,
    .size   = NULL,
    .delay  = NULL,
    .data   = NULL
}
Definition at line 16 of file kest_resource.c.
Referenced by kest_process_asm_line().
tanh_lut
kest_dsp_resource tanh_lut
Initial value:
= {
    .type   = KEST_DSP_RESOURCE_LUT,
    .name   = NULL,
    .handle = 1,
    .size   = NULL,
    .delay  = NULL,
    .data   = NULL
}
Definition at line 25 of file kest_resource.c.
Referenced by kest_process_asm_line().