Kestrel Interface: kest_parameter.c File Reference
kest_parameter.c File Reference
#include <float.h>
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
#define DEFAULT_MAX_VELOCITY 1.0
Functions
IMPLEMENT_LINKED_PTR_LIST (kest_parameter)
IMPLEMENT_LINKED_PTR_LIST (kest_setting)
int init_parameter_str (kest_parameter *param)
int init_parameter (kest_parameter *param, const char *name, float level, float min, float max)
kest_parameter * new_m_parameter_wni (const char *name, const char *name_internal, float level, float min, float max)
int init_parameter_wni (kest_parameter *param, const char *name, const char *name_internal, float level, float min, float max)
int init_setting_str (kest_setting *setting)
int init_setting (kest_setting *setting, const char *name, uint16_t level)
void gut_parameter (kest_parameter *param)
void kest_parameter_free (kest_parameter *param)
int parameter_set_id (kest_parameter *param, uint16_t pid, uint16_t tid, uint16_t ppid)
void clone_parameter (kest_parameter *dest, kest_parameter *src)
kest_parameter * kest_parameter_make_clone (kest_parameter *src)
kest_parameter * kest_parameter_make_clone_for_effect (kest_parameter *src, kest_effect *effect)
int clone_setting (kest_setting *dest, kest_setting *src)
kest_setting * kest_setting_make_clone (kest_setting *src)
kest_setting * kest_setting_make_clone_for_effect (kest_setting *src, kest_effect *effect)
void gut_setting (kest_setting *setting)
void kest_setting_free (kest_setting *setting)
int kest_parameters_assign_ids (kest_parameter_pll *list)
int kest_settings_assign_ids (kest_setting_pll *list)
void kest_parameter_effect_rep_update (void *representer, void *representee)
void kest_setting_effect_rep_update (void *representer, void *representee)
Macro Definition Documentation
DEFAULT_MAX_VELOCITY
#define DEFAULT_MAX_VELOCITY 1.0
Definition at line 8 of file kest_parameter.c.
Referenced by init_parameter(), and init_parameter_str().
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 5 of file kest_parameter.c.
Function Documentation
clone_parameter()
void clone_parameter (kest_parameter * dest, kest_parameter * src)
Definition at line 182 of file kest_parameter.c.
Referenced by clone_profile(), kest_parameter_make_clone(), and kest_parameter_make_clone_for_effect().
clone_setting()
int clone_setting (kest_setting * dest, kest_setting * src)
Definition at line 247 of file kest_parameter.c.
Referenced by clone_effect(), kest_setting_make_clone(), and kest_setting_make_clone_for_effect().
gut_parameter()
void gut_parameter (kest_parameter * param)
Definition at line 149 of file kest_parameter.c.
Referenced by kest_extract_parameter_from_dict(), and kest_parameter_free().
gut_setting()
void gut_setting (kest_setting * setting)
Definition at line 332 of file kest_parameter.c.
Referenced by gut_effect(), kest_extract_setting_from_dict(), and kest_setting_free().
IMPLEMENT_LINKED_PTR_LIST() [1/2]
IMPLEMENT_LINKED_PTR_LIST (kest_parameter)
IMPLEMENT_LINKED_PTR_LIST() [2/2]
IMPLEMENT_LINKED_PTR_LIST (kest_setting)
init_parameter()
int init_parameter (kest_parameter * param, const char * name, float level, float min, float max)
Definition at line 46 of file kest_parameter.c.
Referenced by init_effect(), init_m_profile(), init_parameter_wni(), and kest_init_context().
init_parameter_str()
int init_parameter_str (kest_parameter * param)
Definition at line 15 of file kest_parameter.c.
Referenced by clone_parameter(), effect_add_parameter(), and kest_extract_parameter_from_dict().
init_parameter_wni()
int init_parameter_wni (kest_parameter * param, const char * name, const char * name_internal, float level, float min, float max)
Definition at line 84 of file kest_parameter.c.
Referenced by new_m_parameter_wni().
init_setting()
int init_setting (kest_setting * setting, const char * name, uint16_t level)
Definition at line 123 of file kest_parameter.c.
Referenced by init_effect().
init_setting_str()
int init_setting_str (kest_setting * setting)
Definition at line 94 of file kest_parameter.c.
Referenced by clone_setting(), effect_add_setting(), and kest_extract_setting_from_dict().
kest_parameter_effect_rep_update()
void kest_parameter_effect_rep_update (void * representer, void * representee)
Definition at line 467 of file kest_parameter.c.
Referenced by init_parameter(), and init_parameter_str().
kest_parameter_free()
void kest_parameter_free (kest_parameter * param)
Definition at line 159 of file kest_parameter.c.
Referenced by free_effect().
kest_parameter_make_clone()
kest_parameter * kest_parameter_make_clone (kest_parameter * src)
Definition at line 213 of file kest_parameter.c.
kest_parameter_make_clone_for_effect()
kest_parameter * kest_parameter_make_clone_for_effect (kest_parameter * src, kest_effect * effect)
Definition at line 228 of file kest_parameter.c.
Referenced by init_effect_from_effect_desc().
kest_parameters_assign_ids()
int kest_parameters_assign_ids (kest_parameter_pll * list)
Definition at line 357 of file kest_parameter.c.
Referenced by kest_parse_tokens().
kest_setting_effect_rep_update()
void kest_setting_effect_rep_update (void * representer, void * representee)
Definition at line 480 of file kest_parameter.c.
Referenced by init_setting(), and init_setting_str().
kest_setting_free()
void kest_setting_free (kest_setting * setting)
Definition at line 346 of file kest_parameter.c.
Referenced by free_effect().
kest_setting_make_clone()
kest_setting * kest_setting_make_clone (kest_setting * src)
Definition at line 298 of file kest_parameter.c.
kest_setting_make_clone_for_effect()
kest_setting * kest_setting_make_clone_for_effect (kest_setting * src, kest_effect * effect)
Definition at line 313 of file kest_parameter.c.
Referenced by init_effect_from_effect_desc().
kest_settings_assign_ids()
int kest_settings_assign_ids (kest_setting_pll * list)
Definition at line 379 of file kest_parameter.c.
Referenced by kest_parse_tokens().
new_m_parameter_wni()
kest_parameter * new_m_parameter_wni (const char * name, const char * name_internal, float level, float min, float max)
Definition at line 73 of file kest_parameter.c.
parameter_set_id()
int parameter_set_id (kest_parameter * param, uint16_t pid, uint16_t tid, uint16_t ppid)
Definition at line 170 of file kest_parameter.c.