Kestrel Interface: kest_expr_parser.h File Reference
kest_expr_parser.h File Reference
Macros
#define SUMSUB_PRECEDENCE 10
#define MULDIV_PRECEDENCE 20
#define UNARY_PRECEDENCE 30
#define POWER_PRECEDENCE 40
Functions
kest_expression * kest_parse_expression (kest_eff_parsing_state *ps, kest_token_ll *tokens, kest_token_ll *tokens_end)
Macro Definition Documentation
MULDIV_PRECEDENCE
#define MULDIV_PRECEDENCE 20
Definition at line 5 of file kest_expr_parser.h.
Referenced by kest_expression_infix_operator_precedence().
POWER_PRECEDENCE
#define POWER_PRECEDENCE 40
Definition at line 7 of file kest_expr_parser.h.
Referenced by kest_expression_infix_operator_precedence().
SUMSUB_PRECEDENCE
#define SUMSUB_PRECEDENCE 10
Definition at line 4 of file kest_expr_parser.h.
Referenced by kest_expression_infix_operator_precedence().
UNARY_PRECEDENCE
#define UNARY_PRECEDENCE 30
Definition at line 6 of file kest_expr_parser.h.
Referenced by kest_parse_expression_rec_pratt().
Function Documentation
kest_parse_expression()
kest_expression * kest_parse_expression (kest_eff_parsing_state * ps, kest_token_ll * tokens, kest_token_ll * tokens_end)
Definition at line 200 of file kest_expr_parser.c.
Referenced by kest_parse_asm_arg(), kest_parse_asm_arg_2(), and kest_parse_dict_val().