Kestrel Interface: kest_profile.h File Reference
kest_profile.h File Reference
Data Structures
struct kest_profile
Macros
#define PROFILE_NAME_MAX_LEN 128
#define KEST_PROFILE_MUTEX_TIMEOUT_MS 10
Functions
DECLARE_LINKED_PTR_LIST (kest_profile)
int init_m_profile (kest_profile *profile)
int init_m_pipeline (kest_pipeline *pipeline)
int profile_set_id (kest_profile *profile, uint16_t id)
int kest_profile_set_default_name_from_id (kest_profile *profile)
kest_effect * kest_profile_append_effect_eff (kest_profile *profile, kest_effect_desc *eff)
int kest_profile_remove_effect (kest_profile *profile, uint16_t id)
int kest_profile_move_effect (kest_profile *profile, int new_pos, int old_pos)
int clone_profile (kest_profile *dest, kest_profile *src)
void gut_profile (kest_profile *profile)
void free_profile (kest_profile *profile)
void kest_free_profile (kest_profile *profile)
int kest_profile_set_active (kest_profile *profile)
int kest_profile_set_inactive (kest_profile *profile)
int kest_profile_add_representation (kest_profile *profile, kest_representation *rep)
int kest_profile_remove_representation (kest_profile *profile, kest_representation *rep)
int kest_profile_add_name_representation (kest_profile *profile, kest_representation *rep)
int kest_profile_remove_name_representation (kest_profile *profile, kest_representation *rep)
int kest_profile_add_id_representation (kest_profile *profile, kest_representation *rep)
int kest_profile_remove_id_representation (kest_profile *profile, kest_representation *rep)
int kest_profile_save (kest_profile *profile)
int kest_profile_update_representations (kest_profile *profile)
int kest_profile_update_name_representations (kest_profile *profile)
int kest_profile_update_id_representations (kest_profile *profile)
int kest_profile_create_fpga_transfer_batch (kest_profile *profile, kest_fpga_transfer_batch *batch)
int kest_profile_if_active_update_fpga (kest_profile *profile)
int kest_profile_program_fpga (kest_profile *profile)
void kest_profile_file_rep_update (void *representer, void *representee)
kest_effect * kest_profile_get_effect_by_id (kest_profile *profile, int id)
Macro Definition Documentation
KEST_PROFILE_MUTEX_TIMEOUT_MS
#define KEST_PROFILE_MUTEX_TIMEOUT_MS 10
Definition at line 6 of file kest_profile.h.
PROFILE_NAME_MAX_LEN
#define PROFILE_NAME_MAX_LEN 128
Definition at line 4 of file kest_profile.h.
Referenced by clone_profile(), cxt_find_profile(), profile_view_save_name(), and sequence_view_set_name().
Function Documentation
clone_profile()
int clone_profile (kest_profile * dest, kest_profile * src)
Definition at line 224 of file kest_profile.c.
DECLARE_LINKED_PTR_LIST()
DECLARE_LINKED_PTR_LIST (kest_profile)
free_profile()
void free_profile (kest_profile * profile)
Definition at line 271 of file kest_profile.c.
Referenced by cxt_remove_profile(), kest_context_add_profile(), kest_context_add_profile_rp(), kest_free_profile(), and load_saved_profiles().
gut_profile()
void gut_profile (kest_profile * profile)
Definition at line 247 of file kest_profile.c.
Referenced by free_profile().
init_m_pipeline()
int init_m_pipeline (kest_pipeline * pipeline)
Definition at line 9 of file kest_pipeline.c.
Referenced by init_m_profile().
init_m_profile()
int init_m_profile (kest_profile * profile)
Definition at line 13 of file kest_profile.c.
Referenced by kest_context_add_profile(), kest_context_add_profile_rp(), and load_saved_profiles().
kest_free_profile()
void kest_free_profile (kest_profile * profile)
Definition at line 281 of file kest_profile.c.
Referenced by kest_sequence_delete_profile().
kest_profile_add_id_representation()
int kest_profile_add_id_representation (kest_profile * profile, kest_representation * rep)
kest_profile_add_name_representation()
int kest_profile_add_name_representation (kest_profile * profile, kest_representation * rep)
kest_profile_add_representation()
int kest_profile_add_representation (kest_profile * profile, kest_representation * rep)
Definition at line 98 of file kest_profile.c.
Referenced by configure_profile_view(), and seq_plus_cb().
kest_profile_append_effect_eff()
kest_effect * kest_profile_append_effect_eff (kest_profile * profile, kest_effect_desc * eff)
Definition at line 174 of file kest_profile.c.
Referenced by add_effect_from_menu_eff(), and read_profile_from_file().
kest_profile_create_fpga_transfer_batch()
int kest_profile_create_fpga_transfer_batch (kest_profile * profile, kest_fpga_transfer_batch * batch)
Definition at line 383 of file kest_profile.c.
kest_profile_file_rep_update()
void kest_profile_file_rep_update (void * representer, void * representee)
Definition at line 436 of file kest_profile.c.
Referenced by init_m_profile().
kest_profile_get_effect_by_id()
kest_effect * kest_profile_get_effect_by_id (kest_profile * profile, int id)
Definition at line 450 of file kest_profile.c.
Referenced by kest_page_id_find_page().
kest_profile_if_active_update_fpga()
int kest_profile_if_active_update_fpga (kest_profile * profile)
Definition at line 422 of file kest_profile.c.
Referenced by add_effect_from_menu_eff(), kest_profile_move_effect(), kest_profile_remove_effect(), profile_view_effect_delete_cb(), and sw_field_save_cb().
kest_profile_move_effect()
int kest_profile_move_effect (kest_profile * profile, int new_pos, int old_pos)
Definition at line 205 of file kest_profile.c.
Referenced by profile_view_effect_moved_cb().
kest_profile_program_fpga()
int kest_profile_program_fpga (kest_profile * profile)
Definition at line 396 of file kest_profile.c.
Referenced by kest_profile_if_active_update_fpga(), and kest_profile_set_active().
kest_profile_remove_effect()
int kest_profile_remove_effect (kest_profile * profile, uint16_t id)
Definition at line 191 of file kest_profile.c.
Referenced by cxt_remove_effect(), and profile_view_effect_delete_cb().
kest_profile_remove_id_representation()
int kest_profile_remove_id_representation (kest_profile * profile, kest_representation * rep)
kest_profile_remove_name_representation()
int kest_profile_remove_name_representation (kest_profile * profile, kest_representation * rep)
kest_profile_remove_representation()
int kest_profile_remove_representation (kest_profile * profile, kest_representation * rep)
Definition at line 132 of file kest_profile.c.
kest_profile_save()
int kest_profile_save (kest_profile * profile)
Definition at line 361 of file kest_profile.c.
Referenced by cxt_save_all_profiles().
kest_profile_set_active()
int kest_profile_set_active (kest_profile * profile)
Definition at line 72 of file kest_profile.c.
Referenced by set_active_profile(), and set_active_profile_from_sequence().
kest_profile_set_default_name_from_id()
int kest_profile_set_default_name_from_id (kest_profile * profile)
Definition at line 144 of file kest_profile.c.
Referenced by configure_profile_settings_page(), and create_profile_view_ui().
kest_profile_set_inactive()
int kest_profile_set_inactive (kest_profile * profile)
Definition at line 86 of file kest_profile.c.
Referenced by set_active_profile(), and set_active_profile_from_sequence().
kest_profile_update_id_representations()
int kest_profile_update_id_representations (kest_profile * profile)
kest_profile_update_name_representations()
int kest_profile_update_name_representations (kest_profile * profile)
kest_profile_update_representations()
int kest_profile_update_representations (kest_profile * profile)
Definition at line 119 of file kest_profile.c.
Referenced by add_effect_from_menu_eff(), kest_profile_save(), kest_profile_set_active(), kest_profile_set_inactive(), and profile_view_save_name().
profile_set_id()
int profile_set_id (kest_profile * profile, uint16_t id)
Definition at line 61 of file kest_profile.c.