Kestrel Interface: kest_sequence_view.h File Reference
kest_sequence_view.h File Reference
Data Structures
struct kest_sequence_view_str
Functions
int init_sequence_view (kest_ui_page *page)
int configure_sequence_view (kest_ui_page *page, void *data)
int create_sequence_view_ui (kest_ui_page *page)
int refresh_sequence_view (kest_ui_page *page)
int free_sequence_view_ui (kest_ui_page *page)
int sequence_view_free_all (kest_ui_page *page)
int sequence_view_append_profile (kest_ui_page *page, kest_profile *sequence)
int create_sequence_view_for (kest_sequence *sequence)
void sequence_view_rep_update (void *representer, void *representee)
void sequence_view_profile_button_rep_update (void *representer, void *representee)
Function Documentation
configure_sequence_view()
int configure_sequence_view (kest_ui_page * page, void * data)
Definition at line 279 of file kest_sequence_view.c.
Referenced by create_sequence_view_for(), and init_sequence_view().
create_sequence_view_for()
int create_sequence_view_for (kest_sequence * sequence)
Definition at line 9 of file kest_sequence_view.c.
Referenced by load_saved_sequences(), menu_item_sequence_listing_released_cb(), and sequence_list_add_cb().
create_sequence_view_ui()
int create_sequence_view_ui (kest_ui_page * page)
Definition at line 353 of file kest_sequence_view.c.
Referenced by init_sequence_view().
free_sequence_view_ui()
int free_sequence_view_ui (kest_ui_page * page)
Definition at line 390 of file kest_sequence_view.c.
init_sequence_view()
int init_sequence_view (kest_ui_page * page)
Definition at line 65 of file kest_sequence_view.c.
Referenced by create_sequence_view_for(), and kest_init_global_pages().
refresh_sequence_view()
int refresh_sequence_view (kest_ui_page * page)
Definition at line 380 of file kest_sequence_view.c.
sequence_view_append_profile()
int sequence_view_append_profile (kest_ui_page * page, kest_profile * sequence)
sequence_view_free_all()
int sequence_view_free_all (kest_ui_page * page)
Definition at line 400 of file kest_sequence_view.c.
sequence_view_profile_button_rep_update()
void sequence_view_profile_button_rep_update (void * representer, void * representee)
Definition at line 450 of file kest_sequence_view.c.
Referenced by configure_sequence_view(), and seq_plus_cb().
sequence_view_rep_update()
void sequence_view_rep_update (void * representer, void * representee)
Definition at line 411 of file kest_sequence_view.c.
Referenced by init_sequence_view().