Kestrel Interface: kest_sequence.c File Reference
kest_sequence.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (kest_sequence)
int init_m_sequence (kest_sequence *sequence)
int sequence_append_profile (kest_sequence *sequence, kest_profile *profile)
seq_profile_ll * sequence_append_profile_rp (kest_sequence *sequence, kest_profile *profile)
int kest_sequence_move_profile (kest_sequence *sequence, int pos, int new_pos)
int kest_sequence_remove_profile (kest_sequence *sequence, kest_profile *profile)
int kest_sequence_delete_profile (kest_sequence *sequence, kest_profile *profile)
void free_sequence (kest_sequence *sequence)
int kest_sequence_add_menu_listing (kest_sequence *sequence, kest_menu_item *listing)
int kest_sequence_begin (kest_sequence *sequence)
int kest_sequence_begin_at (kest_sequence *sequence, kest_profile *profile)
int kest_sequence_regress (kest_sequence *sequence)
int kest_sequence_advance (kest_sequence *sequence)
int kest_sequence_stop (kest_sequence *sequence)
int kest_sequence_stop_from_profile (kest_sequence *sequence)
int kest_sequence_activate_at (kest_sequence *sequence, kest_profile *profile)
int kest_sequence_add_representation (kest_sequence *sequence, kest_representation *rep)
int kest_sequence_update_representations (kest_sequence *sequence)
void kest_sequence_file_rep_update (void *representer, void *representee)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_sequence.c.
Function Documentation
free_sequence()
void free_sequence (kest_sequence * sequence)
Definition at line 246 of file kest_sequence.c.
Referenced by cxt_remove_sequence(), kest_context_add_sequence_rp(), and load_saved_sequences().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (kest_sequence)
init_m_sequence()
int init_m_sequence (kest_sequence * sequence)
Definition at line 11 of file kest_sequence.c.
Referenced by kest_context_add_sequence_rp(), kest_context_init_main_sequence(), and load_saved_sequences().
kest_sequence_activate_at()
int kest_sequence_activate_at (kest_sequence * sequence, kest_profile * profile)
Definition at line 435 of file kest_sequence.c.
Referenced by set_active_profile().
kest_sequence_add_menu_listing()
int kest_sequence_add_menu_listing (kest_sequence * sequence, kest_menu_item * listing)
Definition at line 251 of file kest_sequence.c.
Referenced by create_sequence_listing_menu_item().
kest_sequence_add_representation()
int kest_sequence_add_representation (kest_sequence * sequence, kest_representation * rep)
Definition at line 461 of file kest_sequence.c.
Referenced by configure_sequence_view().
kest_sequence_advance()
int kest_sequence_advance (kest_sequence * sequence)
Definition at line 363 of file kest_sequence.c.
Referenced by cxt_handle_hw_switch().
kest_sequence_begin()
int kest_sequence_begin (kest_sequence * sequence)
Definition at line 270 of file kest_sequence.c.
Referenced by seq_play_cb().
kest_sequence_begin_at()
int kest_sequence_begin_at (kest_sequence * sequence, kest_profile * profile)
Definition at line 293 of file kest_sequence.c.
Referenced by profile_view_play_button_cb().
kest_sequence_delete_profile()
int kest_sequence_delete_profile (kest_sequence * sequence, kest_profile * profile)
Definition at line 231 of file kest_sequence.c.
Referenced by seq_view_delete_cb().
kest_sequence_file_rep_update()
void kest_sequence_file_rep_update (void * representer, void * representee)
Definition at line 518 of file kest_sequence.c.
Referenced by init_m_sequence().
kest_sequence_move_profile()
int kest_sequence_move_profile (kest_sequence * sequence, int pos, int new_pos)
Definition at line 138 of file kest_sequence.c.
Referenced by seq_view_moved_cb().
kest_sequence_regress()
int kest_sequence_regress (kest_sequence * sequence)
Definition at line 331 of file kest_sequence.c.
Referenced by cxt_handle_hw_switch().
kest_sequence_remove_profile()
int kest_sequence_remove_profile (kest_sequence * sequence, kest_profile * profile)
Definition at line 197 of file kest_sequence.c.
Referenced by kest_sequence_delete_profile().
kest_sequence_stop()
int kest_sequence_stop (kest_sequence * sequence)
Definition at line 402 of file kest_sequence.c.
kest_sequence_stop_from_profile()
int kest_sequence_stop_from_profile (kest_sequence * sequence)
Definition at line 420 of file kest_sequence.c.
kest_sequence_update_representations()
int kest_sequence_update_representations (kest_sequence * sequence)
Definition at line 480 of file kest_sequence.c.
Referenced by kest_sequence_activate_at(), kest_sequence_begin(), kest_sequence_begin_at(), kest_sequence_move_profile(), kest_sequence_remove_profile(), kest_sequence_stop(), kest_sequence_stop_from_profile(), sequence_append_profile_rp(), and sequence_view_set_name().
sequence_append_profile()
int sequence_append_profile (kest_sequence * sequence, kest_profile * profile)
Definition at line 45 of file kest_sequence.c.
Referenced by read_sequence_from_file().
sequence_append_profile_rp()
seq_profile_ll * sequence_append_profile_rp (kest_sequence * sequence, kest_profile * profile)
Definition at line 83 of file kest_sequence.c.
Referenced by seq_plus_cb().