Kestrel Interface: kest_files.h File Reference
kest_files.h File Reference
Macros
#define KEST_PROFILE_MAGIC_BYTE 0x4a
#define KEST_PROFILE_PIPELINE_LINEAR 0x01
#define KEST_PROFILE_BROKEN_TRANSFORMER 0xfffd
#define KEST_STATE_MAGIC_BYTE 0x4b
#define KEST_SEQUENCE_MAGIC_BYTE 0x4c
#define KEST_WRITE_UNFINISHED_BYTE 0xfe
#define KEST_WRITE_FINISHED_BYTE 0xff
#define MAIN_SEQUENCE_FNAME "/sdcard/ms.seq"
#define SETTINGS_FNAME "/sdcard/conf"
#define KEST_PROFILES_DIR "/sdcard/prof/"
#define KEST_SEQUENCES_DIR "/sdcard/seq/"
#define KEST_EFFECT_DESC_DIR "/sdcard/eff/"
#define PROFILE_EXTENSION ".prf"
#define SEQUENCE_EXTENSION ".seq"
#define EFF_DESC_EXTENSION ".eff"
Functions
int save_profile_as_file (kest_profile *profile, const char *fname)
int save_profile_as_file_safe (kest_profile *profile, const char *fname)
int read_profile_from_file (kest_profile *profile, const char *fname)
int save_sequence_as_file (kest_sequence *sequence, const char *fname)
int save_sequence_as_file_safe (kest_sequence *sequence, const char *fname)
int read_sequence_from_file (kest_sequence *sequence, const char *fname)
int save_state_to_file (struct kest_state *state, const char *fname)
int load_state_from_file (struct kest_state *state, const char *fname)
int load_effects (kest_context *cxt)
int init_periodic_backup_task ()
int save_profile (kest_profile *profile)
int load_saved_profiles (kest_context *cxt)
int save_sequence (kest_sequence *sequence)
int load_saved_sequences (kest_context *cxt)
int safe_file_write (int(*write_func)(void *arg, const char *fname), void *arg, const char *fname)
string_ll * list_files_in_directory (char *dir)
int kest_init_directories ()
void erase_sd_card_void_cb (void *data)
void erase_sd_card ()
int fnames_agree (char *a, char *b)
Macro Definition Documentation
EFF_DESC_EXTENSION
#define EFF_DESC_EXTENSION ".eff"
Definition at line 33 of file kest_files.h.
KEST_EFFECT_DESC_DIR
#define KEST_EFFECT_DESC_DIR "/sdcard/eff/"
Definition at line 27 of file kest_files.h.
Referenced by load_effects().
KEST_PROFILE_BROKEN_TRANSFORMER
#define KEST_PROFILE_BROKEN_TRANSFORMER 0xfffd
Definition at line 7 of file kest_files.h.
Referenced by save_profile_as_file().
KEST_PROFILE_MAGIC_BYTE
#define KEST_PROFILE_MAGIC_BYTE 0x4a
Definition at line 4 of file kest_files.h.
Referenced by read_profile_from_file(), read_sequence_from_file(), and save_profile_as_file().
KEST_PROFILE_PIPELINE_LINEAR
#define KEST_PROFILE_PIPELINE_LINEAR 0x01
Definition at line 5 of file kest_files.h.
KEST_PROFILES_DIR
#define KEST_PROFILES_DIR "/sdcard/prof/"
Definition at line 25 of file kest_files.h.
Referenced by kest_init_directories(), load_saved_profiles(), and save_profile().
KEST_SEQUENCE_MAGIC_BYTE
#define KEST_SEQUENCE_MAGIC_BYTE 0x4c
Definition at line 11 of file kest_files.h.
Referenced by read_sequence_from_file(), and save_sequence_as_file().
KEST_SEQUENCES_DIR
#define KEST_SEQUENCES_DIR "/sdcard/seq/"
Definition at line 26 of file kest_files.h.
Referenced by kest_init_directories(), load_saved_sequences(), and save_sequence().
KEST_STATE_MAGIC_BYTE
#define KEST_STATE_MAGIC_BYTE 0x4b
Definition at line 9 of file kest_files.h.
Referenced by load_state_from_file(), and save_state_to_file().
KEST_WRITE_FINISHED_BYTE
#define KEST_WRITE_FINISHED_BYTE 0xff
Definition at line 14 of file kest_files.h.
Referenced by file_validity_check(), load_state_from_file(), read_profile_from_file(), save_profile_as_file(), save_sequence_as_file(), and save_state_to_file().
KEST_WRITE_UNFINISHED_BYTE
#define KEST_WRITE_UNFINISHED_BYTE 0xfe
Definition at line 13 of file kest_files.h.
Referenced by save_profile_as_file(), save_sequence_as_file(), and save_state_to_file().
MAIN_SEQUENCE_FNAME
#define MAIN_SEQUENCE_FNAME "/sdcard/ms.seq"
Definition at line 23 of file kest_files.h.
Referenced by kest_context_init_main_sequence(), and load_saved_sequences().
PROFILE_EXTENSION
#define PROFILE_EXTENSION ".prf"
Definition at line 31 of file kest_files.h.
Referenced by save_profile().
SEQUENCE_EXTENSION
#define SEQUENCE_EXTENSION ".seq"
Definition at line 32 of file kest_files.h.
Referenced by save_sequence().
SETTINGS_FNAME
#define SETTINGS_FNAME "/sdcard/conf"
Definition at line 24 of file kest_files.h.
Referenced by app_main(), kest_state_representation_update(), and main_task().
Function Documentation
erase_sd_card()
void erase_sd_card ()
Definition at line 1242 of file kest_files.c.
Referenced by erase_sd_card_void_cb().
erase_sd_card_void_cb()
void erase_sd_card_void_cb (void * data)
Definition at line 1185 of file kest_files.c.
Referenced by configure_main_menu().
fnames_agree()
int fnames_agree (char * a, char * b)
Definition at line 1247 of file kest_files.c.
Referenced by cxt_get_profile_by_fname(), and cxt_get_sequence_by_fname().
init_periodic_backup_task()
int init_periodic_backup_task ()
kest_init_directories()
int kest_init_directories ()
Definition at line 697 of file kest_files.c.
Referenced by app_main(), and main_task().
list_files_in_directory()
string_ll * list_files_in_directory (char * dir)
Definition at line 1121 of file kest_files.c.
Referenced by load_effects(), load_saved_profiles(), and load_saved_sequences().
load_effects()
int load_effects (kest_context * cxt)
Definition at line 1072 of file kest_files.c.
Referenced by app_main(), and main_task().
load_saved_profiles()
int load_saved_profiles (kest_context * cxt)
Definition at line 960 of file kest_files.c.
Referenced by app_main(), and main_task().
load_saved_sequences()
int load_saved_sequences (kest_context * cxt)
Definition at line 1024 of file kest_files.c.
Referenced by app_main(), and main_task().
load_state_from_file()
int load_state_from_file (struct kest_state * state, const char * fname)
Definition at line 298 of file kest_files.c.
Referenced by app_main(), and main_task().
read_profile_from_file()
int read_profile_from_file (kest_profile * profile, const char * fname)
Definition at line 434 of file kest_files.c.
Referenced by load_saved_profiles().
read_sequence_from_file()
int read_sequence_from_file (kest_sequence * sequence, const char * fname)
Definition at line 590 of file kest_files.c.
Referenced by load_saved_sequences().
safe_file_write()
int safe_file_write (int(* write_func)(void *arg, const char *fname), void * arg, const char * fname)
Definition at line 738 of file kest_files.c.
Referenced by kest_state_representation_update().
save_profile()
int save_profile (kest_profile * profile)
Definition at line 883 of file kest_files.c.
Referenced by kest_effect_profile_rep_update(), kest_profile_file_rep_update(), kest_profile_save(), profile_settings_save_button_cb(), and save_sequence_as_file().
save_profile_as_file()
int save_profile_as_file (kest_profile * profile, const char * fname)
Definition at line 96 of file kest_files.c.
Referenced by save_profile(), and save_profile_as_file_safe().
save_profile_as_file_safe()
int save_profile_as_file_safe (kest_profile * profile, const char * fname)
Definition at line 786 of file kest_files.c.
save_sequence()
int save_sequence (kest_sequence * sequence)
Definition at line 921 of file kest_files.c.
Referenced by kest_sequence_file_rep_update(), and seq_save_cb().
save_sequence_as_file()
int save_sequence_as_file (kest_sequence * sequence, const char * fname)
Definition at line 194 of file kest_files.c.
Referenced by save_sequence().
save_sequence_as_file_safe()
int save_sequence_as_file_safe (kest_sequence * sequence, const char * fname)
save_state_to_file()
int save_state_to_file (struct kest_state * state, const char * fname)
Definition at line 258 of file kest_files.c.
Referenced by kest_state_representation_update().