Kestrel Interface: kest_parameter.h File Reference
kest_parameter.h File Reference
Data Structures
struct kest_parameter_id
struct kest_parameter
struct kest_setting_option
struct kest_setting_id
struct kest_setting
Macros
#define PARAM_NAM_ENG_MAX_LEN 254
#define PARAMETER_SCALE_LINEAR 0
#define PARAMETER_SCALE_LOGARITHMIC 1
#define KEST_STANDARD_GAIN_MIN -24
#define KEST_STANDARD_GAIN_MAX 24
#define TRANSFORMER_SETTING_ENUM 0
#define TRANSFORMER_SETTING_BOOL 1
#define TRANSFORMER_SETTING_INT 2
#define TRANSFORMER_SETTING_PAGE_SETTINGS 0
#define TRANSFORMER_SETTING_PAGE_MAIN 1
Typedefs
typedef kest_setting_pll setting_ll
Functions
DECLARE_LINKED_PTR_LIST (kest_parameter)
DECLARE_LINKED_PTR_LIST (kest_setting)
int init_parameter_str (kest_parameter *param)
int init_parameter (kest_parameter *param, const char *name, float level, float min, float max)
int init_parameter_wni (kest_parameter *param, const char *name, const char *name_internal, float level, float min, float max)
int kest_parameters_assign_ids (kest_parameter_pll *list)
int kest_settings_assign_ids (kest_setting_pll *list)
kest_parameter * new_m_parameter_wni (const char *name, const char *name_internal, float level, float min, float max)
int init_setting_str (kest_setting *setting)
int init_setting (kest_setting *setting, const char *name, uint16_t level)
void clone_parameter (kest_parameter *dest, kest_parameter *src)
kest_parameter * kest_parameter_make_clone (kest_parameter *src)
kest_parameter * kest_parameter_make_clone_for_effect (kest_parameter *src, struct kest_effect *effect)
void gut_parameter (kest_parameter *param)
void kest_parameter_free (kest_parameter *param)
int clone_setting (kest_setting *dest, kest_setting *src)
kest_setting * kest_setting_make_clone (kest_setting *src)
kest_setting * kest_setting_make_clone_for_effect (kest_setting *src, struct kest_effect *effect)
void gut_setting (kest_setting *setting)
void kest_setting_free (kest_setting *setting)
void kest_parameter_effect_rep_update (void *representer, void *representee)
void kest_setting_effect_rep_update (void *representer, void *representee)
Macro Definition Documentation
KEST_STANDARD_GAIN_MAX
#define KEST_STANDARD_GAIN_MAX 24
Definition at line 10 of file kest_parameter.h.
KEST_STANDARD_GAIN_MIN
#define KEST_STANDARD_GAIN_MIN -24
Definition at line 9 of file kest_parameter.h.
PARAM_NAM_ENG_MAX_LEN
#define PARAM_NAM_ENG_MAX_LEN 254
Definition at line 4 of file kest_parameter.h.
PARAMETER_SCALE_LINEAR
#define PARAMETER_SCALE_LINEAR 0
Definition at line 6 of file kest_parameter.h.
Referenced by init_3_band_eq(), init_amplifier(), init_compressor(), init_delay(), init_dirty_octave(), init_distortion(), init_envelope(), init_flanger(), init_low_end_compressor(), init_noise_suppressor(), init_parameter_str(), init_percussifier(), init_warbler(), and kest_extract_parameter_from_dict().
PARAMETER_SCALE_LOGARITHMIC
#define PARAMETER_SCALE_LOGARITHMIC 1
Definition at line 7 of file kest_parameter.h.
Referenced by init_band_pass_filter(), init_distortion(), init_effect(), init_envelope(), init_high_pass_filter(), init_low_pass_filter(), init_warbler(), kest_extract_parameter_from_dict(), parameter_widget_change_cb_inner(), and parameter_widget_update_value().
TRANSFORMER_SETTING_BOOL
#define TRANSFORMER_SETTING_BOOL 1
Definition at line 69 of file kest_parameter.h.
Referenced by kest_extract_setting_from_dict().
TRANSFORMER_SETTING_ENUM
#define TRANSFORMER_SETTING_ENUM 0
Definition at line 68 of file kest_parameter.h.
Referenced by kest_extract_setting_from_dict().
TRANSFORMER_SETTING_INT
#define TRANSFORMER_SETTING_INT 2
Definition at line 70 of file kest_parameter.h.
Referenced by init_setting_str(), and kest_extract_setting_from_dict().
TRANSFORMER_SETTING_PAGE_MAIN
#define TRANSFORMER_SETTING_PAGE_MAIN 1
Definition at line 73 of file kest_parameter.h.
Referenced by configure_effect_view(), init_delay(), init_distortion(), init_flanger(), and kest_extract_setting_from_dict().
TRANSFORMER_SETTING_PAGE_SETTINGS
#define TRANSFORMER_SETTING_PAGE_SETTINGS 0
Definition at line 72 of file kest_parameter.h.
Referenced by init_amplifier(), init_setting_str(), and kest_extract_setting_from_dict().
Typedef Documentation
setting_ll
typedef kest_setting_pll setting_ll
Definition at line 110 of file kest_parameter.h.
Function Documentation
clone_parameter()
void clone_parameter (kest_parameter * dest, kest_parameter * src)
Definition at line 182 of file kest_parameter.c.
Referenced by clone_profile(), kest_parameter_make_clone(), and kest_parameter_make_clone_for_effect().
clone_setting()
int clone_setting (kest_setting * dest, kest_setting * src)
Definition at line 247 of file kest_parameter.c.
Referenced by clone_effect(), kest_setting_make_clone(), and kest_setting_make_clone_for_effect().
DECLARE_LINKED_PTR_LIST() [1/2]
DECLARE_LINKED_PTR_LIST (kest_parameter)
DECLARE_LINKED_PTR_LIST() [2/2]
DECLARE_LINKED_PTR_LIST (kest_setting)
gut_parameter()
void gut_parameter (kest_parameter * param)
Definition at line 149 of file kest_parameter.c.
Referenced by kest_extract_parameter_from_dict(), and kest_parameter_free().
gut_setting()
void gut_setting (kest_setting * setting)
Definition at line 332 of file kest_parameter.c.
Referenced by gut_effect(), kest_extract_setting_from_dict(), and kest_setting_free().
init_parameter()
int init_parameter (kest_parameter * param, const char * name, float level, float min, float max)
Definition at line 46 of file kest_parameter.c.
Referenced by init_effect(), init_m_profile(), init_parameter_wni(), and kest_init_context().
init_parameter_str()
int init_parameter_str (kest_parameter * param)
Definition at line 15 of file kest_parameter.c.
Referenced by clone_parameter(), effect_add_parameter(), and kest_extract_parameter_from_dict().
init_parameter_wni()
int init_parameter_wni (kest_parameter * param, const char * name, const char * name_internal, float level, float min, float max)
Definition at line 84 of file kest_parameter.c.
Referenced by new_m_parameter_wni().
init_setting()
int init_setting (kest_setting * setting, const char * name, uint16_t level)
Definition at line 123 of file kest_parameter.c.
Referenced by init_effect().
init_setting_str()
int init_setting_str (kest_setting * setting)
Definition at line 94 of file kest_parameter.c.
Referenced by clone_setting(), effect_add_setting(), and kest_extract_setting_from_dict().
kest_parameter_effect_rep_update()
void kest_parameter_effect_rep_update (void * representer, void * representee)
Definition at line 467 of file kest_parameter.c.
Referenced by init_parameter(), and init_parameter_str().
kest_parameter_free()
void kest_parameter_free (kest_parameter * param)
Definition at line 159 of file kest_parameter.c.
Referenced by free_effect().
kest_parameter_make_clone()
kest_parameter * kest_parameter_make_clone (kest_parameter * src)
Definition at line 213 of file kest_parameter.c.
kest_parameter_make_clone_for_effect()
kest_parameter * kest_parameter_make_clone_for_effect (kest_parameter * src, struct kest_effect * effect)
Definition at line 228 of file kest_parameter.c.
Referenced by init_effect_from_effect_desc().
kest_parameters_assign_ids()
int kest_parameters_assign_ids (kest_parameter_pll * list)
Definition at line 357 of file kest_parameter.c.
Referenced by kest_parse_tokens().
kest_setting_effect_rep_update()
void kest_setting_effect_rep_update (void * representer, void * representee)
Definition at line 480 of file kest_parameter.c.
Referenced by init_setting(), and init_setting_str().
kest_setting_free()
void kest_setting_free (kest_setting * setting)
Definition at line 346 of file kest_parameter.c.
Referenced by free_effect().
kest_setting_make_clone()
kest_setting * kest_setting_make_clone (kest_setting * src)
Definition at line 298 of file kest_parameter.c.
kest_setting_make_clone_for_effect()
kest_setting * kest_setting_make_clone_for_effect (kest_setting * src, struct kest_effect * effect)
Definition at line 313 of file kest_parameter.c.
Referenced by init_effect_from_effect_desc().
kest_settings_assign_ids()
int kest_settings_assign_ids (kest_setting_pll * list)
Definition at line 379 of file kest_parameter.c.
Referenced by kest_parse_tokens().
new_m_parameter_wni()
kest_parameter * new_m_parameter_wni (const char * name, const char * name_internal, float level, float min, float max)
Definition at line 73 of file kest_parameter.c.