Kestrel Interface: kest_sd.h File Reference
kest_sd.h File Reference
Macros
#define MOUNT_POINT "/sdcard"
Functions
int init_sd_card ()
int kest_sd_mode_msc ()
int kest_sd_mode_local ()
int kest_sd_toggle_msc ()
Variables
int sd_msc_mode
Macro Definition Documentation
MOUNT_POINT
#define MOUNT_POINT "/sdcard"
Definition at line 7 of file kest_sd.h.
Referenced by erase_sd_card().
Function Documentation
init_sd_card()
int init_sd_card ()
Definition at line 155 of file kest_sd.c.
Referenced by app_main().
kest_sd_mode_local()
int kest_sd_mode_local ()
Definition at line 179 of file kest_sd.c.
Referenced by kest_sd_toggle_msc().
kest_sd_mode_msc()
int kest_sd_mode_msc ()
Definition at line 162 of file kest_sd.c.
Referenced by kest_sd_toggle_msc().
kest_sd_toggle_msc()
int kest_sd_toggle_msc ()
Definition at line 195 of file kest_sd.c.
Referenced by kest_msc_button_cb().
Variable Documentation
sd_msc_mode
int sd_msc_mode extern
Definition at line 58 of file kest_sd.c.
Referenced by kest_msc_button_cb(), kest_sd_mode_local(), kest_sd_mode_msc(), and kest_sd_toggle_msc().