Kestrel Interface: kest_sequence_list.h File Reference
kest_sequence_list.h File Reference
Functions
int init_sequence_list (kest_ui_page *page)
int configure_sequence_list (kest_ui_page *page, void *data)
int create_sequence_list_ui (kest_ui_page *page)
int free_sequence_list_ui (kest_ui_page *page)
int enter_sequence_list (kest_ui_page *page)
int refresh_sequence_list (kest_ui_page *page)
struct kest_menu_item * create_sequence_listing_menu_item (char *text, kest_sequence *sequence, kest_ui_page *parent)
void sequence_listing_delete_button_cb (lv_event_t *e)
void disappear_sequence_listing_delete_button (lv_timer_t *timer)
void menu_item_sequence_listing_released_cb (lv_event_t *e)
void menu_item_sequence_listing_long_pressed_cb (lv_event_t *e)
int sequence_listing_menu_item_refresh_active (struct kest_menu_item *item)
int sequence_listing_menu_item_change_name (struct kest_menu_item *item, char *name)
Function Documentation
configure_sequence_list()
int configure_sequence_list (kest_ui_page * page, void * data)
Definition at line 145 of file kest_sequence_list.c.
Referenced by init_sequence_list(), and kest_create_ui().
create_sequence_list_ui()
int create_sequence_list_ui (kest_ui_page * page)
create_sequence_listing_menu_item()
struct kest_menu_item * create_sequence_listing_menu_item (char * text, kest_sequence * sequence, kest_ui_page * parent)
Definition at line 9 of file kest_sequence_list.c.
Referenced by configure_sequence_list(), and sequence_list_add_cb().
disappear_sequence_listing_delete_button()
void disappear_sequence_listing_delete_button (lv_timer_t * timer)
Definition at line 226 of file kest_sequence_list.c.
Referenced by menu_item_sequence_listing_released_cb().
enter_sequence_list()
int enter_sequence_list (kest_ui_page * page)
free_sequence_list_ui()
int free_sequence_list_ui (kest_ui_page * page)
Definition at line 196 of file kest_sequence_list.c.
init_sequence_list()
int init_sequence_list (kest_ui_page * page)
Definition at line 90 of file kest_sequence_list.c.
Referenced by kest_init_global_pages().
menu_item_sequence_listing_long_pressed_cb()
void menu_item_sequence_listing_long_pressed_cb (lv_event_t * e)
Definition at line 278 of file kest_sequence_list.c.
Referenced by create_menu_item_ui().
menu_item_sequence_listing_released_cb()
void menu_item_sequence_listing_released_cb (lv_event_t * e)
Definition at line 235 of file kest_sequence_list.c.
Referenced by create_menu_item_ui().
refresh_sequence_list()
int refresh_sequence_list (kest_ui_page * page)
sequence_listing_delete_button_cb()
void sequence_listing_delete_button_cb (lv_event_t * e)
Definition at line 206 of file kest_sequence_list.c.
Referenced by create_menu_item_ui().
sequence_listing_menu_item_change_name()
int sequence_listing_menu_item_change_name (struct kest_menu_item * item, char * name)
Definition at line 75 of file kest_sequence_list.c.
sequence_listing_menu_item_refresh_active()
int sequence_listing_menu_item_refresh_active (struct kest_menu_item * item)
Definition at line 37 of file kest_sequence_list.c.
Referenced by sequence_list_add_cb().