Kestrel Interface: kest_printf.c File Reference
kest_printf.c File Reference
#include <stdarg.h>
#include "kest_int.h"
Functions
void kest_printf_init ()
void kest_printf (const char *fmt,...)
Variables
int prints_initd = 0
Function Documentation
kest_printf()
void kest_printf (const char * fmt, ...)
Definition at line 21 of file kest_printf.c.
Referenced by app_main(), footswitch_task(), kest_sd_mode_local(), kest_sd_mode_msc(), kest_sd_toggle_msc(), kest_sgtl5000_init(), sgtl5000_enable(), and sgtl5000_readout_registers().
kest_printf_init()
void kest_printf_init ()
Definition at line 11 of file kest_printf.c.
Referenced by app_main(), and main_task().
Variable Documentation
prints_initd
int prints_initd = 0
Definition at line 6 of file kest_printf.c.
Referenced by kest_printf(), and kest_printf_init().