Kestrel Interface: kest_profile_view.h File Reference
kest_profile_view.h File Reference
Data Structures
struct kest_profile_view_str
Functions
kest_ui_page * create_profile_view_for (kest_profile *profile)
int init_profile_view (kest_ui_page *page)
int configure_profile_view (kest_ui_page *page, void *data)
int create_profile_view_ui (kest_ui_page *page)
int free_profile_view_ui (kest_ui_page *page)
int free_profile_view (kest_ui_page *page)
int enter_profile_view (kest_ui_page *page)
int enter_profile_view_from (kest_ui_page *page, kest_ui_page *prev)
int refresh_profile_view (kest_ui_page *page)
int profile_view_recalculate_indices (kest_ui_page *page)
int profile_view_append_effect (kest_ui_page *page, kest_effect *effect)
int profile_view_populate_index_pos_array (kest_ui_page *page)
int profile_view_index_y_position (int index)
int profile_view_refresh_play_button (kest_ui_page *page)
int profile_view_refresh_save_button (kest_ui_page *page)
int profile_view_change_name (kest_ui_page *page, char *name)
int profile_view_set_left_button_mode (kest_ui_page *page, int mode)
void profile_view_rep_update (void *representer, void *representee)
Function Documentation
configure_profile_view()
int configure_profile_view (kest_ui_page * page, void * data)
Definition at line 335 of file kest_profile_view.c.
Referenced by create_profile_view_for(), and init_profile_view().
create_profile_view_for()
kest_ui_page * create_profile_view_for (kest_profile * profile)
Definition at line 9 of file kest_profile_view.c.
Referenced by create_new_profile_with_teensy(), load_saved_profiles(), and seq_view_clicked_cb().
create_profile_view_ui()
int create_profile_view_ui (kest_ui_page * page)
Definition at line 416 of file kest_profile_view.c.
Referenced by init_profile_view().
enter_profile_view()
int enter_profile_view (kest_ui_page * page)
Definition at line 472 of file kest_profile_view.c.
Referenced by init_profile_view().
enter_profile_view_from()
int enter_profile_view_from (kest_ui_page * page, kest_ui_page * prev)
free_profile_view()
int free_profile_view (kest_ui_page * page)
Definition at line 521 of file kest_profile_view.c.
Referenced by create_profile_view_for(), and init_profile_view().
free_profile_view_ui()
int free_profile_view_ui (kest_ui_page * page)
init_profile_view()
int init_profile_view (kest_ui_page * page)
Definition at line 116 of file kest_profile_view.c.
Referenced by create_profile_view_for().
profile_view_append_effect()
int profile_view_append_effect (kest_ui_page * page, kest_effect * effect)
Definition at line 488 of file kest_profile_view.c.
Referenced by add_effect_from_menu_eff().
profile_view_change_name()
int profile_view_change_name (kest_ui_page * page, char * name)
Definition at line 552 of file kest_profile_view.c.
profile_view_index_y_position()
int profile_view_index_y_position (int index)
profile_view_populate_index_pos_array()
int profile_view_populate_index_pos_array (kest_ui_page * page)
profile_view_recalculate_indices()
int profile_view_recalculate_indices (kest_ui_page * page)
Definition at line 510 of file kest_profile_view.c.
profile_view_refresh_play_button()
int profile_view_refresh_play_button (kest_ui_page * page)
Definition at line 533 of file kest_profile_view.c.
profile_view_refresh_save_button()
int profile_view_refresh_save_button (kest_ui_page * page)
Definition at line 544 of file kest_profile_view.c.
profile_view_rep_update()
void profile_view_rep_update (void * representer, void * representee)
Definition at line 577 of file kest_profile_view.c.
Referenced by init_profile_view().
profile_view_set_left_button_mode()
int profile_view_set_left_button_mode (kest_ui_page * page, int mode)
Definition at line 565 of file kest_profile_view.c.
refresh_profile_view()
int refresh_profile_view (kest_ui_page * page)