Kestrel Interface: kest_dict_extract.h File Reference
kest_dict_extract.h File Reference
Functions
kest_setting * kest_extract_setting_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict)
kest_parameter * kest_extract_parameter_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict)
kest_dsp_resource * kest_extract_resource_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict)
Function Documentation
kest_extract_parameter_from_dict()
kest_parameter * kest_extract_parameter_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict)
Definition at line 9 of file kest_dict_extract.c.
Referenced by kest_parameters_section_extract().
kest_extract_resource_from_dict()
kest_dsp_resource * kest_extract_resource_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict)
Definition at line 632 of file kest_dict_extract.c.
Referenced by kest_resources_section_extract().
kest_extract_setting_from_dict()
kest_setting * kest_extract_setting_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict)
Definition at line 276 of file kest_dict_extract.c.
Referenced by kest_settings_section_extract().