Kestrel Interface: kest_param_update.c File Reference
kest_param_update.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int kest_parameter_trigger_update (kest_parameter *param, float target)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_param_update.c.
Function Documentation
kest_parameter_trigger_update()
int kest_parameter_trigger_update (kest_parameter * param, float target)
Definition at line 276 of file kest_param_update.c.
Referenced by kest_cxt_set_input_gain(), kest_cxt_set_output_gain(), and parameter_widget_change_cb_inner().