Kestrel Interface: kest_block.c File Reference
kest_block.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (kest_block)
kest_block_operand operand_const_zero ()
kest_block_operand operand_const_one ()
kest_block_operand operand_const_minus_one ()
int kest_init_block (kest_block *block)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 8 of file kest_block.c.
Function Documentation
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (kest_block)
kest_init_block()
int kest_init_block (kest_block * block)
Definition at line 37 of file kest_block.c.
operand_const_minus_one()
kest_block_operand operand_const_minus_one ()
Definition at line 29 of file kest_block.c.
Referenced by kest_parse_asm_line(), and kest_process_asm_line().
operand_const_one()
kest_block_operand operand_const_one ()
Definition at line 21 of file kest_block.c.
Referenced by kest_parse_asm_line(), and kest_process_asm_line().
operand_const_zero()
kest_block_operand operand_const_zero ()
Definition at line 13 of file kest_block.c.
Referenced by kest_parse_asm_line(), and kest_process_asm_line().