Kestrel Interface: kest_fixed_point.h File Reference
kest_fixed_point.h File Reference
Functions
kest_fpga_sample_t float_to_q_nminus1 (float x, int shift)
int16_t float_to_q15 (float x)
int32_t float_to_q_nminus1_18bit (float x, int shift)
int kest_expression_compute_format (kest_expression *expr, kest_expr_scope *scope, int fmax, int width)
int kest_filter_compute_format (kest_filter *filter, kest_expr_scope *scope)
Function Documentation
float_to_q15()
int16_t float_to_q15 (float x)
Definition at line 44 of file kest_fixed_point.c.
float_to_q_nminus1()
kest_fpga_sample_t float_to_q_nminus1 (float x, int shift)
Definition at line 26 of file kest_fixed_point.c.
Referenced by kest_fpga_batch_append_block_register_updates(), kest_fpga_batch_append_block_regs(), kest_fpga_set_input_gain(), and kest_fpga_set_output_gain().
float_to_q_nminus1_18bit()
int32_t float_to_q_nminus1_18bit (float x, int shift)
Definition at line 9 of file kest_fixed_point.c.
Referenced by kest_fpga_batch_append_resource().
kest_expression_compute_format()
int kest_expression_compute_format (kest_expression * expr, kest_expr_scope * scope, int fmax, int width)
Definition at line 52 of file kest_fixed_point.c.
Referenced by kest_compute_register_formats(), and kest_filter_compute_format().
kest_filter_compute_format()
int kest_filter_compute_format (kest_filter * filter, kest_expr_scope * scope)
Definition at line 90 of file kest_fixed_point.c.
Referenced by kest_parser_compute_formats().