Kestrel Interface: kest_hfunc.h File Reference
kest_hfunc.h File Reference
Macros
#define binary_max(x, y)
#define binary_min(x, y)
#define sqr(x)
#define IBM(x)
#define range_bits(x, n, start)
#define place_bits(x, y, val)
Functions
char * binary_print_n (uint32_t x, int n)
char * binary_print_8 (uint8_t x)
char * binary_print_16 (uint16_t x)
char * binary_print_24 (uint32_t x)
char * binary_print_32 (uint32_t x)
int format_float (char *buf, float val, int max_len)
Macro Definition Documentation
binary_max
#define binary_max (x, y)
Value:
((x > y) ? x : y)
Definition at line 6 of file kest_hfunc.h.
Referenced by sw_field_save_cb().
binary_min
#define binary_min (x, y)
Value:
((x > y) ? y : x)
Definition at line 7 of file kest_hfunc.h.
Referenced by sw_field_save_cb().
IBM
#define IBM (x)
Value:
((1u << (x)) - 1)
Definition at line 20 of file kest_hfunc.h.
Referenced by kest_fpga_batch_print().
place_bits
#define place_bits (x, y, val)
Value:
((IBM((x)-(y)+1) & ((uint32_t)val)) << y)
Definition at line 24 of file kest_hfunc.h.
Referenced by kest_encode_dsp_block_instr_type_a(), and kest_encode_dsp_block_instr_type_b().
range_bits
#define range_bits (x, n, start)
Value:
(((x) >> (start)) & IBM(n))
Definition at line 22 of file kest_hfunc.h.
Referenced by kest_fpga_batch_append_16(), kest_fpga_batch_append_24(), kest_fpga_batch_append_32(), kest_fpga_batch_print(), print_instruction_format_a(), and print_instruction_format_b().
sqr
#define sqr (x)
Value:
(x * x)
Definition at line 9 of file kest_hfunc.h.
Function Documentation
binary_print_16()
char * binary_print_16 (uint16_t x)
Definition at line 30 of file kest_hfunc.c.
Referenced by kest_fpga_batch_print().
binary_print_24()
char * binary_print_24 (uint32_t x)
Definition at line 37 of file kest_hfunc.c.
Referenced by kest_fpga_batch_print().
binary_print_32()
char * binary_print_32 (uint32_t x)
Definition at line 42 of file kest_hfunc.c.
binary_print_8()
char * binary_print_8 (uint8_t x)
Definition at line 25 of file kest_hfunc.c.
binary_print_n()
char * binary_print_n (uint32_t x, int n)
Definition at line 8 of file kest_hfunc.c.
Referenced by binary_print_16(), binary_print_24(), binary_print_32(), and binary_print_8().
format_float()
int format_float (char * buf, float val, int max_len)
Definition at line 47 of file kest_hfunc.c.
Referenced by configure_parameter_widget(), format_parameter_widget_value_label(), and format_parameter_widget_value_label_v().