Kestrel Interface: kest_hfunc.c File Reference
kest_hfunc.c File Reference
#include <stdint.h>
#include <math.h>
#include "kest_hfunc.h"
Functions
char * binary_print_n (uint32_t x, int n)
char * binary_print_8 (uint8_t x)
char * binary_print_16 (uint16_t x)
char * binary_print_24 (uint32_t x)
char * binary_print_32 (uint32_t x)
int format_float (char *buf, float val, int max_len)
Variables
char binary_print_buffer [35]
Function Documentation
binary_print_16()
char * binary_print_16 (uint16_t x)
Definition at line 30 of file kest_hfunc.c.
Referenced by kest_fpga_batch_print().
binary_print_24()
char * binary_print_24 (uint32_t x)
Definition at line 37 of file kest_hfunc.c.
Referenced by kest_fpga_batch_print().
binary_print_32()
char * binary_print_32 (uint32_t x)
Definition at line 42 of file kest_hfunc.c.
binary_print_8()
char * binary_print_8 (uint8_t x)
Definition at line 25 of file kest_hfunc.c.
binary_print_n()
char * binary_print_n (uint32_t x, int n)
Definition at line 8 of file kest_hfunc.c.
Referenced by binary_print_16(), binary_print_24(), binary_print_32(), and binary_print_8().
format_float()
int format_float (char * buf, float val, int max_len)
Definition at line 47 of file kest_hfunc.c.
Referenced by configure_parameter_widget(), format_parameter_widget_value_label(), and format_parameter_widget_value_label_v().
Variable Documentation
binary_print_buffer
char binary_print_buffer[35]
Definition at line 6 of file kest_hfunc.c.
Referenced by binary_print_n().