Kestrel Interface: kest_expr_parser.c File Reference
kest_expr_parser.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 1
Functions
int kest_expression_token_unary_type (char *token)
int kest_expression_token_infix_type (char *token)
int kest_expression_infix_operator_precedence (int infix_type)
int kest_expression_infix_associativity (int infix_type)
kest_expression * kest_parse_expression_rec_pratt (kest_eff_parsing_state *ps, kest_token_ll *tokens, kest_token_ll **next_token, kest_token_ll *tokens_end, int min_binding_power, int depth)
kest_expression * kest_parse_expression (kest_eff_parsing_state *ps, kest_token_ll *tokens, kest_token_ll *tokens_end)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 1
Definition at line 4 of file kest_expr_parser.c.
Function Documentation
kest_expression_infix_associativity()
int kest_expression_infix_associativity (int infix_type)
Definition at line 59 of file kest_expr_parser.c.
Referenced by kest_parse_expression_rec_pratt().
kest_expression_infix_operator_precedence()
int kest_expression_infix_operator_precedence (int infix_type)
Definition at line 44 of file kest_expr_parser.c.
Referenced by kest_parse_expression_rec_pratt().
kest_expression_token_infix_type()
int kest_expression_token_infix_type (char * token)
Definition at line 31 of file kest_expr_parser.c.
Referenced by kest_parse_expression_rec_pratt().
kest_expression_token_unary_type()
int kest_expression_token_unary_type (char * token)
Definition at line 9 of file kest_expr_parser.c.
Referenced by kest_parse_expression_rec_pratt().
kest_parse_expression()
kest_expression * kest_parse_expression (kest_eff_parsing_state * ps, kest_token_ll * tokens, kest_token_ll * tokens_end)
Definition at line 200 of file kest_expr_parser.c.
Referenced by kest_parse_asm_arg(), kest_parse_asm_arg_2(), and kest_parse_dict_val().
kest_parse_expression_rec_pratt()
kest_expression * kest_parse_expression_rec_pratt (kest_eff_parsing_state * ps, kest_token_ll * tokens, kest_token_ll ** next_token, kest_token_ll * tokens_end, int min_binding_power, int depth)
Definition at line 72 of file kest_expr_parser.c.
Referenced by kest_parse_expression(), and kest_parse_expression_rec_pratt().