Kestrel Interface: kest_effect_select.h File Reference
kest_effect_select.h File Reference
Data Structures
struct kest_effect_selector_button
struct kest_effect_selector_str
Functions
DECLARE_LINKED_PTR_LIST (kest_effect_selector_button)
int init_effect_selector_button (kest_effect_selector_button *button, int index)
int init_effect_selector_button_from_effect (kest_effect_selector_button *button, kest_effect_desc *eff)
int init_effect_selector (kest_ui_page *page)
int init_effect_selector_eff (kest_ui_page *page)
int configure_effect_selector (kest_ui_page *page, void *data)
int create_effect_selector_ui (kest_ui_page *page)
int create_effect_selector_ui_eff (kest_ui_page *page)
int free_effect_selector_ui (kest_ui_page *page)
int enter_effect_selector (kest_ui_page *page)
int refresh_effect_selector (kest_ui_page *page)
void enter_effect_selector_cb (lv_event_t *e)
Function Documentation
configure_effect_selector()
int configure_effect_selector (kest_ui_page * page, void * data)
Definition at line 62 of file kest_effect_select.c.
create_effect_selector_ui()
int create_effect_selector_ui (kest_ui_page * page)
create_effect_selector_ui_eff()
int create_effect_selector_ui_eff (kest_ui_page * page)
Definition at line 158 of file kest_effect_select.c.
Referenced by init_effect_selector_eff().
DECLARE_LINKED_PTR_LIST()
DECLARE_LINKED_PTR_LIST (kest_effect_selector_button)
enter_effect_selector()
int enter_effect_selector (kest_ui_page * page)
Definition at line 190 of file kest_effect_select.c.
Referenced by init_effect_selector_eff().
enter_effect_selector_cb()
void enter_effect_selector_cb (lv_event_t * e)
Definition at line 11 of file kest_effect_select.c.
Referenced by configure_profile_view().
free_effect_selector_ui()
int free_effect_selector_ui (kest_ui_page * page)
init_effect_selector()
int init_effect_selector (kest_ui_page * page)
init_effect_selector_button()
int init_effect_selector_button (kest_effect_selector_button * button, int index)
init_effect_selector_button_from_effect()
int init_effect_selector_button_from_effect (kest_effect_selector_button * button, kest_effect_desc * eff)
Definition at line 131 of file kest_effect_select.c.
Referenced by init_effect_selector_eff().
init_effect_selector_eff()
int init_effect_selector_eff (kest_ui_page * page)
Definition at line 16 of file kest_effect_select.c.
Referenced by app_main(), and main_task().
refresh_effect_selector()
int refresh_effect_selector (kest_ui_page * page)
Definition at line 80 of file kest_effect_select.c.