Kestrel Interface: kest_menu.h File Reference
kest_menu.h File Reference
Data Structures
struct kest_menu_item
struct kest_menu_page_str
struct kest_main_menu_str
Macros
#define MENU_ITEM_TEXT_MAX_LEN 256
#define MENU_ITEM_PAD 0
#define MENU_ITEM_PAGE_LINK 1
#define MENU_ITEM_PAGE_LINK_INDIRECT 2
#define MENU_ITEM_CALLBACK_BUTTON 3
#define MENU_ITEM_PROFILE_LISTING 4
#define MENU_ITEM_SEQUENCE_LISTING 5
#define MENU_ITEM_PARAMETER_WIDGET 6
#define MENU_ITEM_DANGER_BUTTON 7
Functions
DECLARE_LINKED_PTR_LIST (kest_menu_item)
int init_menu_item (kest_menu_item *item)
int create_menu_item_ui (kest_menu_item *item, lv_obj_t *parent)
int delete_menu_item_ui (kest_menu_item *item)
int free_menu_item (kest_menu_item *item)
int refresh_menu_item (kest_menu_item *item)
int init_menu_page_str (kest_menu_page_str *str)
int init_menu_page (kest_ui_page *page)
int configure_menu_page (kest_ui_page *page, void *data)
int create_menu_page_ui (kest_ui_page *page)
int free_menu_page_ui (kest_ui_page *page)
int enter_menu_page (kest_ui_page *page)
int refresh_menu_page (kest_ui_page *page)
int menu_page_add_item (kest_menu_page_str *str, kest_menu_item *item)
int init_main_menu (kest_ui_page *page)
int configure_main_menu (kest_ui_page *page, void *data)
int create_main_menu_ui (kest_ui_page *page)
int enter_main_menu (kest_ui_page *page)
int menu_page_remove_item (kest_ui_page *page, kest_menu_item *item)
void enter_main_menu_cb (lv_event_t *e)
kest_menu_item * create_profile_listing_menu_item (char *text, kest_profile *profile, kest_ui_page *parent)
void profile_listing_delete_button_cb (lv_event_t *e)
void disappear_profile_listing_delete_button (lv_timer_t *timer)
void menu_item_profile_listing_released_cb (lv_event_t *e)
void menu_item_profile_listing_long_pressed_cb (lv_event_t *e)
int profile_listing_menu_item_refresh_active (struct kest_menu_item *item)
int profile_listing_menu_item_change_name (struct kest_menu_item *item, char *name)
Macro Definition Documentation
MENU_ITEM_CALLBACK_BUTTON
#define MENU_ITEM_CALLBACK_BUTTON 3
Definition at line 11 of file kest_menu.h.
Referenced by configure_menu_item(), and create_menu_item_ui().
MENU_ITEM_DANGER_BUTTON
#define MENU_ITEM_DANGER_BUTTON 7
Definition at line 15 of file kest_menu.h.
Referenced by configure_menu_item(), create_danger_button_menu_item(), and create_menu_item_ui().
MENU_ITEM_PAD
#define MENU_ITEM_PAD 0
Definition at line 8 of file kest_menu.h.
Referenced by configure_menu_item(), create_menu_item_ui(), and create_pad_menu_item().
MENU_ITEM_PAGE_LINK
#define MENU_ITEM_PAGE_LINK 1
Definition at line 9 of file kest_menu.h.
Referenced by configure_menu_item(), create_menu_item_ui(), and create_page_link_menu_item().
MENU_ITEM_PAGE_LINK_INDIRECT
#define MENU_ITEM_PAGE_LINK_INDIRECT 2
Definition at line 10 of file kest_menu.h.
Referenced by configure_menu_item(), create_menu_item_ui(), and create_page_linindirect_k_menu_item().
MENU_ITEM_PARAMETER_WIDGET
#define MENU_ITEM_PARAMETER_WIDGET 6
Definition at line 14 of file kest_menu.h.
Referenced by configure_menu_item(), create_menu_item_ui(), create_parameter_widget_menu_item(), and enter_menu_page().
MENU_ITEM_PROFILE_LISTING
#define MENU_ITEM_PROFILE_LISTING 4
Definition at line 12 of file kest_menu.h.
Referenced by configure_menu_item(), create_menu_item_ui(), create_profile_listing_menu_item(), and refresh_menu_item().
MENU_ITEM_SEQUENCE_LISTING
#define MENU_ITEM_SEQUENCE_LISTING 5
Definition at line 13 of file kest_menu.h.
Referenced by configure_menu_item(), create_menu_item_ui(), and create_sequence_listing_menu_item().
MENU_ITEM_TEXT_MAX_LEN
#define MENU_ITEM_TEXT_MAX_LEN 256
Definition at line 6 of file kest_menu.h.
Referenced by create_page_linindirect_k_menu_item(), create_page_link_menu_item(), create_profile_listing_menu_item(), and create_sequence_listing_menu_item().
Function Documentation
configure_main_menu()
int configure_main_menu (kest_ui_page * page, void * data)
Definition at line 779 of file kest_menu.c.
Referenced by init_main_menu().
configure_menu_page()
int configure_menu_page (kest_ui_page * page, void * data)
Definition at line 581 of file kest_menu.c.
Referenced by configure_menu_page(), and init_menu_page().
create_main_menu_ui()
int create_main_menu_ui (kest_ui_page * page)
Definition at line 858 of file kest_menu.c.
Referenced by init_main_menu().
create_menu_item_ui()
int create_menu_item_ui (kest_menu_item * item, lv_obj_t * parent)
Definition at line 357 of file kest_menu.c.
Referenced by create_menu_page_ui(), and sequence_list_add_cb().
create_menu_page_ui()
int create_menu_page_ui (kest_ui_page * page)
Definition at line 620 of file kest_menu.c.
Referenced by create_menu_page_ui(), and init_menu_page().
create_profile_listing_menu_item()
kest_menu_item * create_profile_listing_menu_item (char * text, kest_profile * profile, kest_ui_page * parent)
Definition at line 208 of file kest_menu.c.
DECLARE_LINKED_PTR_LIST()
DECLARE_LINKED_PTR_LIST (kest_menu_item)
delete_menu_item_ui()
int delete_menu_item_ui (kest_menu_item * item)
Definition at line 97 of file kest_menu.c.
Referenced by menu_page_remove_item().
disappear_profile_listing_delete_button()
void disappear_profile_listing_delete_button (lv_timer_t * timer)
Definition at line 297 of file kest_menu.c.
Referenced by menu_item_profile_listing_released_cb().
enter_main_menu()
int enter_main_menu (kest_ui_page * page)
Definition at line 918 of file kest_menu.c.
Referenced by init_main_menu().
enter_main_menu_cb()
void enter_main_menu_cb (lv_event_t * e)
Definition at line 743 of file kest_menu.c.
enter_menu_page()
int enter_menu_page (kest_ui_page * page)
Definition at line 661 of file kest_menu.c.
Referenced by init_menu_page().
free_menu_item()
int free_menu_item (kest_menu_item * item)
Definition at line 114 of file kest_menu.c.
Referenced by create_parameter_widget_menu_item(), and menu_page_remove_item().
free_menu_page_ui()
int free_menu_page_ui (kest_ui_page * page)
Definition at line 716 of file kest_menu.c.
Referenced by init_menu_page().
init_main_menu()
int init_main_menu (kest_ui_page * page)
Definition at line 748 of file kest_menu.c.
Referenced by kest_init_global_pages().
init_menu_item()
int init_menu_item (kest_menu_item * item)
Definition at line 11 of file kest_menu.c.
Referenced by create_danger_button_menu_item(), create_pad_menu_item(), create_page_linindirect_k_menu_item(), create_page_link_menu_item(), create_parameter_widget_menu_item(), create_profile_listing_menu_item(), and create_sequence_listing_menu_item().
init_menu_page()
int init_menu_page (kest_ui_page * page)
Definition at line 559 of file kest_menu.c.
Referenced by init_sequence_list().
init_menu_page_str()
int init_menu_page_str (kest_menu_page_str * str)
Definition at line 545 of file kest_menu.c.
Referenced by init_menu_page().
menu_item_profile_listing_long_pressed_cb()
void menu_item_profile_listing_long_pressed_cb (lv_event_t * e)
Definition at line 336 of file kest_menu.c.
Referenced by create_menu_item_ui().
menu_item_profile_listing_released_cb()
void menu_item_profile_listing_released_cb (lv_event_t * e)
Definition at line 306 of file kest_menu.c.
Referenced by create_menu_item_ui().
menu_page_add_item()
int menu_page_add_item (kest_menu_page_str * str, kest_menu_item * item)
Definition at line 726 of file kest_menu.c.
Referenced by configure_sequence_list(), and sequence_list_add_cb().
menu_page_remove_item()
int menu_page_remove_item (kest_ui_page * page, kest_menu_item * item)
Definition at line 926 of file kest_menu.c.
Referenced by profile_listing_delete_button_cb(), and sequence_listing_delete_button_cb().
profile_listing_delete_button_cb()
void profile_listing_delete_button_cb (lv_event_t * e)
Definition at line 277 of file kest_menu.c.
Referenced by create_menu_item_ui().
profile_listing_menu_item_change_name()
int profile_listing_menu_item_change_name (struct kest_menu_item * item, char * name)
Definition at line 262 of file kest_menu.c.
profile_listing_menu_item_refresh_active()
int profile_listing_menu_item_refresh_active (struct kest_menu_item * item)
Definition at line 231 of file kest_menu.c.
refresh_menu_item()
int refresh_menu_item (kest_menu_item * item)
Definition at line 126 of file kest_menu.c.
Referenced by refresh_menu_page().
refresh_menu_page()
int refresh_menu_page (kest_ui_page * page)
Definition at line 695 of file kest_menu.c.
Referenced by enter_menu_page().