Kestrel Interface: kest_allocator Struct Reference
kest_allocator Struct Reference
#include <kest_alloc.h>
Data Fields
void *(* alloc)(void *data, size_t)
void *(* realloc)(void *data, void *, size_t)
void(* free)(void *data, void *)
void * data
Detailed Description
Definition at line 6 of file kest_alloc.h.
Field Documentation
alloc
void *(* kest_allocator::alloc) (void *data, size_t)
Definition at line 7 of file kest_alloc.h.
Referenced by kest_allocator_alloc(), and kest_bump_arena_init().
data
void* kest_allocator::data
Definition at line 11 of file kest_alloc.h.
Referenced by kest_allocator_alloc(), kest_allocator_free(), kest_allocator_realloc(), and kest_bump_arena_init().
free
void(* kest_allocator::free) (void *data, void *)
Definition at line 9 of file kest_alloc.h.
Referenced by kest_allocator_free(), and kest_bump_arena_init().
realloc
void *(* kest_allocator::realloc) (void *data, void *, size_t)
Definition at line 8 of file kest_alloc.h.
Referenced by kest_allocator_realloc(), and kest_bump_arena_init().
The documentation for this struct was generated from the following file:
kest_alloc.h